### ISSUE TITLE
IO caused endpoint pods crash with PANIC - fs/fs_napi.cpp line 636

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6523] opened 2021-05-20 10:12 UTC
### Environment info
- NooBaa Version: master-20210517-nsfs 
- Platform: OCP 4.6.16

### Actual behavior
1. S3 IO caused endpoints crash with PANIC - fs/fs_napi.cpp line 636. The pods didn't recover itself.

### Expected behavior
1. S3 IO shouldn't cause any PANIC into endpoint pods. 

### Steps to reproduce
1. Created 3 accounts and 3 buckets - bucket-1, bucket-2.
bucket-1 = /nsfs/parent
bucket-2 = /nsfs/parent/dir2
bucket-3 = /nsfs/parent/dir3

2. Started IO on all 3 buckets using warp tool. It worked fine for 3 hours 
3. Found IO failing and endpoint crashed. 

```
[root@hpo-node1 ~]# ps -ef |grep warp
root      180756  117662 26 May19 pts/2    00:44:26 warp mixed --access-key=4YNRFT2HCsZ1MlVLamXy --secret-key=hA6nyOLcXMLkBUGnmtXNw9IB/3i7nehzLJHk1bJP --obj.size=1K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com --duration=4h --bucket=bucket-1 --debug --tls --insecure
root      180779  117695 25 May19 pts/3    00:41:47 warp mixed --access-key=PQk0Y2fYEDe0QRPA6xIw --secret-key=ihLl12FflDe6f/y04hl+jtiz0F/7mg3/E5mWtMVD --obj.size=4K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com --duration=4h --bucket=bucket-2 --debug --tls --insecure
root      180791  117721 26 May19 pts/4    00:44:24 warp mixed --access-key=2vWeT8V7GxpxjWx58ZPo --secret-key=50YRdvg7Lu0we8/ffpgQVrBdu8XPDIzhe9o1XeUE --obj.size=2K --host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com --duration=4h --bucket=bucket-3 --debug --tls --insecure
root      181177  181155  0 01:27 pts/6    00:00:00 grep --color=auto warp
```

`PANIC: FS::FileWrap::dtor: file not closed _path=/nsfs/parent/40UbANZ0/12170.)kvvRTgTbfzdlEAY.rnd _fd=60  function ~FileWrap file ../src/native/fs/fs_napi.cpp line 636`

```
[root@ocp-akshat-1-inf ~]# oc get pod -n noobaa
NAME                                               READY   STATUS                 RESTARTS   AGE
noobaa-core-0                                      1/1     Running                0          2d2h
noobaa-db-0                                        1/1     Running                0          2d2h
noobaa-default-backing-store-noobaa-pod-8f3b3033   0/1     Terminating            0          44h
noobaa-endpoint-75cf4844f6-858s5                   0/1     CreateContainerError   0          17h
noobaa-endpoint-75cf4844f6-rd6dd                   0/1     CreateContainerError   0          17h
noobaa-operator-fc5dbbb74-czm9l                    1/1     Running                0          2d4h
```

### More information - Screenshots / Logs / Other output

oc describe pod o/p:

```
Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Normal   Scheduled               16h                  default-scheduler        Successfully assigned noobaa/noobaa-endpoint-75cf4844f6-858s5 to worker2.ocp-akshat-1.cp.fyre.ibm.com
  Normal   SuccessfulAttachVolume  16h                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-950b978c-d1c8-40fb-bc76-6d5f0e385d00"
  Normal   AddedInterface          16h                  multus                   Add eth0 [10.254.16.193/22]
  Normal   Created                 16h                  kubelet                  Created container endpoint
  Normal   Started                 16h                  kubelet                  Started container endpoint
  Warning  Failed                  14m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id 149cb68bdb7a921acfe862f2de49df3e3d7ece5016ddbf1b7fc4aad42f20db62: name is reserved
  Warning  Failed                  13m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id 90e2dc7c83635bf77efd191da85647bc370722b23221493b28261fe54edbdec8: name is reserved
  Warning  Failed                  13m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id b6ca2a47853aec6c24c3189b06b3394553ad6167cedd2517dc305af7a0f7704e: name is reserved
  Warning  Failed                  11m (x2 over 14m)    kubelet                  Error: context deadline exceeded
  Warning  Failed                  11m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id f6fe249d90a6b3869efc9a05255443fa8555b61c82fdb575d38c142a008556f9: name is reserved
  Warning  Failed                  10m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id 851dec4290d400b07210ec89192ae5a3a5944fbcc6ba8dbb413d336a804835e1: name is reserved
  Warning  Failed                  10m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id 04dbc5b32fca71e4ab8e7f1acb0a723c049a4bd26a1c8d639c0e22fb4e031fbd: name is reserved
  Warning  Failed                  10m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id 37682bbd17f9d32e7e7a83e0a31ea9c62809f1721e5d5f49eef9692fa3e5d4c6: name is reserved
  Warning  Failed                  10m                  kubelet                  Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id b7b804e583830971c4ffc84baf12282b5a9294387fc12b1c96f16f1482262cf1: name is reserved
  Warning  Failed                  9m34s (x3 over 10m)  kubelet                  (combined from similar events): Error: Kubelet may be retrying requests that are timing out in CRI-O due to system load: error reserving ctr name k8s_endpoint_noobaa-endpoint-75cf4844f6-858s5_noobaa_96a4c576-dea6-4a3d-bf0d-a0e04c222e2d_1 for id aa1678edacd631cb32c28de0ae08d2c214ca8a5e3d8f939ddb239c06d3622bcd: name is reserved
  Normal   Pulled                  49s (x45 over 16h)   kubelet                  Container image "noobaa/noobaa-core:master-20210517-nsfs" already present on machine
```

Endpoint logs:
```

May-20 8:19:29.944 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/GWSpn5Kf/15709.gXDwjTLU3ESLQYD9.rnd', start: 0, end: Infinity }
May-20 8:19:29.946 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/cWaCm3os/10977.saEz7SN97DuIP(Hj.rnd', start: 0, end: Infinity }
May-20 8:19:29.947 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/1UExk9Wr/16891.vJ3t5ObdkSplwu)d.rnd', start: 0, end: Infinity }
May-20 8:19:29.947 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/40UbANZ0/17582.0v3a6EzWjfa61GIz.rnd', start: 0, end: Infinity }
May-20 8:19:29.947 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/AaqxCrtW/9558.O6nnXvJj2pSu2cEF.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/5Ubo6tPF/16848.8TU4ypThrL68ipX1.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/40UbANZ0/12170.)kvvRTgTbfzdlEAY.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/(pSD6yAw/14150.6)M(kABek6dGW1z3.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/jJrtTrxU/6788.DP7PzTnn2AYcSgU3.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/xsDKdVcg/14803.hV0SPIc1XgSJPRBo.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/cWaCm3os/17288.GRZa)KQdcbbiPWZI.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/Cpt2pD0V/17421.Ksh6e8RM(lQEE9zn.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/bzTjC)PM/16817.SzOPNeXARQ8DpN35.rnd', start: 0, end: Infinity }
May-20 8:19:29.948 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/Q5pDc(jq/9954.5RNU5CQCty6Ty)fp.rnd', start: 0, end: Infinity }
May-20 8:19:29.949 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/GWSpn5Kf/16037.C3VHKcqzayzwaWYS.rnd', start: 0, end: Infinity }
May-20 8:19:29.949 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/ittPiDnZ/15200.UjHTbm94mpZndxN1.rnd', start: 0, end: Infinity }
May-20 8:19:29.949 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/cWaCm3os/10977.saEz7SN97DuIP(Hj.rnd', start: 0, end: Infinity }
May-20 8:19:29.951 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/g7OCfjlX/9327.j(7(PnvRXeqnvdhq.rnd', start: 0, end: Infinity }
May-20 8:19:29.966 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/(pSD6yAw/16737.xSBJcaXsatoLLT4z.rnd', start: 0, end: Infinity }
May-20 8:19:29.967 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/HXnAtEDC/14784.8uU7KWHgmqisiTul.rnd', start: 0, end: Infinity }
May-20 8:19:29.967 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/GWSpn5Kf/15709.gXDwjTLU3ESLQYD9.rnd', start: 0, end: Infinity }
May-20 8:19:29.967 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/1UExk9Wr/17073.tPWjlbQ)DRbwwnXF.rnd', start: 0, end: Infinity }
May-20 8:19:30.011 [Endpoint/8]   [LOG] CONSOLE:: NamespaceFS: read_object_stream { file_path: '/nsfs/parent/dir3/IY5uF(yW/12269.SK8CIMURlP2HZLJa.rnd', start: 0, end: Infinity }
PANIC: FS::FileWrap::dtor: file not closed _path=/nsfs/parent/40UbANZ0/12170.)kvvRTgTbfzdlEAY.rnd _fd=60  function ~FileWrap file ../src/native/fs/fs_napi.cpp line 636
/noobaa_init_files/noobaa_init.sh: line 74:     8 Aborted                 $*




######################################################################
Thu May 20 08:19:30 UTC 2021 NooBaa: Process exited RIP (RC=134)
######################################################################

```

**Comment by akmithal** [comment] 2021-05-20 10:19
[noobaa_diagnostics_1621500574.tar.gz](https://github.com/noobaa/noobaa-core/files/6515001/noobaa_diagnostics_1621500574.tar.gz)

**Comment by jeniawhite** [comment] 2021-06-15 08:50
Looks like a duplicate of https://github.com/noobaa/noobaa-core/issues/6566

**Comment by nimrod-becker** [comment] 2021-06-24 07:27
@akmithal can we dup into 6566 ?

**Comment by nimrod-becker** [comment] 2021-06-28 10:23
Closing as dup of 6566

**Closed by nimrod-becker** 2021-06-28 10:23 UTC
Labels: NS-FS
