### ISSUE TITLE
Error "No space left on device" observed while running warp run I/O

### ISSUE THREAD

**Issue by NeeshaPan** [noobaa/noobaa-core#7078] opened 2022-09-21 11:43 UTC
### Environment info
Noobaa version
```
[root@hpo-app1 ~]# noobaa version
INFO[0000] CLI version: 5.11.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.10.0-20220120
INFO[0000] operator-image: noobaa/noobaa-operator:5.11.0
```

OC version
```
[root@hpo-app1 ~]# oc version
Client Version: 4.11.0
Kustomize Version: v4.5.4
Server Version: 4.11.0
Kubernetes Version: v1.24.0+9546431

```
ODF version
```
[root@hpo-app1 ~]# oc get csv
NAME                                   DISPLAY                       VERSION               REPLACES                          PHASE
mcg-operator.v4.11.1                   NooBaa Operator               4.11.1                mcg-operator.v4.11.0              Succeeded
metallb-operator.4.11.0-202208300306   MetalLB Operator              4.11.0-202208300306                                     Succeeded
ocs-operator.v4.11.1                   OpenShift Container Storage   4.11.1                ocs-operator.v4.11.0              Succeeded
odf-csi-addons-operator.v4.11.1        CSI Addons                    4.11.1                odf-csi-addons-operator.v4.11.0   Succeeded
odf-operator.v4.11.1                   OpenShift Data Foundation     4.11.1                odf-operator.v4.11.0              Succeeded
```

When running warp consecutively on 3 IP's, the run fails due to error "`warp: <ERROR> upload error: We encountered an internal error. Please try again`". On checking end-points logs, found that error i.e `"upload_stream had error:  [Error: No space left on device] { code: 'ENOSPC' }`  is returned for all runs.

### Actual behavior
1. Warp run is failing

### Expected behavior
1.Warp run should execute with any error.

### Steps to reproduce
1. Setup BM with CNSA/CSI RC4, ODF 4.11.1, latest DAS operator.
2. Run warp on all three metallb IPs with 3 different users.

### More information - Screenshots / Logs / Other output
[noobaa_diagnostics_1663759506.tar.gz](https://github.com/noobaa/noobaa-core/files/9616192/noobaa_diagnostics_1663759506.tar.gz)

**Comment by NeeshaPan** [comment] 2022-09-21 14:55
Started the 2hr run again with new buckets after changing the NOOBAA_LOG_LEVEL to nsfs and the issue is still reproducible.
We have enough disk space available on SC, still we are observing space issue while performing I/O.
Attaching noobaa diagnose log  and  /var/lib/pgsql/data/userdata/log/  after changing the log.

Snippet of end-point log
---------------------------
```
Sep-21 14:22:58.505 [Endpoint/14] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  [Error: No space left on device] { code: 'ENOSPC' }
Sep-21 14:22:58.506 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Message
>We encountered an internal error. Please try again.</Message><Resource>/bucket3/uj1VUA1T/155966.gr4iCZ4a%28zD2EHlf.rnd</Resource><RequestId>l8bpt1kl-9s7oa0-
qtb</RequestId></Error> PUT /bucket3/uj1VUA1T/155966.gr4iCZ4a%28zD2EHlf.rnd {"host":"10.49.0.105","user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.
5.2","content-length":"1000","authorization":"AWS4-HMAC-SHA256 Credential=7fvk34fEIHkL4qNbVZCk/20220921/us-east-1/s3/aws4_request, SignedHeaders=content-type
;host;x-amz-content-sha256;x-amz-date, Signature=00e91fd20ab20a56a45f149da3618c3b118546e3621d190cde5582a6322729ae","content-type":"application/octet-stream",
"x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20220921T142258Z"} Error: No space left on device
Sep-21 14:22:58.972 [Endpoint/14] [ERROR] core.sdk.namespace_fs:: _upload_stream had error:  [Error: No space left on device] { code: 'ENOSPC' }
Sep-21 14:22:58.972 [Endpoint/14] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>InternalError</Code><Messag$
>We encountered an internal error. Please try again.</Message><Resource>/bucket3/uj1VUA1T/155966.gr4iCZ4a%28zD2EHlf.rnd</Resource><RequestId>l8bpt1wx-kwytf-$
53</RequestId></Error> PUT /bucket3/uj1VUA1T/155966.gr4iCZ4a%28zD2EHlf.rnd {"host":"10.49.0.105","user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.$
.2","content-length":"1000","authorization":"AWS4-HMAC-SHA256 Credential=7fvk34fEIHkL4qNbVZCk/20220921/us-east-1/s3/aws4_request, SignedHeaders=content-type$
host;x-amz-content-sha256;x-amz-date, Signature=00e91fd20ab20a56a45f149da3618c3b118546e3621d190cde5582a6322729ae","content-type":"application/octet-stream",$
x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20220921T142258Z"} Error: No space left on device
```

noobaa diagnose log:
[noobaa_diagnostics_1663771890.tar.gz](https://github.com/noobaa/noobaa-core/files/9617790/noobaa_diagnostics_1663771890.tar.gz)


 /var/lib/pgsql/data/userdata/log/: 
[postgress.zip](https://github.com/noobaa/noobaa-core/files/9617767/postgress.zip)

**Comment by rkomandu** [comment] 2022-09-21 17:07
Just to mention, there is enough space at the backend (Storage Cluster) and that was also tracked while running the Warp IO. @NeeshaPan, Could that also be uploaded for reference ?

**Comment by guymguym** [comment] 2022-09-21 17:17
@romayalon raised the question if we were struck by a ulimit of open file descriptors on our endpoint.
@rkomandu @NeeshaPan - would you be able to verify if this is the case by entering the endpoint container and checking its configured ulimit vs the number of open files (with lsof)?
Thanks

**Comment by rkomandu** [comment] 2022-09-21 18:11
This is the current status on the hpofvt1 machine (neesha m/c) atm

```
for i in `oc get pods  |grep noobaa-endpoint | awk ' {print $1}'`; do oc rsh $i ulimit -n; oc rsh $i lsof |wc -l; echo $i is done; done
1048576
505
noobaa-endpoint-5c77fc9bd5-2g5zc is done
1048576
494
noobaa-endpoint-5c77fc9bd5-8tc4f is done
1048576
516
noobaa-endpoint-5c77fc9bd5-brx4w is done
1048576
483
noobaa-endpoint-5c77fc9bd5-ckhwd is done
1048576
494
noobaa-endpoint-5c77fc9bd5-hq2j8 is done
1048576
483
noobaa-endpoint-5c77fc9bd5-l7wrl is done
1048576
494
noobaa-endpoint-5c77fc9bd5-nlkp7 is done
1048576
483
noobaa-endpoint-5c77fc9bd5-pkrwm is done
1048576
483
noobaa-endpoint-5c77fc9bd5-zv7ld is done

```

**Comment by guymguym** [comment] 2022-09-21 22:55
Next up - @eshelmarc suggested to gather a fs trace of that ENOSPC reproduction. 
@rkomandu Is that something you know how to collect while reproducing the error?

**Comment by rkomandu** [comment] 2022-09-22 06:10
@guymguym , we are setting the trace level and @NeeshaPan is retrying on her cluster with new set of users. Will update once we have the data. May be we need to add in box note these files for further analysis by IBM GPFS team & Noobaa

**Comment by romayalon** [comment] 2022-09-22 07:42
@rkomandu @guymguym  I checked the higher debug level logs, I don’t see any PUT related File system log prints

**Comment by romayalon** [comment] 2022-09-22 07:45
@guymguym @ @rkomandu don't we want to see the ulimit/lsof result in a middle of the run when starting to see ENOSPC errors?

**Comment by rkomandu** [comment] 2022-09-22 08:31
@NeeshaPan is already running this on the cluster for the run she spawned in our morning. 

For reference: we don't see a SPC issue atm and the lsof etc is also fine with appropriate ulimit .

```
df -h /gpfs/hpofvt1
Filesystem      Size  Used Avail Use% Mounted on
hpofvt1         6.1T  2.0T  4.2T  32% /gpfs/hpofvt1

atm , first value is ulimit -n and the second one is lsof

1048576
571
noobaa-endpoint-5c77fc9bd5-2g5zc is done
1048576
615
noobaa-endpoint-5c77fc9bd5-8tc4f is done
1048576
538
noobaa-endpoint-5c77fc9bd5-brx4w is done
1048576
549
noobaa-endpoint-5c77fc9bd5-ckhwd is done
1048576
472
noobaa-endpoint-5c77fc9bd5-hq2j8 is done
1048576
494
noobaa-endpoint-5c77fc9bd5-l7wrl is done
1048576
527
noobaa-endpoint-5c77fc9bd5-nlkp7 is done
1048576
450
noobaa-endpoint-5c77fc9bd5-pkrwm is done
1048576
483
noobaa-endpoint-5c77fc9bd5-zv7ld is done

```

**Comment by romayalon** [comment] 2022-09-22 08:37
@rkomandu but do you see warp failures?

**Comment by rkomandu** [comment] 2022-09-22 09:07
this is Neesha system and she had run into Warp failure with the "specified key exist" for 1K obj size whereas the other runs of 2k and 50M has completed w/o the ENOSPC.. She will update the 7067 with the logs she has , may be you need to assist her on the system why is this happening on her system as these are new buckets. 

For this defect, @NeeshaPan  would rerun with 20M, 40M,50M for 2hrs (or whatever the combination she ran into this ENOSPC) in the endpoint logs earlier

**Comment by NeeshaPan** [comment] 2022-09-22 11:02
I had started run on 3IP's for 1k, 2k and 50m consecutively. For 2k and 50m run had completed without issues, however for 1k run observed https://github.com/noobaa/noobaa-core/issues/7076. Updated the defect with required logs.

**Comment by nimrod-becker** [comment] 2022-09-22 12:47
Looking at the DF output, is the PV really allocated with 6TB ?

**Comment by rkomandu** [comment] 2022-09-22 13:52
I don't think the disk output is taken into consideration when the PV is created with underlying CSI. 

noobaa-s3respv-4080029599                  50Gi       RWX            Retain           Bound    openshift-storage/noobaa-s3resvol-pvc-4080029599                                                            6d5h

**Comment by guymguym** [comment] 2022-09-22 16:11
@eshelmarc @romayalon I see that there are cases in libgpfs where ENOSPC is used to represent things which are not related to filesystem space, such as buffer too small - is that possibly our case?

Here for example -
https://github.com/noobaa/noobaa-core/blob/fc2f6099dc7566ba23dca2c462195a83077a24e0/src/native/fs/gpfs.h#L649-L650

**Comment by NeeshaPan** [comment] 2022-09-23 11:06
I ran the warp today consecutively for 2hrs for 1k, 2k and 50m object size and did not observe issue. The run completed successfully without any errors.

**Comment by nigamshaurya14** [comment] 2022-09-23 12:51
Ran warp today with 1k,10k and 100k object size and observed the No space left on device issue:

Logs were captured the moment error starts to occur:

[noobaa_diagnostics_1663934707.tar.gz](https://github.com/noobaa/noobaa-core/files/9633601/noobaa_diagnostics_1663934707.tar.gz)
[lsof_file_shaurya1.txt](https://github.com/noobaa/noobaa-core/files/9633622/lsof_file_shaurya1.txt)


Almost all Inodes were used during that no space left issue though diskspace was available:
```

[root@emshpo ~]# mmlsfileset hpofvt3 -i
Collecting fileset usage information ...
Filesets in file system 'hpofvt3':
Name                     Status    Path                                         InodeSpace      MaxInodes    AllocInodes     UsedInodes
root                     Linked    /gpfs/hpofvt3                                   0              2154496        2154496        2154456
pvc-cc206296-6c73-434a-8362-7b949bb016c2 Linked /gpfs/hpofvt3/pvc-cc206296-6c73-434a-8362-7b949bb016c2 1       200704 49152        1531
pvc-5f7ce287-815a-4a67-89a8-2602a9e2c9af Linked /gpfs/hpofvt3/pvc-5f7ce287-815a-4a67-89a8-2602a9e2c9af 2       200704 49152        4103
.msgq                    Linked    /gpfs/hpofvt3/.msgq                             0                    0              0              1
.audit_log               Linked    /gpfs/hpofvt3/.audit_log                        3               102400         102400             35
primary-fileset-remote-sample-12429638916813902899 Unlinked --                     8              1048576          65536              2
primary-fileset-remote-sample-12429638916815041112 Linked /gpfs/hpofvt3/primary-fileset-remote-sample-12429638916815041112 9       1048576 65536 4
[root@emshpo ~]# mmlsfileset hpofvt3 -i
Collecting fileset usage information ...
Filesets in file system 'hpofvt3':
Name                     Status    Path                                         InodeSpace      MaxInodes    AllocInodes     UsedInodes
root                     Linked    /gpfs/hpofvt3                                   0              2154496        2154496        2154462
pvc-cc206296-6c73-434a-8362-7b949bb016c2 Linked /gpfs/hpofvt3/pvc-cc206296-6c73-434a-8362-7b949bb016c2 1       200704 49152        1531
pvc-5f7ce287-815a-4a67-89a8-2602a9e2c9af Linked /gpfs/hpofvt3/pvc-5f7ce287-815a-4a67-89a8-2602a9e2c9af 2       200704 49152        4103
.msgq                    Linked    /gpfs/hpofvt3/.msgq                             0                    0              0              1
.audit_log               Linked    /gpfs/hpofvt3/.audit_log                        3               102400         102400             35
primary-fileset-remote-sample-12429638916813902899 Unlinked --                     8              1048576          65536              2
primary-fileset-remote-sample-12429638916815041112 Linked /gpfs/hpofvt3/primary-fileset-remote-sample-12429638916815041112 9       1048576 65536 4
[root@emshpo ~]# mmlsfileset hpofvt3 -i
Collecting fileset usage information ...
Filesets in file system 'hpofvt3':
Name                     Status    Path                                         InodeSpace      MaxInodes    AllocInodes     UsedInodes
root                     Linked    /gpfs/hpofvt3                                   0              2154496        2154496        2154456
pvc-cc206296-6c73-434a-8362-7b949bb016c2 Linked /gpfs/hpofvt3/pvc-cc206296-6c73-434a-8362-7b949bb016c2 1       200704 49152        1531
pvc-5f7ce287-815a-4a67-89a8-2602a9e2c9af Linked /gpfs/hpofvt3/pvc-5f7ce287-815a-4a67-89a8-2602a9e2c9af 2       200704 49152        4103
.msgq                    Linked    /gpfs/hpofvt3/.msgq                             0                    0              0              1
.audit_log               Linked    /gpfs/hpofvt3/.audit_log                        3               102400         102400             35
primary-fileset-remote-sample-12429638916813902899 Unlinked --                     8              1048576          65536              2
primary-fileset-remote-sample-12429638916815041112 Linked /gpfs/hpofvt3/primary-fileset-remote-sample-12429638916815041112 9       1048576 65536 4
[root@emshpo ~]#

```

Diskspace monitor logs:

[dfcommand.txt](https://github.com/noobaa/noobaa-core/files/9633673/dfcommand.txt)

warp run log file:
[warp-109ip.1K.shaurya.23Sep.log](https://github.com/noobaa/noobaa-core/files/9633701/warp-109ip.1K.shaurya.23Sep.log)
[warp-110ip.10k.shaurya.23Sep.log](https://github.com/noobaa/noobaa-core/files/9633722/warp-110ip.10k.shaurya.23Sep.log)
[warp-111ip.100K.shaurya.23Sep.log](https://github.com/noobaa/noobaa-core/files/9633730/warp-111ip.100K.shaurya.23Sep.log)

**Comment by eshelmarc** [comment] 2022-09-23 15:28
If you expected that this number of file 2154456 should have been created by this test, than you can view the inode-limit  with mmlsfs nad change/increase it with mmchfs. If not we might have some files that are not removed like maybe temp files?

**Comment by rkomandu** [comment] 2022-09-24 17:37
Ran Warp with 16/32/48M as obj sizes from 3 users concurrently for overnight on 6hrs (2 sizes), 12hrs (1 size) and ran out of Filesystem space. Chosen as the blocksize on OCP is about 16M as per the configuration.

 There is no recreate as such w/r/t ENOSPC after my above post and that ENOSPC proved to be due to running out of Inodes. 
 
 Will continue to run for 1 overnight run to check the results.

**Comment by rkomandu** [comment] 2022-09-27 04:16
Ran for 6hrs from 1 user for 10k obj size with appropriate inode setting and it ran successfully. 

```
 warp mixed --host=10.49.0.103  --access-key=37isnwvQs1ws7quB1S3m --secret-key=0t+p/+RDqG5Bq5Uk9BBXn7k/3xoIWmdtnNcygXbM --obj.size=10k --duration=360m --bucket=warp-103ip-26sep --debug --insecure --tls
warp: Benchmark data written to "warp-mixed-2022-09-26[142237]-iQBo.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Duration: 5h59m59s.
 * Throughput: 37.52 obj/s

Operation: GET, 45%, Concurrency: 20, Duration: 5h59m59s.
 * Throughput: 1.61 MiB/s, 168.83 obj/s

Operation: PUT, 15%, Concurrency: 20, Duration: 5h59m59s.
 * Throughput: 0.54 MiB/s, 56.28 obj/s

Operation: STAT, 30%, Concurrency: 20, Duration: 5h59m59s.
 * Throughput: 112.56 obj/s

Cluster Total: 2.15 MiB/s, 375.19 obj/s over 6h0m0s.
warp: Cleanup Done

```
Issue can be closed from my view. let us discuss in Noobaa Interlock call for a min before doing that.

**Comment by rkomandu** [comment] 2022-09-28 10:25
Finally could run for overnight(12hrs) with 10k object size , it ran successfully with the available inode and FS disk space. 

```
warp mixed --host=10.49.0.110 --access-key=lLGtTpuoYEn3aXkYcCcg --secret-key=t6q+chBxcTrrM/8OxqY3jhHqDid55MhWDlqD2rAU --obj.size=16k --duration=720m --bucket=newbucket-16k-27sep --debug --insecure --tls 2>&1 | tee /tmp/warp-110ip.16k.rkomandu-12hr.27Sep.log
warp: Benchmark data written to "warp-mixed-2022-09-27[130225]-SwXe.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Ran 11h59m59s.
 * Throughput: 434.55 obj/s

Operation: GET, 45%, Concurrency: 20, Ran 11h59m59s.
 * Throughput: 29.84 MiB/s, 1955.49 obj/s

Operation: PUT, 15%, Concurrency: 20, Ran 11h59m59s.
 * Throughput: 9.95 MiB/s, 651.83 obj/s

Operation: STAT, 30%, Concurrency: 20, Ran 11h59m59s.
 * Throughput: 1303.66 obj/s

Cluster Total: 39.78 MiB/s, 4345.53 obj/s over 12h0m0s.
warp: Cleanup Done

```

Discussed with @romayalon today in Noobaa interlock call and closing this.

**Comment by romayalon** [comment] 2022-09-28 10:26
closing it per @rkomandu last comment

**Closed by romayalon** 2022-09-28 10:26 UTC
