### ISSUE TITLE
Get object in namespaced s3 compatible bucket only returns first 4kiB

### ISSUE THREAD

**Issue by lallinger-arbeit** [noobaa/noobaa-core#6164] opened 2020-09-09 08:17 UTC
### Environment info
- NooBaa Version: master+74b79637d8a9a1dca2baf51598860579711a5c6b
- Platform: OKD 4.5

### Actual behavior
1. Performing a `GET` to any object in a namespaced bucket returns only the first 4kiB.

### Expected behavior
1. Performing a `GET` to any object in a namespaced bucket should return the full object

### Steps to reproduce
1. Create namespaced s3 compatible bucket
2. Upload an object
3. `GET` the object

### More information - Screenshots / Logs / Other output
Also the metadata of all objects is reported incorrectly, as `Content-Length` Noobaa always states `4096`.

As far as i can see [this commit](https://github.com/noobaa/noobaa-core/commit/abbafc463045736a4a2be973b1e15c282cb41d97) from @paulxuzhang  introduced the problem here:
https://github.com/noobaa/noobaa-core/blob/72a0fbc92ac4c29a98a8ab3eca3118a167860f5b/src/sdk/namespace_s3.js#L142-L144

Also i noticed that even when you send a headObject request to Noobaa this function (read_object_md) gets called and performs a getObject, instead of only calling headObject on the backend.

**Comment by guymguym** [comment] 2020-09-09 15:19
Might be related to this addition:
https://github.com/noobaa/noobaa-core/blob/bcc21725dd3ee45e73f05b87e7ac581d73f11b76/src/endpoint/s3/s3_utils.js#L279

We should try to add a unit test that fails on this issue.
@lallinger-arbeit Is it possible for you to take a stab?

**Comment by guymguym** [comment] 2020-09-09 20:29
@lallinger-arbeit A question - can you print the headers you get back on the GET response?

**Comment by guymguym** [comment] 2020-09-09 20:36
Actually wait, not sure the headers are needed.

**Comment by paulxuzhang** [comment] 2020-09-09 22:04
@guymguym Created PR https://github.com/noobaa/noobaa-core/pull/6167 for this issue. The root cause is that the changes supporting partNumber query parameter sets content-length to the one returned by hub, it ends up that content-length is set to Inline Range Length (4kb) for object with size > 4kb if partNumber query parameter is NOT set.

We should whether we have existing tests or create new for validating that.

**Comment by guymguym** [comment] 2020-09-22 07:33
Fixed by #6167

**Closed by guymguym** 2020-09-22 07:33 UTC
Labels: Comp-Namespace
