### ISSUE TITLE
Bucket has access issues if created outside of account's newbucketpath

### ISSUE THREAD

**Issue by PravinRanjan10** [noobaa/noobaa-core#7892] opened 2024-03-12 16:00 UTC
### Environment info
- NooBaa Version: **VERSION**

### Actual behavior
Consider the below scenario:
Bucket is having access issues if the bucket directory is created outside of account’s new bucket path. Details below
For example:
Create 2 accounts as below
       account-test6001, newBucketPath = /mnt/fs1/test6001,    uid=6001,  gid=6001
       account-test7001, newBucketPath = /mnt/fs1/test7001,     uid=7001,  gid=7001
2. Create a bucket bucket-7001 , Owner account is test7001, But directory path is /mnt/fs1/test6001/bucket-7001 # here, uid:gid of path /mnt/fs1/test6001 is 6001:6001 but owner of /mnt/fs1/test6001/bucket-7001 is 7001:7001
3. When I do IO using aws cli, it is giving me access denied.So the conclusion is , user should always create bucket under his own account newbucketspath.
### Expected behavior
1.
warning should be given to user, When manage_nsfs bucket add is be called, check that the owner has read and write access to the underlying directory.

### Steps to reproduce
1. see 1st section

### More information - Screenshots / Logs / Other output
Consider the below scenario:
Bucket is having access issues if the bucket directory is created outside of account’s new bucket path. Details below
For example:
Create 2 accounts as below
       account-test6001, newBucketPath = /mnt/fs1/test6001,    uid=6001,  gid=6001
       account-test7001, newBucketPath = /mnt/fs1/test7001,     uid=7001,  gid=7001
2. Create a bucket bucket-7001 , Owner account is test7001, But directory path is /mnt/fs1/test6001/bucket-7001 # here, uid:gid of path /mnt/fs1/test6001 is 6001:6001 but owner of /mnt/fs1/test6001/bucket-7001 is 7001:7001
3. When I do IO using aws cli, it is giving me access denied.So the conclusion is , user should always create bucket under his own account newbucketspath.
What’s your opinion on this, should noobaa verify the ownership of directory before allowing to create bucket? Because account’s details are with noobaa already.

Rom Ayalon:
[@Pravin]
 Although this might help with the user experience, I don't think we would like to create this kind of limitation because we will limit the user to only be able to export existing directories that are under his new_buckets_path.
This seems like a similar issue where we added a check when creating an account to check the permissions of its new_buckets_path.
So I suggest to add a similar check -
When manage_nsfs bucket add will be called, we will check that the owner has read and write access to the underlying directory.
[@Guy][@Pravin]
 WDYT?

Pravin Ranjan:
[@Romy Ayalon]
 Yes, (atleast warning should be given to user.), When manage_nsfs bucket add will be called, check that the owner has read and write access to the underlying directory.

Rom Ayalon
[@Pravin]
 is this the corresponding github issue - https://github.com/noobaa/noobaa-core/issues/7861 ?

Pravin Ranjan:
Yes. That's right 
[@Romy Ayalon]

Rom Ayalon:
so i'll update the issue with the last comments and we will take care of it :+1:
thanks for reporting 

Pravin Ranjan
Ohh. Sorry. The above issue link is different.
For this context I have not opened the issue yet. Was waiting for discussion and clarification. I will open a separate issue for this to track.

Rom Ayalon:
[@Pravin]
 but the only difference is that the bucket path is under and not exactly the other user's new_buckets_path, no? (edited) 

Pravin Ranjan:
So there are two issues.
1 . We discussed just now, the different owners of dir. In this case IO will fail.
2. If new_buckets_path is same as Path( parameter of bucket add) then, IO will pass but one bucket will be subfolder. Please read details of GitHub issue.

Pravin Ranjan:
We can setup a call, if you need some more detailed observations (apart from description mentioned in GitHub)

Madhu Thorat:
[@Romy Ayalon][@Pravin]
 While this case is being taken care, we should allow to create bucket at a path which is not owned by any other user. Like if:
account-test7001, newBucketPath = /mnt/fs1/test7001,    uid=7001, gid=7001
After this if account-test7001 tries to create a bucket at /mnt/fs1/mybucket7001 which is not below the ‘newBucketPath’ for the account-test7001 but is a valid path as no other user is owner of the path, so bucket should be allowed to create in this case.

Rom Ayalon:
[@madhu.thorat]
 yes exactly, we should not limit the path location of the bucket.
I suggested that on bucket creation we will check if the bucket owner's uid:gid can access (read and write) to the --path. 
[@madhu.thorat]
 WDYT?

Rom Ayalon:
[@Pravin]
 got your point regarding the github issue, but I don't think it's something that we would like to limit as well...
and please open a bug for the first issue :+1:

Madhu Thorat:
 I suggested that on bucket creation we will check if the bucket owner’s uid:gid can access (read and write) to the --path.
[@Romy Ayalon]
 I would suggest to check if the path given for bucket creation has a subpath/completepath owned by another account which is not in the same group, if yes then we can possibly avoid creation of bucket and given an error.

Madhu Thorat
WDYT ?

Rom Ayalon
but if the directory is public? (777) we still want to create it I think and the owner/group doesn't really matter, no?
did I understood correctly? if not please give an example (edited)

**Comment by shirady** [comment] 2024-03-13 06:50
Hi @PravinRanjan10,
If I understand the details correctly I think @romayalon already opened an issue #7883.
Please correct me if I'm wrong.

cc: @naveenpaul1

**Comment by naveenpaul1** [comment] 2024-03-15 05:07
duplicate of https://github.com/noobaa/noobaa-core/issues/7883

**Closed by naveenpaul1** 2024-03-15 05:07 UTC
