### ISSUE TITLE
Warp gives "The specified key does not exist." error

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6704] opened 2021-08-11 12:50 UTC
Environment info
NooBaa Version: master-20210809
Platform: OCP 4.7.13

### Actual behavior
1. Got The specified key does not exist while running warp

### Expected behavior
1. No error should be shown

### Steps to reproduce
1. Start two parallel instances of warp with same user and on same bucket
2. [root@fyreauto-x-app1 ~]# warp mixed --objects=300 --bucket=buck-1 --insecure --debug --tls --host=s3-noobaa.apps.ns.cp.fyr e.ibm.com --access-key=9RpKEfPS5AxuoNVgZ7Og --secret-key=t7a3yO5eAE+JOTiM3hjqUFCHT3Hmxrn7L9A8A3kY --duration=1800s  --obj.s ize=120M
warp: <ERROR> Command takes no arguments[root@fyreauto-x-app1 ~]# warp mixed --objects=300 --bucket=buck-2 --insecure --debu.ibm.com --access-key=EFiul4DdX7sWyOAszBNL --secret-key=++htUePTDRoqVF7gl1FMZRmSnrNQtNs+pHnwOdU+ --duration=1800s  --obj.size=120M
warp: <ERROR> upload error: The specified key does not exist.
warp: Benchmark data written to "warp-mixed-2021-08-11[044432]-fLpK.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Duration: 29m55s.
 * Throughput: 0.25 obj/s

Operation: GET, 45%, Concurrency: 20, Duration: 30m0s.
 * Throughput: 130.11 MiB/s, 1.14 obj/s

Operation: PUT, 15%, Concurrency: 20, Duration: 30m15s.
Errors: 1
 * Throughput: 43.21 MiB/s, 0.38 obj/s

Operation: STAT, 30%, Concurrency: 20, Duration: 29m59s.
 * Throughput: 0.76 obj/s

[root@fyreauto-x-app1 ~]# warp mixed --objects=200 --bucket=buck-2 --insecure --debug --tls --host=s3-noobaa.apps.ns.cp.fyre.ibm.com --access-key=EFiul4DdX7sWyOAszBNL --secret-key=++htUePTDRoqVF7gl1FMZRmSnrNQtNs+pHnwOdU+ --duration=900s  --obj.size=120M
warp: Benchmark data written to "warp-mixed-2021-08-11[043950]-kveQ.csv.zst"
Mixed operations.
Operation: DELETE, 10%, Concurrency: 20, Duration: 12m30s.
 * Throughput: 0.15 obj/s

Operation: GET, 45%, Concurrency: 20, Duration: 12m31s.
 * Throughput: 82.57 MiB/s, 0.72 obj/s

Operation: PUT, 13%, Concurrency: 20, Duration: 12m29s.
 * Throughput: 27.43 MiB/s, 0.24 obj/s

Operation: STAT, 30%, Concurrency: 20, Duration: 12m30s.
 * Throughput: 0.48 obj/s

Cluster Total: 108.74 MiB/s, 1.59 obj/s over 12m31s.
warp: Cleanup Done.[root@fyreauto-x-app1 ~]#

### More information - Screenshots / Logs / Other output
[single.tar.gz](https://github.com/noobaa/noobaa-core/files/6968484/single.tar.gz)

**Comment by akmithal** [comment] 2021-08-12 04:16
Hi @nehasharma5 , please correspond to relevant error in endpoint log for this - `"warp: upload error: The specified key does not exist."`

As part of the defect raise, we must provide our analysis so as to categorize them together and in priority.

**Comment by nehasharma5** [comment] 2021-08-19 10:26
@jeniawhite I tried this with 18 Aug build and endpoint log shows
32mAug-19 8:54:29.251[35m [Endpoint/14] [31m[ERROR][39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/hello-100/9HG78XG1/4.hCm%29jvCnhj2JBbVM.rnd</Resource><RequestId>ksiotkqh-ciyo2r-56t</RequestId></Error> PUT /hello-100/9HG78XG1/4.hCm%29jvCnhj2JBbVM.rnd {"user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.3.43","content-length":"1000","authorization":"AWS4-HMAC-SHA256 Credential=QP5JgCwWuJNasiwCXVty/20210819/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=665f39101b10609b1378763a1a73529398eecefb0717bed9a2c4d8bd8ec4bb2d","content-type":"application/octet-stream","x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20210819T085429Z","host":"s3-noobaa.apps.ns.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ns.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.97.157;host=s3-noobaa.apps.ns.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.97.157"} Error: No such file or directory
[32mAug-19 8:54:29.879[35m [Endpoint/14] [31m[ERROR][39m core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/hello-100/9HG78XG1/6.rZbek1n8bQiTdKnE.rnd</Resource><RequestId>ksiotl7g-63l76e-coh</RequestId></Error> PUT /hello-100/9HG78XG1/6.rZbek1n8bQiTdKnE.rnd {"user-agent":"MinIO (linux; amd64) minio-go/v7.0.11 warp/0.3.43","content-length":"1000","authorization":"AWS4-HMAC-SHA256 Credential=QP5JgCwWuJNasiwCXVty/20210819/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=ed55762dc6841bfb290fb52f00722623ada75e049374aee79fc6ec34bb09e8ee","content-type":"application/octet-stream","x-amz-content-sha256":"UNSIGNED-PAYLOAD","x-amz-date":"20210819T085429Z","host":"s3-noobaa.apps.ns.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ns.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.97.157;host=s3-noobaa.apps.ns.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.97.157"} Error: No such file or directory
[32mAug-19 8:54:54.541[35m [Endpoint/14] [36m  [LOG][39m CONSOLE:: update_endpoint_stats. namespace_stats = [ { io_stats: { read_count: [33m1279[39m, write_count: [33m459[39m, read_bytes: [33m21458059264[39m, write_bytes: [33m459000[39m, error_write_bytes: [33m0[39m, error_write_count: [33m0[39m, error_read_bytes: [33m0[39m, error_read_count: [33m0[39m }, namespace_resource_id: [32m'611e0163297b99002e5b5581'[39m } ]

**Comment by akmithal** [comment] 2021-08-19 11:09
Hi @jeniawhite , It is strange that I am not getting this error in my environment but Neha is easily able to reproduce it on her setup. This is coming with every recent build on her setup. 

Could this be due to a DB error and @jackyalbo can help too.

**Comment by akmithal** [comment] 2022-03-08 04:28
@nimrod-becker , please close this defect as I don't have permission to do so.

**Comment by nimrod-becker** [comment] 2022-03-08 07:52
Closing per last comments

**Closed by nimrod-becker** 2022-03-08 07:52 UTC
Labels: NS-FS
