### ISSUE TITLE
Deleting 375 buckets takes progressively longer and causes read timeout to mb later

### ISSUE THREAD

**Issue by nigamshaurya14** [noobaa/noobaa-core#6884] opened 2022-02-18 12:27 UTC
Bug Description

Not sure what is causing this. Don't know if it is a database problem or something else. We had a required test to delete 375 buckets. It was noted that it took progressively longer to delete the buckets.

[root@hpo-app3 ~]# while :
> do 
> s3s ls | wc
> sleep 300
> done
    295     885    9083
    277     831    8530
    261     783    8038
    242     726    7453
    225     675    6931
    208     624    6408
    190     570    5854
    173     519    5332
    155     465    4778
    137     411    4225
    121     363    3733
    110     330    3396
    101     303    3118
     96     288    2963
     92     276    2839
     87     261    2684
     83     249    2560
     79     237    2436
     74     222    2281
     70     210    2157
     65     195    2002
     61     183    1878
     57     171    1754
     52     156    1599
     48     144    1475
     44     132    1351
     39     117    1196
     35     105    1072
     31      93     948
     26      78     793
     22      66     669
     17      51     514
     13      39     390
      9      27     266
      4      12     111

After it was completed, I tried to make a bucket (mb) and it failed due to read time out:

[root@hpo-app3 ~]# time s3user1 mb s3://mokibucket1
make_bucket failed: s3://mokibucket1 Read timeout on endpoint URL: "http://10.49.0.100/mokibucket1"

real	3m3.495s
user	0m0.421s
sys	0m0.036

However, this is not a network connection problem or configuration problem:

[root@hpo-app3 ~]# time s3user1 ls
2022-02-17 16:38:55 test3
2022-02-17 16:38:55 test2
2022-02-17 16:38:55 bucket1

real	0m2.630s
user	0m0.436s
sys	0m0.039s

The end point pods are all properly labeled and running. root@hpo-infra1 ~]# oc get pods -o wide --show-labels | grep endpoint

noobaa-endpoint-7489b7bcf4-qsjk5                   1/1     Running   0            20h    10.128.1.64    hpo-dan3.hpoocp4.tuc.stglabs.ibm.com   <none>           <none>            app=noobaa,ibm-spectrum-scale-das-node=hpo-dan3.hpoocp4.tuc.stglabs.ibm.com,noobaa-s3=noobaa,pod-template-hash=7489b7bcf4
noobaa-endpoint-7489b7bcf4-x7g9f                   1/1     Running   0            20h    10.128.3.37    hpo-dan1.hpoocp4.tuc.stglabs.ibm.com   <none>           <none>            app=noobaa,ibm-spectrum-scale-das-node=hpo-dan1.hpoocp4.tuc.stglabs.ibm.com,noobaa-s3=noobaa,pod-template-hash=7489b7bcf4
noobaa-endpoint-7489b7bcf4-zg2rw                   1/1     Running   0            20h    10.128.4.248   hpo-dan2.hpoocp4.tuc.stglabs.ibm.com   <none>           <none>            app=noobaa,ibm-spectrum-scale-das-node=hpo-dan2.hpoocp4.tuc.stglabs.ibm.com,noobaa-s3=noobaa,pod-template-hash=7489b7bcf4
[root@hpo-infra1 ~]#

[root@hpo-infra1 ~]# oc get svc das-s3-hpo-dan1 -o json | grep selector -A2
        "selector": {
            "ibm-spectrum-scale-das-node": "hpo-dan1.hpoocp4.tuc.stglabs.ibm.com"
        },
[root@hpo-infra1 ~]#

I'm not sure if this is related, but another tester reported that, yesterday, they had deleted their david buckets via rb but they are still showing up in the export list:

[root@hpo-infra1 mokinew_issuue]# mmdas export list | grep -c david
70

I am marking this as sev 1 blocker for now b/c I'm not sure how to get out of it.  Perhaps, deleteing all of the exports, accounts and service would work.   But I am not sure.

The  must-gather is in Tucson Bare Metal Real World cluster's Infrastructure node in /root/GitIssues/

[root@hpo-infra1 mokinew_issuue]# noobaa status
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.9_nsfsfixes-20220208
INFO[0000] operator-image: quay.io/rhceph-dev/odf4-mcg-rhel8-operator@sha256:773dbaded46fa0a024c28a92f98f4ad64d370011ed1405f2b16f39b9258eb6b2
INFO[0000] noobaa-db-image: quay.io/rhceph-dev/rhel8-postgresql-12@sha256:da0b8d525b173ef472ff4c71fae60b396f518860d6313c4f3287b844aab6d622
INFO[0000] Namespace: openshift-storage
INFO[0000]
INFO[0000] CRD Status:
INFO[0000] ✅ Exists: CustomResourceDefinition "noobaas.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "backingstores.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "namespacestores.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "bucketclasses.noobaa.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "objectbucketclaims.objectbucket.io"
INFO[0000] ✅ Exists: CustomResourceDefinition "objectbuckets.objectbucket.io"
INFO[0000]
INFO[0000] Operator Status:
INFO[0000] ✅ Exists: Namespace "openshift-storage"
INFO[0000] ✅ Exists: ServiceAccount "noobaa"
INFO[0000] ✅ Exists: ServiceAccount "noobaa-endpoint"
INFO[0000] ✅ Exists: Role "mcg-operator.v4.9.3-noobaa-7fdbb75fd7"
INFO[0000] ✅ Exists: Role "mcg-operator.v4.9.3-noobaa-endpoint-65854bfccb"
INFO[0000] ✅ Exists: RoleBinding "mcg-operator.v4.9.3-noobaa-7fdbb75fd7"
INFO[0000] ✅ Exists: RoleBinding "mcg-operator.v4.9.3-noobaa-endpoint-65854bfccb"
INFO[0000] ✅ Exists: ClusterRole "mcg-operator.v4.9.3-644558fccd"
INFO[0000] ✅ Exists: ClusterRoleBinding "mcg-operator.v4.9.3-644558fccd"
INFO[0000] ✅ Exists: Deployment "noobaa-operator"
INFO[0000]
INFO[0000] System Wait Ready:
INFO[0000] ✅ System Phase is "Ready".
INFO[0000]
INFO[0000]
INFO[0000] System Status:
INFO[0000] ✅ Exists: NooBaa "noobaa"
INFO[0000] ✅ Exists: StatefulSet "noobaa-core"
INFO[0000] ✅ Exists: ConfigMap "noobaa-config"
INFO[0000] ✅ Exists: Service "noobaa-mgmt"
INFO[0000] ✅ Exists: Service "s3"
INFO[0000] ✅ Exists: Secret "noobaa-db"
INFO[0000] ✅ Exists: ConfigMap "noobaa-postgres-config"
INFO[0000] ✅ Exists: StatefulSet "noobaa-db-pg"
INFO[0000] ✅ Exists: Service "noobaa-db-pg"
INFO[0000] ✅ Exists: Secret "noobaa-server"
INFO[0000] ✅ Exists: Secret "noobaa-operator"
INFO[0000] ✅ Exists: Secret "noobaa-endpoints"
INFO[0000] ✅ Exists: Secret "noobaa-admin"
INFO[0000] ✅ Exists: Secret "noobaa-root-master-key"
INFO[0000] ✅ Exists: StorageClass "openshift-storage.noobaa.io"
INFO[0000] ✅ Exists: BucketClass "noobaa-default-bucket-class"
INFO[0000] ✅ Exists: Deployment "noobaa-endpoint"
INFO[0000] ✅ Exists: HorizontalPodAutoscaler "noobaa-endpoint"
INFO[0000] ✅ (Optional) Exists: BackingStore "noobaa-default-backing-store"
INFO[0000] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-aws-cloud-creds"
INFO[0000] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-azure-cloud-creds"
INFO[0000] ⬛ (Optional) Not Found: Secret "noobaa-azure-container-creds"
INFO[0000] ⬛ (Optional) Not Found: Secret "noobaa-gcp-bucket-creds"
INFO[0000] ⬛ (Optional) Not Found: CredentialsRequest "noobaa-gcp-cloud-creds"
INFO[0000] ✅ (Optional) Exists: PrometheusRule "noobaa-prometheus-rules"
INFO[0000] ✅ (Optional) Exists: ServiceMonitor "noobaa-mgmt-service-monitor"
INFO[0000] ✅ (Optional) Exists: ServiceMonitor "s3-service-monitor"
INFO[0000] ✅ (Optional) Exists: Route "noobaa-mgmt"
INFO[0000] ✅ (Optional) Exists: Route "s3"
INFO[0000] ✅ Exists: PersistentVolumeClaim "db-noobaa-db-pg-0"
INFO[0000] ✅ System Phase is "Ready"
INFO[0001] ✅ Exists: "noobaa-admin"

#------------------#
#- Mgmt Addresses -#
#------------------#

ExternalDNS : [https://noobaa-mgmt-openshift-storage.apps.hpoocp4.tuc.stglabs.ibm.com]
ExternalIP : []
NodePorts : [https://192.168.7.34:32545]
InternalDNS : [https://noobaa-mgmt.openshift-storage.svc:443]
InternalIP : [https://172.30.225.251:443]
PodPorts : [https://10.128.1.79:8443]

#--------------------#
#- Mgmt Credentials -#
#--------------------#

email : [admin@noobaa.io](mailto:admin@noobaa.io)[](https://github.ibm.com/moki)
password : 1o1MQwL+yRDAsSRF/9Rh0g==

#----------------#
#- S3 Addresses -#
#----------------#

ExternalDNS : [https://s3-openshift-storage.apps.hpoocp4.tuc.stglabs.ibm.com]
ExternalIP : []
NodePorts : [https://192.168.7.34:30741 https://192.168.7.33:30741 https://192.168.7.32:30741 https://192.168.7.33:30741]
InternalDNS : [https://s3.openshift-storage.svc:443]
InternalIP : [https://172.30.20.198:443]
PodPorts : [https://10.128.1.64:6443 https://10.128.5.114:6443 https://10.128.3.37:6443 https://10.128.4.248:6443]

#------------------#
#- S3 Credentials -#
#------------------#

#------------------#
#- Backing Stores -#
#------------------#

NAME TYPE TARGET-BUCKET PHASE AGE
noobaa-default-backing-store pv-pool Ready 72h26m7s

#------------------#
#- Bucket Classes -#
#------------------#

NAME PLACEMENT NAMESPACE-POLICY PHASE AGE
noobaa-default-bucket-class {"tiers":[{"backingStores":["noobaa-default-backing-store"]}]} null Ready 72h26m35s

#-----------------#
#- Bucket Claims -#
#-----------------#

No OBCs found.
Your environment

Tucson Real World Bare Metal Cluster
[root@hpo-infra1 [moki](https://github.ibm.com/moki)new_issuue]# oc get csv
NAME DISPLAY VERSION REPLACES PHASE
mcg-operator.v4.9.3 NooBaa Operator 4.9.3 mcg-operator.v4.9.2 Succeeded
ocs-operator.v4.9.3 OpenShift Container Storage 4.9.3 ocs-operator.v4.9.2 Succeeded
odf-operator.v4.9.3 OpenShift Data Foundation 4.9.3 odf-operator.v4.9.2 Succeeded
[root@hpo-infra1 mokinew_issuue]#
Steps to reproduce

    <Step 1>
    <Step 2>

Expected behaviour

**Comment by nilesh-bhosale** [comment] 2022-02-20 03:46
When I tried:
```
# s3user3 mb s3://david1001
make_bucket failed: s3://david1001 Read timeout on endpoint URL: "http://10.49.0.102/david1001"
```

The corresponding log messages seen on the respective noobaa-endpoint pod logs are:

```
Feb-18 3:23:49.105 [Endpoint/14]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: 'd78407e9-f528-4c40-b5de-4a974
270d297', hostname: 'noobaa-endpoint-7489b7bcf4-qsjk5' }
Feb-18 3:23:49.310 [Endpoint/14]  [WARN] core.util.postgres_client:: INVALID_SCHEMA_DB objectstats ERRORS [ { keyword: 'required', data
Path: '', schemaPath: '#/required', params: { missingProperty: 'system' }, message: "should have required property 'system'", schema: {
 _id: { objectid: true }, system: { objectid: true }, s3_usage_info: { type: 'object', additionalProperties: { type: 'integer' } }, s3_
errors_info: { type: 'object', additionalProperties: { type: 'integer' } } }, parentSchema: {
      id: 's3_usage_schema',
      type: 'object',
      required: [ 'system', 's3_usage_info', 's3_errors_info', [length]: 3 ],
      properties: { _id: { objectid: true }, system: { objectid: true }, s3_usage_info: { type: 'object', additionalProperties: { type:
 'integer' } }, s3_errors_info: { type: 'object', additionalProperties: { type: 'integer' } } },
      additionalProperties: false
    }, data: { _id: 620f1145c6609b000e929a1f } }, { keyword: 'required', dataPath: '', schemaPath: '#/required', params: { missingPrope
rty: 's3_usage_info' }, message: "should have required property 's3_usage_info'", schema: { _id: { objectid: true }, system: { objectid
: true }, s3_usage_info: { type: 'object', additionalProperties: { type: 'integer' } }, s3_errors_info: { type: 'object', additionalPro
perties: { type: 'integer' } } }, parentSchema: {
      id: 's3_usage_schema',
      type: 'object',
      required: [ 'system', 's3_usage_info', 's3_errors_info', [length]: 3 ],
      properties: { _id: { objectid: true }, system: { objectid: true }, s3_usage_info: { type: 'object', additionalProperties: { type:
 'integer' } }, s3_errors_info: { type: 'object', additionalProperties: { type: 'integer' } } },
      additionalProperties: false
    }, data: { _id: 620f1145c6609b000e929a1f } }, { keyword: 'required', dataPath: '', schemaPath: '#/required', params: { missingPrope
rty: 's3_errors_info' }, message: "should have required property 's3_errors_info'", schema: { _id: { objectid: true }, system: { object
id: true }, s3_usage_info: { type: 'object', additionalProperties: { type: 'integer' } }, s3_errors_info: { type: 'object', additionalP
roperties: { type: 'integer' } } }, parentSchema: {
      id: 's3_usage_schema',
      type: 'object',
      required: [ 'system', 's3_usage_info', 's3_errors_info', [length]: 3 ],
      properties: { _id: { objectid: true }, system: { objectid: true }, s3_usage_info: { type: 'object', additionalProperties: { type:
 'integer' } }, s3_errors_info: { type: 'object', additionalProperties: { type: 'integer' } } },
      additionalProperties: false
    }, data: { _id: 620f1145c6609b000e929a1f } }, [length]: 3 ] DOC { _id: 620f1145c6609b000e929a1f }
```

Although, I confirmed that the s3 endpoint is reachable from the app node.
```
# s3user3 ls s3://
2022-02-17 22:30:28 david131
2022-02-17 22:30:28 david130
2022-02-17 22:30:28 david129
2022-02-17 22:30:28 david128
2022-02-17 22:30:28 david127
2022-02-17 22:30:28 david126
...
...
``` 

on the same system, the db seems to be fine.
```
# noobaa api account_api read_account '{"email":"user3"}'
...
INFO[0000] ✅ RPC: account.read_account() Response OK: took 1.1ms
access_keys:
- access_key: fgyicDjikRF5jKKo3iEY
  secret_key: xBI6Q+ul3oiJIsvSWmqG4bg+fj4XWPOwPhbBFQq8
allowed_buckets:
  full_permission: true
can_create_buckets: true
default_resource: noobaa-s3res-4142975866
email: user3
external_connections:
  connections: []
  count: 0
has_login: false
has_s3_access: true
name: user3
nsfs_account_config:
  gid: 5003
  new_buckets_path: s5003/
  nsfs_only: true
  uid: 5003
preferences:
  ui_theme: DARK
systems:
- name: noobaa
  roles:
  - admin
```

**Comment by romayalon** [comment] 2022-02-24 08:54
@nigamshaurya14
From my initial investigation:
The difference between s3 mb and s3 ls is that mb communicates with the DB (delete bucket as well), 
I do see in the noobaa core pod the creation of the bucket DB entry but I never saw the folder created in the file system, 
I think that the root cause is the same as #6856

**Comment by akmithal** [comment] 2022-03-03 07:32
@romayalon : Please mark this as duplicate of 6856 and we can track this one just for defect validation.

**Comment by nimrod-becker** [comment] 2022-03-03 08:46
closing as dup of #6856

**Closed by nimrod-becker** 2022-03-03 08:46 UTC
Labels: NS-FS
