### ISSUE TITLE
Noobaa install using ocs method fails to create all pods

### ISSUE THREAD

**Issue by steve-delillo** [noobaa/noobaa-core#6534] opened 2021-05-26 16:17 UTC
### Environment info
- NooBaa Version:
[root@steve-may25-inf ~]# **noobaa version**
INFO[0000] CLI version: 5.8.0                           
INFO[0000] noobaa-image: noobaa/noobaa-core:5.8.0-20210418 
INFO[0000] operator-image: noobaa/noobaa-operator:5.8.0 

- Platform: OCP 4.7.4

### Expected behavior
We expected more pods to get created in the openshift-storage namespace after `noobaa system create ...` was ran, but as I show below, not all of the expected pods were created.

### Steps to reproduce
Used the following steps to attempt to install Noobaa:

[root@steve-may25-inf ~]# **wget https://raw.githubusercontent.com/openshift/ocs-operator/master/deploy/deploy-with-olm.yaml**
--2021-05-26 06:29:00--  https://raw.githubusercontent.com/openshift/ocs-operator/master/deploy/deploy-with-olm.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.109.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2268 (2.2K) [text/plain]
Saving to: ‘deploy-with-olm.yaml’

deploy-with-olm.yaml              100%[===========================================================>]   2.21K  --.-KB/s    in 0s      

2021-05-26 06:29:00 (37.6 MB/s) - ‘deploy-with-olm.yaml’ saved [2268/2268]

[root@steve-may25-inf ~]# **oc apply -f deploy-with-olm.yaml**
namespace/openshift-storage created
operatorgroup.operators.coreos.com/openshift-storage-operatorgroup created
catalogsource.operators.coreos.com/ocs-catalogsource created
subscription.operators.coreos.com/ocs-subscription created
[root@steve-may25-inf ~]# 

To check:
[root@steve-may25-inf ~]# **oc get pods -n openshift-storage**
NAME                                                             READY   STATUS    RESTARTS   AGE
noobaa-operator-77d6d465c4-wgzdr        1/1        Running     0                   60s
ocs-metrics-exporter-597fd6976-ntmxr    1/1        Running     0                   57s
ocs-operator-77f8866bc8-jg8ml                 1/1       Running     0                    62s
rook-ceph-operator-768656f47b-wvks2    1/1       Running     0                     61s
[root@steve-may25-inf ~]# 

[root@steve-may25-inf ~]# **oc cp -n openshift-storage noobaa-operator-77d6d465c4-wgzdr:/usr/local/bin/noobaa-operator /usr/local/bin/noobaa**
tar: Removing leading `/' from member names
[root@steve-may25-inf ~]# 

[root@steve-may25-inf ~]# **ls -ltr /usr/local/bin/noobaa**
-rw-r--r-- 1 root root 59166397 May 26 06:34 /usr/local/bin/noobaa

[root@steve-may25-inf ~]# **chmod +x /usr/local/bin/noobaa**

[root@steve-may25-inf ~]# **noobaa system create --db-storage-class='ibm-spectrum-scale-csi-fileset' --pv-pool-default-storage-class='ibm-spectrum-scale-csi-fileset'**
INFO[0006] ✅ Created: Namespace "ibm-spectrum-scale-csi-driver" 
INFO[0006] ✅ Created: NooBaa "noobaa"                   
[root@steve-may25-inf ~]# 

Only produced the following pods:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/84864338/119695217-d18fb400-be02-11eb-8838-4998cafeb2d0.png">

However, according to our instructions, we should be getting more pods, like noobaa-core, noobaa-db, etc.  Example:
NAME                                               READY   STATUS    RESTARTS   AGE
noobaa-core-0                                      1/1     Running   0          4m28s
noobaa-db-0                                        1/1     Running   0          4m28s
noobaa-default-backing-store-noobaa-pod-a9c2bc0e   1/1     Running   0          2m26s
noobaa-endpoint-846cd688d8-vfpfq                   1/1     Running   0          2m50s
noobaa-operator-7d69f7b694-xlktr                   1/1     Running   0          20m
ocs-metrics-exporter-66b8747855-vg62p              1/1     Running   0          20m
ocs-operator-8d9ddf87c-k5z4l                       1/1     Running   0          20m
rook-ceph-operator-7dd954cf46-924k6                1/1     Running   0          20m

### More information - Screenshots / Logs / Other output

Here are the PVCs and SCs that existed on the cluster at the time the issue occurred.

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/84864338/119700753-75c82980-be08-11eb-9be8-0c129805f168.png">

**Comment by steve-delillo** [comment] 2021-05-26 18:44
[must-gather.tar.gz](https://github.com/noobaa/noobaa-core/files/6549013/must-gather.tar.gz)

**Comment by nimrod-becker** [comment] 2021-06-02 16:34
@steve-delillo you need to create/apply the noobaa CR, it won't happen automatically.
It is created as part of creating a StorageCluster instance, which we don't want in this case. So the NooBaa CR has to be applied manually

**Comment by nimrod-becker** [comment] 2021-06-30 18:07
@steve-delillo is the issue still reproducible?

**Comment by nimrod-becker** [comment] 2021-07-04 14:30
Closing since it seems the NooBaa CR was not created, if it was, or the case issue still occurs, please reopen or drop a comment

**Closed by nimrod-becker** 2021-07-04 14:30 UTC
Labels: NS-FS
