### ISSUE TITLE
Operator pod shows panic and restarted when shutting down the node on which endpoint is scheduled

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6674] opened 2021-07-23 06:58 UTC
### Environment info
[root@api.ns.cp.fyre.ibm.com ~]# oc version
Client Version: 4.7.13
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210719
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#

### Actual behavior
1. Operator pod shows panic and restarted when shutting down the node on which endpoint is scheduled

### Expected behavior
1. No panic should be shown in operator logs and operator pod should not have restarted

### Steps to reproduce
1. Install noobaa and start a copy object operation into a bucket
2. While doing copy operation shutdown the node on which noobaa is installed (I have only endpoint pod scheduled on that node , no other noobaa pode)
3. Start the node

Inf node:
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod -o wide
```
NAME READY STATUS RESTARTS AGE IP NODE NOMINATED NODE READINESS GATES
noobaa-core-0 1/1 Running 0 73m 10.254.3.167 master1.ns.cp.fyre.ibm.com
noobaa-db-pg-0 1/1 Running 0 60m 10.254.4.17 master0.ns.cp.fyre.ibm.com
noobaa-default-backing-store-noobaa-pod-62daf8d7 0/1 Terminating 0 38m master2.ns.cp.fyre.ibm.com
noobaa-endpoint-565dbbd667-gfzt2 1/1 Running 0 74m 10.254.4.14 master0.ns.cp.fyre.ibm.com
noobaa-operator-6d54447bc5-hr7sb 1/1 Running 1 19h 10.254.3.136 master1.ns.cp.fyre.ibm.com
```
[root@api.ns.cp.fyre.ibm.com ~]#
### More information - Screenshots / Logs / Other output
[operator.log](https://github.com/noobaa/noobaa-core/files/6867472/operator.log)
[must-gather.local.2716179569581607829.tar.gz](https://github.com/noobaa/noobaa-core/files/6867475/must-gather.local.2716179569581607829.tar.gz)

**Comment by igorpick** [comment] 2021-07-27 09:10
Hello,
could you please provide the nodes status to me by:
```
kubectl get nodes -o wide
```
or
```
oc get nodes -o wide
```

Thank you

**Comment by nehasharma5** [comment] 2021-07-27 09:24
[root@api.ns.cp.fyre.ibm.com ~]# oc get nodes -o wide
NAME                         STATUS   ROLES           AGE   VERSION           INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                                       KERNEL-VERSION                 CONTAINER-RUNTIME
master0.ns.cp.fyre.ibm.com   Ready    master,worker   31d   v1.20.0+df9c838   10.17.39.219   <none>        Red Hat Enterprise Linux CoreOS 47.83.202105220305-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-12.rhaos4.7.git9f7be76.el8
master1.ns.cp.fyre.ibm.com   Ready    master,worker   31d   v1.20.0+df9c838   10.17.41.53    <none>        Red Hat Enterprise Linux CoreOS 47.83.202105220305-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-12.rhaos4.7.git9f7be76.el8
master2.ns.cp.fyre.ibm.com   Ready    master,worker   31d   v1.20.0+df9c838   10.17.49.179   <none>        Red Hat Enterprise Linux CoreOS 47.83.202105220305-0 (Ootpa)   4.18.0-240.22.1.el8_3.x86_64   cri-o://1.20.2-12.rhaos4.7.git9f7be76.el8
[root@api.ns.cp.fyre.ibm.com ~]#

**Comment by igorpick** [comment] 2021-08-02 12:36
HI,
cannot reproduce the issue, but according to the panic log, the operator gets an internal error in util.kubeCreateSkipOrFailExisting method from kubernetes that cannot complete the owner permission enforcement validation:  
Internal error occurred: admission plugin \"OwnerReferencesPermissionEnforcement\" failed to complete validation in 13s  

The method maps most known errors and throws a panic once received unknown one.   
I suggest to convert the panic to temporary error, print unknown kubernetes errors to the log and reconcile the process again.

**Comment by dannyzaken** [comment] 2021-08-04 13:16
AFAIU it’s not a recurring panic, and after the operator restarted it did not happen again. @nehasharma5 am I right? 

if so I think we should keep the panic and not change it. the panic is there to avoid silent failures when encountering unknown errors. if we see that this specific error is repeating in many cases maybe we can ignore it specifically, but I wouldn't remove the panic entirely.
@igorpick @nimrod-becker WDYT?

**Comment by dannyzaken** [comment] 2021-08-12 12:44
@nehasharma5 @akmithal do you have any new info on this? 

if this panic was a one-time thing I don't think we should remove the call to `panic`. if it is a recurring panic and the pod is in a crash loop due to the same error it should be addressed. please comment

@nimrod-becker @guymguym WDYT?

**Comment by nimrod-becker** [comment] 2021-08-16 08:07
I think we can add ignore to the specific error

**Comment by nehasharma5** [comment] 2021-08-17 09:08
Getting this PANIC too operator logs with 15 Aug build
time="2021-08-17T09:00:52Z" level=panic msg="☠️  Panic Attack: [] etcdserver: request timed out"
E0817 09:00:52.912814       1 runtime.go:78] Observed a panic: &logrus.Entry{Logger:(*logrus.Logger)(0xc000288540), Data:logrus.Fields{}, Time:time.Time{wall:0xc03efc9136656400, ext:18311349035, loc:(*time.Location)(0x322a0e0)}, Level:0x0, Caller:(*runtime.Frame)(nil), Message:"☠️  Panic Attack: [] etcdserver: request timed out", Buffer:(*bytes.Buffer)(nil), Context:(*context.emptyCtx)(0xc0001381e8), err:""} (&{0xc000288540 map[] 2021-08-17 09:00:52.9126144 +0000 UTC m=+18.311349035 panic <nil> ☠️  Panic Attack: [] etcdserver: request timed out <nil> context.TODO })
goroutine 841 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x209f760, 0xc0005fa4d0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x95
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x89
panic(0x209f760, 0xc0005fa4d0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:969 +0x1b9
github.com/sirupsen/logrus.Entry.log(0xc000288540, 0xc00036aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0005cef50, 0x0, 0xc0010ed798, 0x1, 0x1)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc0005cef50, 0x0, 0x210683d, 0x1d, 0xc0010ed7f8, 0x2, 0x2)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:371
github.com/noobaa/noobaa-operator/v5/pkg/util.Panic(0x241cda0, 0xc000658500)
        noobaa-operator/pkg/util/util.go:680 +0xf3
github.com/noobaa/noobaa-operator/v5/pkg/util.KubeCheck(0x24962e0, 0xc001098000, 0x0)
        noobaa-operator/pkg/util/util.go:448 +0x23d
github.com/noobaa/noobaa-operator/v5/pkg/system.CheckSystem(0xc001098000, 0xc000000004)
        noobaa-operator/pkg/system/system.go:913 +0x58
github.com/noobaa/noobaa-operator/v5/pkg/system.(*Reconciler).Reconcile(0xc00000a5a0, 0x6, 0xc0008ab994, 0x6, 0x2481240)
        noobaa-operator/pkg/system/reconciler.go:317 +0x93
github.com/noobaa/noobaa-operator/v5/pkg/controller/noobaa.Add.func1(0x2464ea0, 0xc000aff080, 0xc0008ab9aa, 0x6, 0xc0008ab994, 0x6, 0x1f7d280, 0xc000aff080, 0x1e215c0, 0x325bf20)
        noobaa-operator/pkg/controller/noobaa/noobaa_controller.go:53 +0x113
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc0006c70e0, 0x2464ea0, 0xc000aff080, 0xc0008ab9aa, 0x6, 0xc0008ab994, 0x6, 0xc000aff080, 0x40a2df, 0xc00003a000, ...)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000c0a1e0, 0x2464de0, 0xc000720040, 0x1eb1a60, 0xc0003fdb60)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000c0a1e0, 0x2464de0, 0xc000720040, 0x0)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x2464de0, 0xc000720040)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000073750)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0010edf50, 0x241d020, 0xc000aff020, 0xc000720001, 0xc0001145a0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xad
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000073750, 0x3b9aca00, 0x0, 0x1, 0xc0001145a0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext(0x2464de0, 0xc000720040, 0xc000312f70, 0x3b9aca00, 0x0, 0x1)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0xa6
k8s.io/apimachinery/pkg/util/wait.UntilWithContext(0x2464de0, 0xc000720040, 0xc000312f70, 0x3b9aca00)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:99 +0x57
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213 +0x45e
panic: (*logrus.Entry) 0xc0005fa4d0 [recovered]
        panic: (*logrus.Entry) 0xc0005fa4d0

goroutine 841 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x10c
panic(0x209f760, 0xc0005fa4d0)
        /opt/hostedtoolcache/go/1.15.15/x64/src/runtime/panic.go:969 +0x1b9
github.com/sirupsen/logrus.Entry.log(0xc000288540, 0xc00036aae0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:259 +0x345
github.com/sirupsen/logrus.(*Entry).Log(0xc0005cef50, 0x0, 0xc0010ed798, 0x1, 0x1)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:287 +0xf0
github.com/sirupsen/logrus.(*Entry).Logf(0xc0005cef50, 0x0, 0x210683d, 0x1d, 0xc0010ed7f8, 0x2, 0x2)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:333 +0xe5
github.com/sirupsen/logrus.(*Entry).Panicf(...)
        noobaa-operator/vendor/github.com/sirupsen/logrus/entry.go:371
github.com/noobaa/noobaa-operator/v5/pkg/util.Panic(0x241cda0, 0xc000658500)
        noobaa-operator/pkg/util/util.go:680 +0xf3
github.com/noobaa/noobaa-operator/v5/pkg/util.KubeCheck(0x24962e0, 0xc001098000, 0x0)
        noobaa-operator/pkg/util/util.go:448 +0x23d
github.com/noobaa/noobaa-operator/v5/pkg/system.CheckSystem(0xc001098000, 0xc000000004)
        noobaa-operator/pkg/system/system.go:913 +0x58
github.com/noobaa/noobaa-operator/v5/pkg/system.(*Reconciler).Reconcile(0xc00000a5a0, 0x6, 0xc0008ab994, 0x6, 0x2481240)
        noobaa-operator/pkg/system/reconciler.go:317 +0x93
github.com/noobaa/noobaa-operator/v5/pkg/controller/noobaa.Add.func1(0x2464ea0, 0xc000aff080, 0xc0008ab9aa, 0x6, 0xc0008ab994, 0x6, 0x1f7d280, 0xc000aff080, 0x1e215c0, 0x325bf20)
        noobaa-operator/pkg/controller/noobaa/noobaa_controller.go:53 +0x113
sigs.k8s.io/controller-runtime/pkg/reconcile.Func.Reconcile(0xc0006c70e0, 0x2464ea0, 0xc000aff080, 0xc0008ab9aa, 0x6, 0xc0008ab994, 0x6, 0xc000aff080, 0x40a2df, 0xc00003a000, ...)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/reconcile/reconcile.go:102 +0x6f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000c0a1e0, 0x2464de0, 0xc000720040, 0x1eb1a60, 0xc0003fdb60)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298 +0x317
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000c0a1e0, 0x2464de0, 0xc000720040, 0x0)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2(0x2464de0, 0xc000720040)
        noobaa-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:216 +0x4a
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1()
        noobaa-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:185 +0x37
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000073750)

**Comment by igorpick** [comment] 2021-08-17 14:53
@nehasharma5 
The last panic is not equal to the previous one. According to the last, kubernetes got "etcdserver timeout" error, however from previous one, kubernetes got "failed to complete validation" internal error.
I think the root cause the same (shutdown master node), but the errors are not equal. 
one of the solutions is to add some error handler, which will print the errors to the log and count them. 
If there were many such errors within some period (1 min), throw the panic and restart the pod.
@nimrod-becker @guymguym what do you think?

**Comment by liranmauda** [comment] 2021-08-17 14:56
> @nehasharma5
> The last panic is not equal to the previous one. According to the last, kubernetes got "etcdserver timeout" error, however from previous one, kubernetes got "failed to complete validation" internal error.
> I think the root cause the same (shutdown master node), but the errors are not equal.
> one of the solutions is to add some error handler, which will print the errors to the log and count them.
> If there were many such errors within some period (1 min), throw the panic and restart the pod.
> @nimrod-becker @guymguym what do you think?

The  "etcdserver timeout" error is the Panic in https://github.com/noobaa/noobaa-operator/issues/714

**Comment by nimrod-becker** [comment] 2021-08-17 14:59
So it seems we have same RC for several things here...

Question is, can our operator do something if etcd is not functioning? I remember seeing these kinds of errors before, it usually means that everything is pretty messed up... Are we trying to reduce exists of the operator here?

@baum might have some insights with his latest work on the rescheduling

**Comment by nehasharma5** [comment] 2021-08-18 09:35
@liranmauda The Panic which was earlier mentioned originally in this bug came when during IO I shutdown the node on which endpoint is scheduled as I am getting continuously etcdserver: request timed out . May be once that is resolved the original Panic for which this bug was raised start coming again. We should resolve it for the Panic this bug is raised

**Comment by dannyzaken** [comment] 2021-08-19 07:52
@Igor and I discussed a solution that instead of panicking immediately when encountering an unknown error, the operator will return a temp error and the reconcile will requeu. If it reoccurs several times then the operator will panic.
@nimrod-becker WDYT?

**Comment by nehasharma5** [comment] 2021-10-01 09:00
On bare metal This issue is not observed

**Comment by nimrod-becker** [comment] 2021-10-31 07:29
See Danny's comment, would go with that solution.
That would mainly remove the initiated panic, but its still an unknown problem

**Comment by akmithal** [comment] 2021-12-28 09:35
@dannyzaken , @nimrod-becker , please guide on the next step on this one.

**Comment by nimrod-becker** [comment] 2022-01-06 15:32
The choice is between continuing to operate on an unknown error which can lead to unknown behaviour
or panic , start again on a clean state.

I think we should keep the current behavior

**Comment by akmithal** [comment] 2022-02-01 05:40
Ok, closing this bug. Thanks @nimrod-becker

**Comment by akmithal** [comment] 2022-03-08 04:29
@nimrod-becker , please close it.

**Comment by nimrod-becker** [comment] 2022-03-08 07:52
Closing per last comments

**Closed by nimrod-becker** 2022-03-08 07:52 UTC
Labels: NS-FS
