### ISSUE TITLE
warp list --versions failing with NamespaceFS: Version dir not found

### ISSUE THREAD

**Issue by muenchp1** [noobaa/noobaa-core#8429] opened 2024-10-03 12:59 UTC
### Environment info
- NooBaa Version: noobaa-core-5.17.0-20240926.el9.s390x
- Platform: Linux on Z

### Actual behavior
1. Running warp list --versions=5 showing a large number of NamespaceFS: Version dir not found,
/var/log/noobaa.log
Oct  3 14:29:32 gshtc1d.fpet.pokprv.stglabs.ibm.com noobaa[1411664]: [nsfs/1411664] ESC[36m   [L0]ESC[39m core.sdk.namespace_fs:: NamespaceFS: Version dir not found,  /ibm/gpfs1/warpio/testbucket2222/.versions
Oct  3 14:29:32 gshtc1d.fpet.pokprv.stglabs.ibm.com noobaa[1411664]: [nsfs/1411664] ESC[36m   [L0]ESC[39m core.sdk.namespace_fs:: check_access: dir_path /ibm/gpfs1/warpio/testbucket2222/0LzNYz4U/ fs_context { uid: ESC[33m1001ESC[39m, gid: ESC[33m1001ESC[39m, new_buckets_path: ESC[32m'/ibm/gpfs1/warpio'ESC[39m, fs_backend: ESC[32m'GPFS'ESC[39m, backend: ESC[32m'GPFS'ESC[39m, warn_threshold_ms: ESC[33m100ESC[39m, report_fs_stats: ESC[36m[Function (anonymous)]ESC[39m }

### Expected behavior
1. warp should end without any errors.

### Steps to reproduce
1. ./warp list --versions=5 --host=192.168.17.15{0...3}:6443 --access-key=wkjHko0IpmjqWw3HedwK --secret-key=jB+SCzJ44+PfRxA/lqrUBDLhx3szxeItQWkjZ47y --insecure --tls --bucket=testbucket2222 --objects=100 --obj.size=40MiB --obj.randsize --disable-multipart --concurrent=1 --duration=1m

### More information - Screenshots / Logs / Other output

s3api_1924  get-bucket-versioning --bucket testbucket2222
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1071: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.17.149'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
{
    "Status": "Enabled"
}

./warp list --versions=5 --host=192.168.17.15{0...3}:6443 --access-key=wkjHko0IpmjqWw3HedwK --secret-key=jB+SCzJ44+PfRxA/lqrUBDLhx3szxeItQWkjZ47y --insecure --tls --bucket=testbucket2222 --objects=100 --obj.size=40MiB --obj.randsize --disable-multipart --concurrent=1 --duration=1m
warp: Benchmark data written to "warp-list-2024-10-03[142829]-LatD.csv.zst"                                                                               

----------------------------------------
Operation: PUT. Concurrency: 1
* Average: 115.13 MiB/s, 15.36 obj/s

Throughput by host:
 * https://192.168.17.150:6443: Avg: 28.59 MiB/s, 3.94 obj/s
 * https://192.168.17.151:6443: Avg: 29.90 MiB/s, 3.94 obj/s
 * https://192.168.17.152:6443: Avg: 23.48 MiB/s, 3.93 obj/s
 * https://192.168.17.153:6443: Avg: 35.46 MiB/s, 3.94 obj/s

Throughput, split into 32 x 1s:
 * Fastest: 181.1MiB/s, 17.40 obj/s
 * 50% Median: 116.3MiB/s, 6.47 obj/s
 * Slowest: 63.0MiB/s, 11.78 obj/s

----------------------------------------
Operation: LIST. Concurrency: 0
Errors: 2214
Skipping LIST too few samples. Longer benchmark run required for reliable results.

Created 500 files (4 Versions per object) during warp execution

**Comment by romayalon** [comment] 2024-10-06 07:04
@shirady can you please take a look?

**Comment by shirady** [comment] 2024-10-06 09:40
Hi @muenchp1,
To understand the issue I need more details you can attach them here:
1. In the title you wrote that the warp list is failing, what exactly is the error that you see?
2. Could you please attach the logs to the issue?
I see that you attached partial logs with the message:
> core.sdk.namespace_fs:: NamespaceFS: Version dir not found, /ibm/gpfs1/warpio/testbucket2222/.versions

It might be that there is a phase where we don't have the `/.versions` directory and it might not be the root cause for the issue.
3. I can see that you used AWS CLI to get the bucket versioning, and it is Enabled, did you try to manually run the needed commands to test the basic warp list (using `ListObjectVersions`)? If you can share the output and the logs.

I would add that I tried to run it locally on my POSIX machine (with lower numbers) and it worked without any issue: `./warp list --versions=5 --host=localhost:6443 --access-key=<access-keys> --secret-key=<secret-keys> --insecure --tls --bucket=<bucket-name> --objects=2 --obj.size=4MiB --obj.randsize --disable-multipart --concurrent=1 --duration=1m` (`--objects` 2 instead of 100 and  `--obj.size` 4MiB instead of 40MiB).

**Comment by muenchp1** [comment] 2024-10-07 16:28
[noobaa.log](https://github.com/user-attachments/files/17281747/noobaa.log)

**Comment by shirady** [comment] 2024-10-08 05:13
Hi @muenchp1,
I will edit my previous comment so it will be clear that one of the changes on my run is also using one endpoint instead of a couple.

So, if I understand you correctly:
1. list versions on one host - works as expected.
2. list (no versions) on multiple hosts - works as expected.
3. list versions on multiple hosts - generates errors (in the output of warp we can see "Operation: LIST ... Errors: 14217"

I see you attached the logs, I will look at them, thank you.

**Comment by muenchp1** [comment] 2024-10-08 09:50
Created a new bucket:
(10:39:15) svtc5a:~ # s3_warpio mb s3://warpiobucket
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1071: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.17.149'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
make_bucket: warpiobucket
(10:39:36) svtc5a:~ #
(10:45:57) svtc5a:~ # s3api_warpio get-bucket-versioning --bucket warpiobucket
/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py:1071: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.17.149'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
{
    "Status": "Enabled"
}

Waiting for more than 60s and started warp list versioning

(10:48:34) gshtc1a:/scratch/muenchp/warp # ./warp list --versions=5 --host=192.168.17.15{0...3}:6443 --access-key=dUePYr9Hii41X1Tjrd5g --secret-key=UVcPrMHKmVIE3CXqy6oDwjmDjyDBmKnf7tNKFHnJ --insecure --tls --bucket=warpiobucket --objects=2 --obj.size=4MiB --obj.randsize --disable-multipart --concurrent=1 --duration=1m
warp: Benchmark data written to "warp-list-2024-10-08[104841]-jYuN.csv.zst"                                                                               

----------------------------------------
Operation: PUT. Concurrency: 0
Skipping PUT too few samples. Longer benchmark run required for reliable results.

----------------------------------------
Operation: LIST
* Average: 2426.74 obj/s

Throughput by host:
 * https://192.168.17.150:6443: Avg: 607.28 obj/s
 * https://192.168.17.151:6443: Avg: 607.40 obj/s
 * https://192.168.17.152:6443: Avg: 607.29 obj/s
 * https://192.168.17.153:6443: Avg: 607.35 obj/s

Throughput, split into 59 x 1s:
 * Fastest: 3096.60 obj/s
 * 50% Median: 2514.63 obj/s
 * Slowest: 1440.74 obj/s
warp: Cleanup Done.

Execution successful.

**Comment by shirady** [comment] 2024-10-08 10:36
Hi,
According to the last run in the [comment above](https://github.com/noobaa/noobaa-core/issues/8429#issuecomment-2399386182) with the steps:
1. Creating the bucket
2. Setting the versioning to Enabled
3. Waiting for 1 minute (so the configuration will be saved and when using `bucket_namespace_cache` it will expire until we execute the next operations: put-object and list-object-versions there is no configuration change).
4. Running the same warp command: `/warp list --versions=5 --host=192.168.17.15{0...3}:6443 --access-key=<access-key> --secret-key=<secret-key> --insecure --tls --bucket=warpiobucket --objects=2 --obj.size=4MiB --obj.randsize --disable-multipart --concurrent=1 --duration=1m`
It worked as expected.

Regarding running without delay, I can say that we have an open issue related to the `bucket_namespace_cache` #8391.
As mentioned in the [previous comment](https://github.com/noobaa/noobaa-core/issues/8429#issuecomment-2399124439) "Version dir not found" logs were no indicating an issue by themselves.
Since we don’t have an issue with the list object versions on multiple hosts I'm closing this issue.

**Closed by shirady** 2024-10-08 10:36 UTC
Labels: NS-FS

**Comment by shirady** [comment] 2024-11-21 09:10
Hi @muenchp1 ,
I want to let you know that we merged a code change in PR https://github.com/noobaa/noobaa-core/pull/8527.
Could you please test it again on the master branch? (on RPM that includes the code changes)

In case it didn't solve the issue, please attach all the details:
- RPM version and date
- Partial code snippet (to see that it is with the code change)
- The steps that you did
- Logs with high debug level

I'm adding a label for validation, please update in a comment the status.
