### ISSUE TITLE
not able to read or put objects in the bucket created and not able see my bucket path in my endpoint path

### ISSUE THREAD

**Issue by radhalankisetti** [noobaa/noobaa-core#6557] opened 2021-06-08 02:05 UTC
### Environment info
- NooBaa Version: master-20210607
- Platform: OpenShift 4.7.1

### Actual behavior
1. namespacestore and bucket got created but not able to see my bucket path or folder after bucket got created in my pvc or endpoint
2. not able to list or put objects in the bucket using s3 

### Expected behavior
1.to create an nsfs bucket and put objects in it
### Steps to reproduce
 noobaa namespacestore create nsfs d2 --pvc-name='gpfs-vol' --fs-backend='GPFS'
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Created: NamespaceStore "d2"
INFO[0001]
INFO[0001] NOTE:
INFO[0001]   - This command has finished applying changes to the cluster.
INFO[0001]   - From now on, it only loops and reads the status, to monitor the operator work.
INFO[0001]   - You may Ctrl-C at any time to stop the loop and watch it manually.
INFO[0001]
INFO[0001] NamespaceStore Wait Ready:
INFO[0001] ⏳ NamespaceStore "d2" Phase is "": waiting...
INFO[0004] ✅ NamespaceStore "d2" Phase is Ready
INFO[0004]
INFO[0004]
INFO[0004] ✅ Exists: NamespaceStore "d2"
INFO[0004] ✅ NamespaceStore "d2" Phase is Ready

# NamespaceStore spec:
nsfs:
  fsBackend: GPFS
  pvcName: gpfs-vol
  subPath: ""
type: nsfs

oc rsh noobaa-endpoint-67b6748fdd-2gm7w
sh-4.4# ls
bin   dev  home               lib    log         media  noobaa_init_files  opt   root  sbin  srv  tmp  var
data  etc  install_nodejs.sh  lib64  lost+found  mnt    nsfs               proc  run   src   sys  usr

df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         250G   22G  229G   9% /
tmpfs            64M     0   64M   0% /dev
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
shm              64M     0   64M   0% /dev/shm
tmpfs           7.7G   55M  7.6G   1% /etc/hostname
tmpfs           7.7G  8.0K  7.7G   1% /etc/mgmt-secret
tmpfs           7.7G  8.0K  7.7G   1% /etc/s3-secret
d2               50G     0   50G   0% /nsfs/d2
/dev/vda4       250G   22G  229G   9% /etc/hosts
tmpfs           7.7G   28K  7.7G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs           7.7G     0  7.7G   0% /proc/acpi
tmpfs           7.7G     0  7.7G   0% /proc/scsi
tmpfs           7.7G     0  7.7G   0% /sys/firmware

 noobaa namespacestore list nsfs
NAME   TYPE   TARGET-BUCKET   PHASE   AGE
d2     nsfs                   Ready   2m45s

noobaa api account_api create_account '{
>    "email": "xxx@noobaa.io",
>    "name" : "xxxxxx",
>    "has_login": false,
>    "s3_access": true,
>    "allowed_buckets": { "full_permission": true },
>    "default_resource": "d2",
>    "nsfs_account_config": {
>      "uid": 2000,
>      "gid": 2000,
>      "new_buckets_path": "/"
>    }
>  }'
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: account.create_account() Request: map[allowed_buckets:map[full_permission:true] default_resource:d2 email:dg@noobaa.io has_login:false name:deepak nsfs_account_config:map[gid:2000 new_buckets_path:/ uid:2000] s3_access:true]
WARN[0001] RPC: GetConnection creating connection to wss://localhost:33825/rpc/ 0xc000d18320
INFO[0001] RPC: Connecting websocket (0xc000d18320) &{RPC:0xc00028e870 Address:wss://localhost:33825/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc000d18320) &{RPC:0xc00028e870 Address:wss://localhost:33825/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] ✅ RPC: account.create_account() Response OK: took 45.8ms
access_keys:
- access_key: xxxxxx
  secret_key: xxxxxx
token: xxxxx

noobaa api bucket_api create_bucket '{
  "name": "d2-sample-bucket",
  "namespace":{
    "write_resource": { "resource": "d2", "path": "sample/" },
    "read_resources": [ { "resource": "d2", "path": "sample/" }]
  }
}'
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: bucket.create_bucket() Request: map[name:d2-sample-bucket namespace:map[read_resources:[map[path:sample/ resource:d2]] write_resource:map[path:sample/ resource:d2]]]
WARN[0001] RPC: GetConnection creating connection to wss://localhost:38733/rpc/ 0xc000c1aaf0
INFO[0001] RPC: Connecting websocket (0xc000c1aaf0) &{RPC:0xc0003d0870 Address:wss://localhost:38733/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc000c1aaf0) &{RPC:0xc0003d0870 Address:wss://localhost:38733/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] ✅ RPC: bucket.create_bucket() Response OK: took 54.1ms
bucket_type: NAMESPACE
data:
  available_for_upload: 0
  free: 0
  last_update: 1623117108885
  size: 0
  size_reduced: 0
host_tolerance: 0
mode: OPTIMAL
name: d2-sample-bucket
namespace:
  read_resources:
  - path: sample/
    resource: d2
  should_create_underlying_storage: false
  write_resource:
    path: sample/
    resource: d2
node_tolerance: 0
num_objects:
  last_update: 1623117030000
  value: 0
owner_account:
  email: operator@noobaa.io
  id: 60bec4c01dcf750022091789
stats_by_type: []
storage:
  last_update: 1623117108885
  values:
    free: 0
    total: 0
    used: 0
    used_other: 0
tag: ""
tiering:
  data: {}
  mode: NO_RESOURCES_INTERNAL
  name: d2-sample-bucket#kpne36by
  tiers:
  - disabled: false
    mode: OPTIMAL
    order: 0
    spillover: false
    tier: d2-sample-bucket#kpne36by
triggers: []
usage_by_pool:
  last_update: 1623117030000
  pools: []
versioning: DISABLED
writable: false

after this I am not able to see the bucket path I created in endpoint or pvc
oc rsh noobaa-endpoint-67b6748fdd-2gm7w

sh-4.4# ls
bin   etc                lib    lost+found  noobaa_init_files  proc  sbin  sys  var
data  home               lib64  media       nsfs               root  src   tmp
dev   install_nodejs.sh  log    mnt         opt                run   srv   usr
sh-4.4# cd nsfs
sh-4.4# ls
d2
sh-4.4# cd d2
sh-4.4# ls
sh-4.4# 

I should see my sample/ folder right??

I cannot see anything in my pv also
sh-4.4# cd pvc-841db0bf-535f-484c-a014-ccf3212ddbff/
sh-4.4# ls  
pvc-841db0bf-535f-484c-a014-ccf3212ddbff-data
sh-4.4# cd pvc-841db0bf-535f-484c-a014-ccf3212ddbff-data/
sh-4.4# ls

when try to list or upload an object using s3 credentials I get bucket not found error

but I am able see my bucket in noobaa management gui 
![image](https://user-images.githubusercontent.com/85148371/121111127-fa18a480-c82b-11eb-81d6-7884ee757b6c.png)

please let me know what went wrong

**Comment by jackyalbo** [comment] 2021-06-08 13:41
Can you please add info on what you are seeing using s3 client. Show the buckets you are seeing and what errors you are getting on running the s3 commands. I would guess it's a permissions issue - but can't know for sure. The bucket is being created lazily so without you starting to upload files to it it won't be created.  Also please provide the endpoint logs, or noobaa diagnostics. Thanks

**Comment by radhalankisetti** [comment] 2021-06-09 06:46
@jackyalbo  my code to upload a file to the bucket i create using noobaa api
const express = require('express');
const fs = require('fs')
const app = express();
const AWS = require('aws-sdk');
const https = require('https');
 
const ACCESS_KEY_ID = "XXXXXXXXXXXXXXXXXX"
const SECRET_ACCESS_KEY = "XXXXXXXXXXXXXXXXXX"
AWS.config.update({
  httpOptions: {
    agent: new https.Agent({
      rejectUnauthorized: false
    })
  },
  s3ForcePathStyle:true
});
const s3 = new AWS.S3({
    accessKeyId: ACCESS_KEY_ID,
    secretAccessKey: SECRET_ACCESS_KEY,
    endpoint: new AWS.Endpoint("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
})

const fileName = 'hello_world.txt';

const uploadFile = (fileName) => {
    // Read content from the file
    const fileContent = fs.readFileSync(fileName);

    // Setting up S3 upload parameters
    const params = {
        Bucket: "d2-sample-bucket",
        Key: 'hello_world.txt', // File name you want to save as in S3
        Body: fileContent
    };

    // Uploading files to the bucket
    s3.upload(params, function(err, data) {
        if (err) {
            throw err;
        }
        console.log(`File uploaded successfully. ${data.Location}`);
    });
};
uploadFile(fileName);
error I am getting

Error [InternalError]: We encountered an internal error. Please try again.
    at Request.extractError (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\services\s3.js:718:35)      
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:78:10)       
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'InternalError',
  region: null,
  time: 2021-06-09T06:22:55.661Z,
  requestId: 'kpp356s2-72pa6k-w54',
  extendedRequestId: 'kpp356s2-72pa6k-w54',
  cfId: undefined,
  statusCode: 500,
  retryable: true
} InternalError: We encountered an internal error. Please try again.
    at Request.extractError (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\services\s3.js:718:35)      
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:106:    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:78:10)       
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
PS C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs> node app.js
C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

Error [InternalError]: We encountered an internal error. Please try again.
    at Request.extractError (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\services\s3.js:718:35)      
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:78:10)       
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'InternalError',
  region: null,
  time: 2021-06-09T06:24:50.461Z,
  requestId: 'kpp37ncz-3s8srr-o2m',
  extendedRequestId: 'kpp37ncz-3s8srr-o2m',
  cfId: undefined,
  statusCode: 500,
  retryable: true
}


Similarly, i am unable to list bucket also getting this error

s3.listBuckets(function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});



Error [InternalError]: We encountered an internal error. Please try again.
    at Request.extractError (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\services\s3.js:718:35)      
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:78:10)       
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'InternalError',
  region: null,
  time: 2021-06-09T06:30:33.043Z,
  requestId: 'kpp3ezpa-di0dqj-5f3',
  extendedRequestId: 'kpp3ezpa-di0dqj-5f3',
  cfId: undefined,
  statusCode: 500,
  retryable: true
} InternalError: We encountered an internal error. Please try again.
    at Request.extractError (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\services\s3.js:718:35)      
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:78:10)       
    at Request.emit (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\LANKISETTISAIVAMSEEK\Documents\minio-nodejs\node_modules\aws-sdk\lib\sequential_executor.js:116:18)


but when I create a bucket using s3 create bucket instead of noobaa API create bucket I am able to get the folder created in my endpoint and I am able to upload objects into the bucket and list them.

another thing that i noticed is if I created a bucket using s3 and delete it from noobaa management console the bucket folder is not getting deleted but if i delete using s3 it getting deleted completely.

noobaa diagnose is attached below

[noobaa_diagnostics_1623220997.tar.zip](https://github.com/noobaa/noobaa-core/files/6621605/noobaa_diagnostics_1623220997.tar.zip)

**Comment by nimrod-becker** [comment] 2021-06-10 08:49
Correct me if I'm wrong, but we have 2 paths for creating an NS FS bucket

- Export - this is creating a bucket on top of an existing directory. This will NOT create a new directory in the FS. This is done using the API/CLI

- Ne bucket via S3 - this will create a bucket AND will create the directory on the FS.

This is the design we have, so sounds like works as expected?

@jeniawhite @romayalon @jackyalbo @akmithal to keep me honest

**Comment by romayalon** [comment] 2021-06-13 07:09
@nimrod-becker you are correct.

**Comment by vamseekrishna25** [comment] 2021-06-15 05:29
any solution for the above issue I am still not able to list buckets but only able to list objects in the bucket and upload object using s3 credentials

**Comment by romayalon** [comment] 2021-06-15 08:58
@vamseekrishna25 
as Nimrod wrote, noobaa will create and delete the underlying directory only if you will use s3, if you are willing to export the buckets by using noobaa API, you will need to handle creation of the directory (before create_bucket op) and deletion of the directory (after delete_bucket op)  by yourself.
this is done by design so you can choose one of the 2 methods ( S3 / NooBaa API).

**Comment by nimrod-becker** [comment] 2021-06-15 09:03
@vamseekrishna25 I think this is a "works as designed" flow

**Comment by vamseekrishna25** [comment] 2021-06-16 06:21
Okay Thank You I understood the flow now

**Comment by nimrod-becker** [comment] 2021-06-16 06:24
Closing the issue

**Closed by nimrod-becker** 2021-06-16 06:24 UTC
Labels: NS-FS
