### ISSUE TITLE
Cli command not available for creating the Access-key and secret-key  (Used for creating the account for nsfs service)

### ISSUE THREAD

**Issue by ramya-c3** [noobaa/noobaa-core#7537] opened 2023-10-19 10:17 UTC
**Environment info**

NooBaa Version: 5.15
Platform: Linux

**Actual behavior**

Currently **nsfs accounts creation** is **mandating** the access-key and secret-key but there is no cli provided for generating the access-key and secret-key below is the cli command for reference.

node src/cmd/manage_nsfs account add --config_root ../standalon/config_root --name noobaa --email noobaa@gmail.com --new_buckets_path ../standalon/nsfs_root/ --access_key abc --secret_key abc
 

**Expected behavior**

In openshift it is observed that account creation is accepting only uid,gid,bucket path but for the standalone nsfs it is expecting the access-key and secret-key. Below is the reference of the account create api for ocp

		Api: "account_api", Method: "create_account",
                       NsfsAccountConfig: nsfsAccountConfig{
				Uid:            uid,
				Gid:            gid,
				NewBucketsPath: newBucketsPath,
				NSFSOnly:       true,

**So the expectation here** is by using the uid and gid we should be able to generate the access-key and secret-key post that we should be able to update the account with this generated keys.

**Steps to reproduce**
NA

**Comment by PravinRanjan10** [comment] 2023-10-25 06:57
@guymguym @romayalon . Please take a look of this issue. Thank you.

**Comment by romayalon** [comment] 2023-11-28 11:21
duplicate of https://github.com/noobaa/noobaa-core/issues/7580, closing

**Closed by romayalon** 2023-11-28 11:21 UTC
Labels: Type:Enhancement
