### ISSUE TITLE
Bucket status give 'INVALID_SCHEMA_REPLY' for all buckets after deleting the account. 

### ISSUE THREAD

**Issue by schawla5** [noobaa/noobaa-core#6783] opened 2021-10-26 06:38 UTC
### Environment info
[root@api.transcept.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:5.9.0-20210722
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0

Openshift Client Version: 4.8.2
Openshift Server Version: 4.8.2
Kubernetes Version: v1.21.1+051ac4f

### Actual behavior
1. Create a account and use this account key to create buckets.
2. Upload the data in the bucket.
3. .Delete the account then try to do bucket status of any bucket then it gives INVALID_SCHEMA_REPLY

### Expected behavior
1. INVALID_SCHEMA_REPLY should not be appear

### Steps to reproduce
1. Create a account
```
 noobaa api account_api create_account '{
   "email": "ketan@noobaa.io",
   "name" : "ketan",
   "has_login": false,
   "s3_access": true,
   "allowed_buckets": { "full_permission": true },
   "default_resource": "noobaa-s3res-4080029599",
   "nsfs_account_config": {
     "uid": 1003,
     "gid": 1003,
     "new_buckets_path": "test2",
     "nsfs_only": true
   }
 }'
```
2. Use Access key to create the bucket.
```
s3 mb s3://newbucket
```
3. Upload the data 
```
s3 cp /bin/date s3://newbucket
```
4. Delete the account
```
 noobaa api account_api delete_account '{"email":"ketan@ibm.com"}'
```
5. Get the bucket status it gives error.
```
noobaa bucket status newbucket
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: bucket.read_bucket() Request: {Name:newbucket}
WARN[0001] RPC: GetConnection creating connection to wss://localhost:46433/rpc/ 0xc0001185a0
INFO[0001] RPC: Connecting websocket (0xc0001185a0) &{RPC:0xc00034b090 Address:wss://localhost:46433/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc0001185a0) &{RPC:0xc00034b090 Address:wss://localhost:46433/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
ERRO[0001] ⚠️  RPC: bucket.read_bucket() Response Error: Code=INVALID_SCHEMA_REPLY Message=INVALID_SCHEMA_REPLY SERVER bucket_api#/methods/read_bucket
FATA[0001] INVALID_SCHEMA_REPLY SERVER bucket_api#/methods/read_bucket
```

**Comment by rkomandu** [comment] 2021-10-30 00:06
Installed the 212.ci d/s ODF build and verified that when the user account is trying to delete where it has a bucket, the operation is giving an error message as expected 

```

Created Account s3user81 

- access_key: BmqzD6IhitAjVfVsuMEu
  secret_key: a+CKwMoKC3o2X8gsGjrJX1xvpzbMV9cZTLZLQ7Bs


[root@rkomandu-app-node1 ~]# s3u81 mb s3://newbucket-29oct-s81user
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-openshift-storage.apps.rkomandu-ocp.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
make_bucket: newbucket-29oct-s81user


[root@api.rkomandu-ocp.cp.fyre.ibm.com accounts]# noobaa api bucket_api list_buckets {}
I1029 06:51:20.625525  648689 request.go:668] Waited for 1.00002435s due to client-side throttling, not priority and fairness, request: GET:https://api.rkomandu-ocp.cp.fyre.ibm.com:6443/apis/operator.openshift.io/v1alpha1?timeout=32s
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: bucket.list_buckets() Request: map[]
WARN[0001] RPC: GetConnection creating connection to wss://localhost:41137/rpc/ 0xc0009d1c20
INFO[0001] RPC: Connecting websocket (0xc0009d1c20) &{RPC:0xc00056f860 Address:wss://localhost:41137/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc0009d1c20) &{RPC:0xc00056f860 Address:wss://localhost:41137/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] ✅ RPC: bucket.list_buckets() Response OK: took 1.0ms
buckets:
- name: newbucket-29oct-s81user
- name: first.bucket


noobaa api account_api delete_account '{"email":"s3user81@noobaa.io"} '
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: account.delete_account() Request: map[email:s3user81@noobaa.io]
WARN[0001] RPC: GetConnection creating connection to wss://localhost:46219/rpc/ 0xc000204690
INFO[0001] RPC: Connecting websocket (0xc000204690) &{RPC:0xc0001194f0 Address:wss://localhost:46219/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc000204690) &{RPC:0xc0001194f0 Address:wss://localhost:46219/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
ERRO[0001] ⚠️  RPC: account.delete_account() Response Error: Code=UNAUTHORIZED Message=Cannot delete account that is owner of buckets
FATA[0001] ❌ Cannot delete account that is owner of buckets


noobaa api account_api read_account '{"email":"s3user81@noobaa.io"}'
INFO[0001] ✅ Exists: NooBaa "noobaa"
INFO[0001] ✅ Exists: Service "noobaa-mgmt"
INFO[0001] ✅ Exists: Secret "noobaa-operator"
INFO[0001] ✅ Exists: Secret "noobaa-admin"
INFO[0001] ✈️  RPC: account.read_account() Request: map[email:s3user81@noobaa.io]
WARN[0001] RPC: GetConnection creating connection to wss://localhost:40001/rpc/ 0xc0004d9e00
INFO[0001] RPC: Connecting websocket (0xc0004d9e00) &{RPC:0xc0004d9680 Address:wss://localhost:40001/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] RPC: Connected websocket (0xc0004d9e00) &{RPC:0xc0004d9680 Address:wss://localhost:40001/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s}
INFO[0001] ✅ RPC: account.read_account() Response OK: took 1.0ms
access_keys:
- access_key: BmqzD6IhitAjVfVsuMEu
  secret_key: a+CKwMoKC3o2X8gsGjrJX1xvpzbMV9cZTLZLQ7Bs
allowed_buckets:
  full_permission: true
can_create_buckets: true
default_resource: noobaa-s3res-4080029599
email: s3user81@noobaa.io
external_connections:
  connections: []
  count: 0
has_login: false
has_s3_access: true
name: s3user81
nsfs_account_config:
  gid: 6000
  new_buckets_path: /
  nsfs_only: true
  uid: 6001
preferences:
  ui_theme: LIGHT
systems:
- name: noobaa
  roles:
  - admin

```

**Comment by rkomandu** [comment] 2021-10-30 00:09
@liranmauda 
Could you elaborate further on your above comment 
>> "also, we will fix the get info and return undefined where there is no account info on the bucket (Just to be on the safe side)." 

Anything that needs to be tested based on above comment ? Let us know

**Comment by liranmauda** [comment] 2021-10-31 07:34
@rkomandu 

> Anything that needs to be tested based on above comment ? Let us know

This fix is also for systems that for some reason deleted their account when there was a bucket (This issue is there for some time now).
So for a system that managed to delete the account, even when it had a bucket, we also fix that, and now you can list the bucket. 

In order to test that we need to reproduce the issue (with a version the allows deletion of an account that a bucket is attached to), then upgrade to this version and see that we can list the bucket.

**Comment by rkomandu** [comment] 2021-11-02 04:35
Thank you @liranmauda for your input. 

For HPO GA this is the first release, I don't think we should bother about the previously available bucket which was persisting when Account was deleted since the fix is now already there for the release. 

In Dev/Test systems we are uninstalling the  ODF and then installing with latest-stable-4.9.0 pointed in ocs-registry the above test doesn't need to get that importance IMO. 

Will close this if you don't have any further comments.

**Comment by liranmauda** [comment] 2021-11-02 08:08
@rkomandu 
Sure, as I don't have any further comments regarding this, we can close it 🙂

**Comment by rkomandu** [comment] 2021-11-02 09:34
Thank you for the fix. From noobaa side it works.

**Closed** 2021-11-02 10:37 UTC
Labels: NS-FS, Request Validation
