### ISSUE TITLE
Delete Object Version ID Should Be Allowed Only by Bucket Owner

### ISSUE THREAD

**Issue by shirady** [noobaa/noobaa-core#7370] opened 2023-07-02 09:11 UTC
### Environment info
- NooBaa Version: current master (5.14)
- Platform: Rancher Desktop 1.19.0 (VM and cluster)

### Actual behavior
1. When versioning is suspended and a user request to delete an object version ID - we do not enforce the action to be limited only to bucket owner.

### Expected behavior
1. When versioning is suspended delete object with version id should be allowed only to the bucket owner.
From [AWS doc](https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectsfromVersioningSuspendedBuckets.html):

> Only the bucket owner can delete a specified object version.

### Steps to reproduce
1. none (base the steps on the comments below)

### More information - Screenshots / Logs / Other output
Comments:

- We need to check AWS behavior of delete object version id when bucket versioning is enabled / suspended and when the user is the bucket owner / not the bucket owner.

**Comment by shirady** [comment] 2024-07-22 06:24
@vh05 @romayalon 
I noticed that the versioning in NSFS NC is going to be tested in the CI (in PR #8220), and I also noticed that we updated the bucket owner in a couple of PRs (for example #8221, #8062, #8211), and I thought that this gap might be relevant.

**Comment by naveenpaul1** [comment] 2024-10-04 07:02
@shirady @romayalon 
With latest changes I tested the issue and couldnt reproduce the issues.

1. created two accounts acc1 and acc2
2. created bucket bucket1 using acc1 and enabled versioning and put three versions if that object
3. suspend versioning in bucket1 ` --versioning-configuration Status=Suspended`
4. switch to acc2 and try to delete the bucket1 object version created using acc1, got Access Denied error
missing something here?

**Comment by shirady** [comment] 2024-10-06 05:41
Hi @naveenpaul1,
I opened this issue based on the AWS documentation.
To reproduce it in our system and AWS you need to give the other account bucket policy, for example, to allow all actions in S3:

In NooBaa:
```json
{
  "Version": "2012-10-17",
  "Statement": [ 
    { 
     "Effect": "Allow", 
     "Principal": { "AWS": [ "<account-name>" ] }, 
     "Action": [ "s3:*" ], 
     "Resource": [ "arn:aws:s3:::<bucket-name>/*", "arn:aws:s3:::<bucket-name>" ] 
    }
  ]
}
```

And now you can check if the other account can delete a specific version.
Anyway, as mentioned in the issue you would also need to test it in AWS in versioning Enabled and versioning Suspended modes.

**Comment by naveenpaul1** [comment] 2024-10-07 08:46
I tested it with a different IAM user with the same account, I can delete the version specific object, But @shirady suggested testing with a different account.

**Comment by naveenpaul1** [comment] 2024-10-14 10:22
@romayalon @shirady completed the version scenario with Sagi,

1. created bucket bucket1 using acc1 and enabled versioning and put three versions if that object
2. added account access to bucket1 using policy
```{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AllowAllS3ActionsInUserFolder",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::{acc2-arn}"
            },
            "Action": "s3:*",
            "Resource": [
                "arn:aws:s3:::bucket1/*",
                "arn:aws:s3:::bucket1"
            ]
        }
    ]
}
```
3. try to delete the specific version using acc2, Able to delete the version
4. suspend versioning in bucket1  `--versioning-configuration Status=Suspended`
5. try to delete the specific version using acc2, Able to delete the version

We also need behavior similar to this?

**Comment by shirady** [comment] 2024-10-14 11:25
> @romayalon @shirady completed the version scenario with Sagi,
> 
> 1. created bucket bucket1 using acc1 and enabled versioning and put three versions if that object
> 2. added account access to bucket1 using policy
> 
> ```
>     "Version": "2012-10-17",
>     "Statement": [
>         {
>             "Sid": "AllowAllS3ActionsInUserFolder",
>             "Effect": "Allow",
>             "Principal": {
>                 "AWS": "arn:aws:iam::{acc2-arn}"
>             },
>             "Action": "s3:*",
>             "Resource": [
>                 "arn:aws:s3:::bucket1/*",
>                 "arn:aws:s3:::bucket1"
>             ]
>         }
>     ]
> }
> ```
> 
> 3. try to delete the specific version using acc2, Able to delete the version
> 4. suspend versioning in bucket1  `--versioning-configuration Status=Suspended`
> 5. try to delete the specific version using acc2, Able to delete the version
> 
> We also need behavior similar to this?

@naveenpaul1 so you could delete a specific version (using `--version-id`) on both bucket versioning Enabled and Suspended by another account that is not the bucket owner?
If that is so, I think we already have this behavior (the issue I opened was about adding the limitation).

If you can add what you reproduced with list-object-versions before and after delete a specific version so it will be easier to see it.

**Comment by naveenpaul1** [comment] 2024-10-14 12:01
@shirady @romayalon Please find the reproduced steps from Sagi
```
$ aws s3api list-object-versions --bucket naveen-noobaa-bucket --prefix tag-test1
{
    "Versions": [
        {
            "ETag": "\"8377851de1b13ec717edcbef57b1d17a\"",
            "Size": 40,
            "StorageClass": "STANDARD",
            "Key": "tag-test1",
            "VersionId": "DvlRuxgk3PFjMx.rP_Z9to6inmCqtFRs",
            "IsLatest": true,
            "LastModified": "2024-10-01T09:47:28+00:00",
            "Owner": {
                "DisplayName": "pnt-aws-root+255735097469",
                "ID": "2e055fd7dc2c9eb01fe8d089e32b84c4b9e8a66b85e370793b4c7259ea477902"
            }
        },
        {
            "ETag": "\"8377851de1b13ec717edcbef57b1d17a\"",
            "Size": 40,
            "StorageClass": "STANDARD",
            "Key": "tag-test1/",
            "VersionId": "null",
            "IsLatest": true,
            "LastModified": "2024-10-01T10:20:53+00:00",
            "Owner": {
                "DisplayName": "pnt-aws-root+255735097469",
                "ID": "2e055fd7dc2c9eb01fe8d089e32b84c4b9e8a66b85e370793b4c7259ea477902"
            }
        },
        {
            "ETag": "\"8377851de1b13ec717edcbef57b1d17a\"",
            "Size": 40,
            "StorageClass": "STANDARD",
            "Key": "tag-test1/",
            "VersionId": "IXyUdRJDAc9ur4wdHUppUEwvvchUjrXN",
            "IsLatest": false,
            "LastModified": "2024-10-01T09:47:52+00:00",
            "Owner": {
                "DisplayName": "pnt-aws-root+255735097469",
                "ID": "2e055fd7dc2c9eb01fe8d089e32b84c4b9e8a66b85e370793b4c7259ea477902"
            }
        }
    ],
    "RequestCharged": null
}

$ aws s3api delete-object --bucket naveen-noobaa-bucket --key tag-test1 --version-id DvlRuxgk3PFjMx.rP_Z9to6inmCqtFRs
{
    "VersionId": "DvlRuxgk3PFjMx.rP_Z9to6inmCqtFRs"
}

$ aws s3api list-object-versions --bucket naveen-noobaa-bucket --prefix tag-test1
{
    "Versions": [
        {
            "ETag": "\"bc068f05f1b84f5a1ad4cdd10a185f1d\"",
            "Size": 28,
            "StorageClass": "STANDARD",
            "Key": "tag-test1/",
            "VersionId": "null",
            "IsLatest": true,
            "LastModified": "2024-10-14T09:50:09+00:00",
            "Owner": {
                "DisplayName": "pnt-aws-root+255735097469",
                "ID": "2e055fd7dc2c9eb01fe8d089e32b84c4b9e8a66b85e370793b4c7259ea477902"
            }
        },
        {
            "ETag": "\"8377851de1b13ec717edcbef57b1d17a\"",
            "Size": 40,
            "StorageClass": "STANDARD",
            "Key": "tag-test1/",
            "VersionId": "IXyUdRJDAc9ur4wdHUppUEwvvchUjrXN",
            "IsLatest": false,
            "LastModified": "2024-10-01T09:47:52+00:00",
            "Owner": {
                "DisplayName": "pnt-aws-root+255735097469",
                "ID": "2e055fd7dc2c9eb01fe8d089e32b84c4b9e8a66b85e370793b4c7259ea477902"
            }
        }
    ],
    "RequestCharged": null
}
```
```

**Comment by shirady** [comment] 2024-10-27 12:37
@naveenpaul1 It seems like it was not reproduced in AWS, although I would have expected this according to their documentation.
I think you can close this issue and we might need to open an issue in AWS to understand the behavior as described in their documentation.

cc: @romayalon

**Comment by romayalon** [comment] 2024-10-27 17:25
Closing per the last comment

**Closed by romayalon** 2024-10-27 17:25 UTC
