### ISSUE TITLE
Account creation give error while noobaa-db pod running node is power down

### ISSUE THREAD

**Issue by nishant16** [noobaa/noobaa-core#7166] opened 2022-06-08 06:35 UTC
### Environment info
- ODF 4.9 and 4.10
- Platform: OCP 4.9.31

### Actual behavior
1. account create fails with in-appropriate message when noobaa-db pod is in Init state
```
error: "this.begin() must be called before sending queries on this transaction' 
```
### Expected behavior
1.  account create fails should give Appropriate message when noobaa-db pod is in Init state. like:
```
Cannot connect to noobaa-db pod
```

**Comment by shirady** [comment] 2023-01-17 10:39
The steps to reproduce this issue with RPC calls (without the operator as I did before):

**Prerequisite:**
Based on the instructions [here](https://gist.github.com/dannyzaken/c85f0006e5d6582c8d8666cafce6ab76) - the steps of ‘Build images’ and ‘Deploy noobaa’.

**Steps:**
1. use the watch to see all 5 pods running (and observe the changes that we will do).
`watch kubectl get pods`
2. kill `noobaa-db-pg` pod (by changing the number of replicas to 0)
`kubectl edit statefulsets.apps noobaa-db-pg `
under spec replicas change from 1 to 0 and save.
3. Wait until the `noobaa-db-pg` is terminated.
4. create a new account (based on [these instructions](https://github.com/noobaa/noobaa-core/wiki/NSFS-on-Kubernetes), Create account):
```
nb api account_api create_account '{
  "email": "jenia2@noobaa.io",
  "name": "jenia2",
  "has_login": false,
  "s3_access": true,
  "default_resource": "noobaa-default-backing-store"
}'
```
_Note: I implemented it without the NSFS part and bucket_claim_owner field._

**Actual behavior:**
![Screenshot 2023-01-17 at 12 35 50](https://user-images.githubusercontent.com/57721533/212876927-157c2e4e-a114-4b81-b124-f4ae1402b6fe.png)

**Expected behavior:**
As suggested by @rkomandu 

> Cannot connect to noobaa-db pod

**Comment by shirady** [comment] 2023-01-25 10:49
HI @rkomandu,
The new message is
![image](https://user-images.githubusercontent.com/57721533/214543638-1d1543c2-2333-4f2b-ba76-4dcd25576b4e.png)

We changed the label, please close this issue after verifying.

**Comment by rkomandu** [comment] 2023-01-30 07:01
@shirady , Is this checked in to ODF 5.13 ? Are there plans to get into ODF 5.12 . @romayalon , please guide on these images if required

**Comment by rkomandu** [comment] 2023-01-30 07:03
Thank you @shirady for your continuous focus on this defect.

**Comment by rkomandu** [comment] 2023-02-06 06:18
@nimrod-becker , is this going to be in ODF 4.12.X ? please let us know

**Comment by nimrod-becker** [comment] 2023-02-06 08:30
Not in the coming ones, maybe later on

**Comment by nimrod-becker** [comment] 2024-01-21 08:01
@rkomandu Is this one fixed? Can we close?

**Comment by rkomandu** [comment] 2024-02-23 17:32
today, observed in the below OCP 4.14.x with ODF 4.14.4, account create via CLI in the containerized environment is as follows 

```
[root@api.rkomandu-airgap.cp.fyre.ibm.com ~]# mmdas account create s3user6700@fvt.ibm.com --uid 6700 --gid 6700 --newBucketsPath "/mnt/remote-sample/s3user6700-dir"
Error: Could not acquire client from DB connection pool
[root@api.rkomandu-airgap.cp.fyre.ibm.com ~]# oc get pods -n openshift-storage
NAME                                               READY   STATUS        RESTARTS       AGE
csi-addons-controller-manager-5576f6c68b-jxtpq     2/2     Running       0              4d5h
noobaa-core-0                                      1/1     Running       0              4d5h
noobaa-db-pg-0                                     0/1     Init:0/1      0              28m
noobaa-default-backing-store-noobaa-pod-ed7a9965   1/1     Running       0              4d5h
noobaa-endpoint-8468d857c5-9w42q                   1/1     Running       0              4d5h
noobaa-endpoint-8468d857c5-kxcq5                   1/1     Running       0              4d5h
noobaa-endpoint-8468d857c5-x22kp                   1/1     Running       0              4d5h
noobaa-endpoint-dfddbf459-gh9np                    0/1     Terminating   0              98s
noobaa-operator-74d44c9489-9lsrd                   2/2     Running       0              4d5h
ocs-metrics-exporter-64755696fb-rd4nx              1/1     Running       0              4d5h
ocs-operator-78c8fb9446-qvx7c                      1/1     Running       1 (4d5h ago)   4d5h
odf-console-76b8fd5784-nb8k9                       1/1     Running       0              4d5h
odf-operator-controller-manager-7bff4bf5cf-q8l9z   2/2     Running       0              4d5h
rook-ceph-operator-7b7b6b8d5c-mbxgm                1/1     Running       0              4d5h
[root@api.rkomandu-airgap.cp.fyre.ibm.com ~]# oc version
Client Version: 4.12.36
Kustomize Version: v4.5.7
Server Version: 4.14.11
Kubernetes Version: v1.27.10+28ed2d7


```

@shirady , looks like we can close this as per above response.. as the noobaa-db is in "Init state" when the account create is issued.

**Comment by shirady** [comment] 2024-02-26 06:01
closing per the last comment

**Closed by shirady** 2024-02-26 06:01 UTC
Labels: NS-FS, Request Validation
