### ISSUE TITLE
Upload failed with InvalidAccessKeyId and endpoint restarted

### ISSUE THREAD

**Issue by nehasharma5** [noobaa/noobaa-core#6633] opened 2021-07-01 10:57 UTC
Environment info
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210627
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#

[root@api.ns.cp.fyre.ibm.com ~]# oc version
Client Version: 4.7.13
Server Version: 4.7.13
Kubernetes Version: v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]#
[root@api.ns.cp.fyre.ibm.com ~]# oc get nodes
NAME STATUS ROLES AGE VERSION
master0.ns.cp.fyre.ibm.com Ready master,worker 4d1h v1.20.0+df9c838
master1.ns.cp.fyre.ibm.com Ready master,worker 4d1h v1.20.0+df9c838
master2.ns.cp.fyre.ibm.com Ready master,worker 4d1h v1.20.0+df9c838
[root@api.ns.cp.fyre.ibm.com ~]#

Actual behavior
Got error while copy of 98G file
html#ssl-warnings
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ns.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload failed: ./test_neha to s3://buck-2/test_neha An error occurred (InvalidAccessKeyId) when calling the UploadPart operation: The AWS access key Id you provided does not exist in our records.
2. The endpoint pod gets restarted

Steps to reproduce
Two endpoint should be patched
While copy operation is performed delete first noobaa-core-0, db , one of endpoint , operator pod

More information - Screenshots / Logs / Other output
[root@api.ns.cp.fyre.ibm.com ~]# oc get pod
NAME READY STATUS RESTARTS AGE
noobaa-core-0 1/1 Running 0 34m
noobaa-db-pg-0 1/1 Running 0 43m
noobaa-endpoint-84858cb98d-sbrs9 1/1 Running 0 34m
noobaa-endpoint-84858cb98d-xfl7s 1/1 Running 1 47m
noobaa-operator-57d449689c-56tc5 1/1 Running 0 32m
[root@api.ns.cp.fyre.ibm.com ~]#

[noobaa_diagnostics_1625135318.tar.gz](https://github.com/noobaa/noobaa-core/files/6747614/noobaa_diagnostics_1625135318.tar.gz)

**Comment by nimrod-becker** [comment] 2021-07-04 14:36
Logs do not include the error, can you please provide --previous or a repro with the correct logs?
@nehasharma5

**Comment by nehasharma5** [comment] 2021-07-05 07:03
Attaching previous ep logs
[ep_previous.log](https://github.com/noobaa/noobaa-core/files/6762362/ep_previous.log)

**Comment by jackyalbo** [comment] 2021-07-06 14:42
```While copy operation is performed delete first noobaa-core-0, db , one of endpoint , operator pod```
Hey @nehasharma5 . I need some info on this issue. first I need to understand what are you doing. Are you deleting all the pods while trying to copy an object using s3? What is the expected behavior? 
2nd looking on the logs I see the endpoint was restarting due to a already known issue of Files not being closed: 
```PANIC: FS::FileWrap::dtor: file not closed _path=/nsfs/fs1/buck-2/.noobaa-nsfs_60dab1e5f90f240027de0ef2/multipart-uploads/084b9e91-84ca-4cc7-982a-55bc0268abb6/part-1163 _fd=26  Success (0) ~FileWrap() at ../src/native/fs/fs_napi.cpp:616```
Nothing to do with invalid access key. also didn't find anything related to invalid access key in the logs

**Comment by nehasharma5** [comment] 2021-07-08 05:02
@jackyalbo yes , I am trying to delete all pods except 1 endpoint while trying to copy an object using s3 . I had 2 endpoint on my environment and got  invalid access key and my copy using s3 failed because of it.
My expectation is that S3 copy operation should have given a valid reason for failure as access key was valid

**Comment by jackyalbo** [comment] 2021-07-08 09:02
@nehasharma5 the issue is with the error type if I get you right?
does 
> An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 2): We encountered an internal error. Please try again.

Sounds better?

**Comment by nehasharma5** [comment] 2021-07-08 09:03
@jackyalbo its better

**Comment by jackyalbo** [comment] 2021-07-08 09:41
@nehasharma5 - As I said from looking in the recent logs you uploaded - the endpoint restarting doesn't have anything to do with the access key error -  I would guess it's a dup for #6624 - As it's multipart upload.
Once I will push the fix for the Internal Error I will close this one as duplicate.

**Comment by nehasharma5** [comment] 2021-07-20 07:01
Thanks @jackyalbo for resolving it.
Verified on noobaa version:
[root@api.ns.cp.fyre.ibm.com ~]# noobaa version
INFO[0000] CLI version: 5.9.0
INFO[0000] noobaa-image: noobaa/noobaa-core:master-20210719
INFO[0000] operator-image: noobaa/noobaa-operator:5.9.0
[root@api.ns.cp.fyre.ibm.com ~]#


IO failure gives:
s.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
upload failed: ./testfile1 to s3://buck-1/testfile1 An error occurred (InternalError) when calling the UploadPart operation (reached max retries: 2): We encountered an internal error. Please try again.
[root@fyreauto-x-app1 ~]#

**Closed** 2021-07-20 07:01 UTC
Labels: NS-FS, Request Validation
