### ISSUE TITLE
Endpoint crashed on 1 GB file upload

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6546] opened 2021-06-02 08:07 UTC
### Environment info
- NooBaa Version: master-20210531
- Platform: OCP 4.6.16

### Actual behavior
1. Endpoint pod crashed on doing upload operations on s3 bucket

### Expected behavior
1. Endpoint should not get crashed

### Steps to reproduce
1. Started upload operation of multiple files with sizes 977M using s3 cp command

Found o**nly 1 file got upload to bucket-1** and .noobaa_nsfs* size increased during this upload.

```
[root@hpo-node1 akshat]# s3u1 ls s3://bucket-1|grep small_chunk
urllib3/connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host 's3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
2021-06-01 23:23:01 1024000000 small_chunk_1
```

```
[root@hpo-node1 akshat]# du -sh small_chunk_*
977M    small_chunk_1
977M    small_chunk_10
977M    small_chunk_1_read
977M    small_chunk_1._read
977M    small_chunk_2
977M    small_chunk_3
977M    small_chunk_4
977M    small_chunk_5
977M    small_chunk_6
977M    small_chunk_7
977M    small_chunk_8
977M    small_chunk_9
```

Uploading this endpoint log and noobaa diagnose

### More information - Screenshots / Logs / Other output
```

Jun-2 6:45:03.736 [Endpoint/9]    [L0] core.sdk.object_sdk:: _load_bucket_namespace {
  _id: '60b672a8369502002280a0c3',
  name: SENSITIVE-f53e749d8f84e52b,
  active_triggers: [ [length]: 0 ],
  system_owner: SENSITIVE-9cf0fd89409efef8,
  bucket_owner: SENSITIVE-3d288e97f8a66631,
  bucket_info: { name: SENSITIVE-f53e749d8f84e52b, owner_account: { email: SENSITIVE-3d288e97f8a66631, id: '60b6713b369502002280a0bf' }, namespace: { write_resource: { resource: 'nsfs-nsr-1', path: '/bucket-1' }, read_resources: [ { resource: 'nsfs-nsr-1', path: '/bucket-1' }, [length]: 1 ], should_create_underlying_storage: true }, tag: '', num_objects: { value: 0, last_update: 1622569559747 }, writable: false, storage: { values: { used: 0, used_other: 0, total: 0, free: 0 }, last_update: 1622616205102 }, data: { size: 0, size_reduced: 0, free: 0, available_for_upload: 0, last_update: 1622616205102 }, usage_by_pool: { pools: [ [length]: 0 ], last_update: 1622569559747 }, stats_by_type: [ [length]: 0 ], mode: 'OPTIMAL', bucket_type: 'NAMESPACE', versioning: 'DISABLED', triggers: [ [length]: 0 ] },
  namespace: {
    write_resource: { resource: { fs_root_path: '/nsfs/parent', fs_backend: 'GPFS', id: '60b67114369502002280a0be', name: 'nsfs-nsr-1' }, path: '/bucket-1' },
    read_resources: [ { resource: { fs_root_path: '/nsfs/parent', fs_backend: 'GPFS', id: '60b67114369502002280a0be', name: 'nsfs-nsr-1' }, path: '/bucket-1' }, [length]: 1 ],
    should_create_underlying_storage: true
  }
}
Jun-2 6:45:03.737 [Endpoint/9]   [LOG] CONSOLE:: NamespaceFS: abort_object_upload /nsfs/parent/bucket-1/.noobaa-nsfs_60b672a8369502002280a0c3/multipart-uploads/38055c2a-c9f1-4b97-be41-1574e9a1046c
Jun-2 6:45:10.907 [Endpoint/9] [ERROR] core.endpoint.s3.s3_rest:: S3 ERROR <?xml version="1.0" encoding="UTF-8"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/bucket-1/small_chunk_10</Resource><RequestId>kpf3uueu-65vjp-qni</RequestId></Error> HEAD /bucket-1/small_chunk_10 {"accept-encoding":"identity","user-agent":"aws-cli/2.1.29 Python/3.8.8 Linux/4.18.0-240.22.1.el8_3.x86_64 exe/x86_64.rhel.8 prompt/off command/s3.cp","x-amz-date":"20210602T064510Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=p8S5WxzMgdcZfoKEpJdf/20210602/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=e51b7ce1acc22259803e2829258153666171d440a521215b2dc4abe5b33e87be","host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-host":"s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com","x-forwarded-port":"443","x-forwarded-proto":"https","forwarded":"for=10.17.66.193;host=s3-noobaa.apps.ocp-akshat-1.cp.fyre.ibm.com;proto=https","x-forwarded-for":"10.17.66.193"} Error: No such file or directory
Jun-2 6:49:48.578 [Endpoint/9]    [L0] core.endpoint.endpoint:: Sending endpoint report: { group_name: 'b1ee45f6-4c95-4e6b-80de-15ccf0782dec', hostname: 'noobaa-endpoint-6ddfcbc794-gjbcz' }
Jun-2 6:53:21.186 [Endpoint/9]  [WARN] core.util.mongo_client:: got close mongodb://noobaa-db-0.noobaa-db/nbcore
Jun-2 6:58:21.187 [Endpoint/9] [ERROR] core.util.mongo_client:: Connection closed for more  300000 , quitting




######################################################################
Wed Jun  2 06:58:21 UTC 2021 NooBaa: Process exited RIP (RC=1)
######################################################################

```

```
sh-4.4# e[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          13h
noobaa-db-0                                        1/1     Running       1          13h
noobaa-default-backing-store-noobaa-pod-fe588510   0/1     Terminating   0          14s
noobaa-endpoint-6ddfcbc794-gjbcz                   0/1     Error         0          13h
noobaa-operator-7c9c876b8c-zp475                   1/1     Running       0          13h

[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          14h
noobaa-db-0                                        1/1     Running       1          14h
noobaa-default-backing-store-noobaa-pod-fe588510   0/1     Terminating   0          3s
noobaa-endpoint-6ddfcbc794-gjbcz                   1/1     Running       1          13h
noobaa-operator-7c9c876b8c-zp475                   1/1     Running       0          14h
```

**Comment by akmithal** [comment] 2021-06-02 08:11
[noobaa_diagnostics_1622619273.tar.gz](https://github.com/noobaa/noobaa-core/files/6583078/noobaa_diagnostics_1622619273.tar.gz)

**Comment by akmithal** [comment] 2021-06-02 08:12
[endpoint_2june.zip](https://github.com/noobaa/noobaa-core/files/6583083/endpoint_2june.zip)

**Comment by jeniawhite** [comment] 2021-06-10 08:58
Seems like duplicate of https://github.com/noobaa/noobaa-core/issues/6565

**Comment by nimrod-becker** [comment] 2021-06-10 08:59
@akmithal ?

**Closed** 2021-06-22 16:18 UTC
Labels: NS-FS
