### ISSUE TITLE
NSFS | S3 | Versioning: HeadObject and PutObject do not return versionId when using multiple boto3 client instances

### ISSUE THREAD

**Issue by hseipp** [noobaa/noobaa-core#8332] opened 2024-09-06 15:05 UTC
### Environment info
- NooBaa Version: **5.15.4**
- Platform: **CentOS 8, deployed using [https://github.com/IBM/StorageScaleVagrant](https://github.com/IBM/StorageScaleVagrant)**

### Actual behavior
For an object that was uploaded to a version-enabled bucket, HeadObject does not deliver a VersionId entry. Identified with Ceph s3-test, method `test_bucket_list_return_data_versioning()`:
```
        bucket_name = get_new_bucket()
        check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
        key_names = ['bar', 'baz', 'foo']
        bucket_name = _create_objects(bucket_name=bucket_name,keys=key_names)
    
        client = get_client()
        data = {}
    
        for key_name in key_names:
            obj_response = client.head_object(Bucket=bucket_name, Key=key_name)
            data.update({
                key_name: {
                    'ETag': obj_response['ETag'],
                    'LastModified': obj_response['LastModified'],
                    'ContentLength': obj_response['ContentLength'],
>                   'VersionId': obj_response['VersionId']
                    }
                })
E           KeyError: 'VersionId'
```

Please note that I modified this test and removed `get_object_acl`:

```
$ git diff
diff --git a/s3tests_boto3/functional/test_s3.py b/s3tests_boto3/functional/test_s3.py
index 0f742df..aa6f3cb 100644
--- a/s3tests_boto3/functional/test_s3.py
+++ b/s3tests_boto3/functional/test_s3.py
@@ -1425,11 +1425,8 @@ def test_bucket_list_return_data_versioning():
 
     for key_name in key_names:
         obj_response = client.head_object(Bucket=bucket_name, Key=key_name)
-        acl_response = client.get_object_acl(Bucket=bucket_name, Key=key_name)
         data.update({
             key_name: {
-                'ID': acl_response['Owner']['ID'],
-                'DisplayName': acl_response['Owner']['DisplayName'],
                 'ETag': obj_response['ETag'],
                 'LastModified': obj_response['LastModified'],
                 'ContentLength': obj_response['ContentLength'],
@@ -1443,10 +1440,8 @@ def test_bucket_list_return_data_versioning():
     for obj in objs_list:
         key_name = obj['Key']
         key_data = data[key_name]
-        assert obj['Owner']['DisplayName'] == key_data['DisplayName']
         assert obj['ETag'] == key_data['ETag']
         assert obj['Size'] == key_data['ContentLength']
-        assert obj['Owner']['ID'] == key_data['ID']
         assert obj['VersionId'] == key_data['VersionId']
         _compare_dates(obj['LastModified'],key_data['LastModified'])
```

### Expected behavior

Test passes, versionId is returned. Noobaa is delivering consistent results, independent if one or more client sessions are used.

### Steps to reproduce

Run Ceph s3-tests with the following function:

```
S3TEST_CONF=s3tests.conf tox -- s3tests_boto3/functional/test_s3.py::test_bucket_list_return_data_versioning
```

### More information - Screenshots / Logs / Other output

Performing HeadObject on the files created during the tests after running the automated test is working.
Also the following script is working:

```
#!/usr/bin/python
import boto3

endpoint = 'https://localhost:6443'
bucket_name = "s3tests-head-object"

session = boto3.Session(profile_name='s3user1')
cos = session.client('s3', endpoint_url=endpoint, verify='/home/vagrant/aws-cert/tls.crt')
response = cos.create_bucket(Bucket=bucket_name)
response = cos.put_bucket_versioning(Bucket=bucket_name, VersioningConfiguration={'Status': 'Enabled'})
read_status = None
expected_string  = 'Enabled'
for i in range(5):
  try:
    response = cos.get_bucket_versioning(Bucket=bucket_name)
    read_status = response['Status']
  except KeyError:
    read_status = None
  if (expected_string == read_status):
    break
  time.sleep(1)
assert expected_string == read_status
data = 'content-1'
key = 'testobj'
response = cos.put_object(Bucket=bucket_name, Key=key, Body=data)
version_id = response['VersionId']
print('put_object: {}'.format(version_id))
response = cos.head_object(Bucket=bucket_name, Key=key)
version_id = response['VersionId']
print('head_object: {}'.format(version_id))
```

So the way Ceph s3-tests perform the operations is causing the issues. In this example, three different S3 sessions / `boto3.client`objects are used:

- one for `create_bucket`
- one for `put_bucket_versioning` and `get_bucket_versioning`
- one for `head_object` and `list_object_versions`

Here is a stand-alone Python script that re-creates this particular error:

```
import boto3

endpoint = 'https://localhost:6443'
bucket_name = "s3tests-2sessions"

session = boto3.Session(profile_name='s3user1')
cos = session.client('s3', endpoint_url=endpoint, verify='/home/vagrant/aws-cert/tls.crt')
response = cos.create_bucket(Bucket=bucket_name)
cos2 = session.client('s3', endpoint_url=endpoint, verify='/home/vagrant/aws-cert/tls.crt')
response = cos2.put_bucket_versioning(Bucket=bucket_name, VersioningConfiguration={'Status': 'Enabled'})
read_status = None
expected_string  = 'Enabled'
for i in range(5):
  try:
    response = cos2.get_bucket_versioning(Bucket=bucket_name)
    read_status = response['Status']
  except KeyError:
    read_status = None
  if (expected_string == read_status):
    break
  time.sleep(1)
assert expected_string == read_status
data = 'content-1'
response = cos.put_object(Bucket=bucket_name, Key='testobj', Body=data)
version_id = response['VersionId']
```

gets me:

```
$ python create-versioned-bucket-upload-object_2sessions.py 
Traceback (most recent call last):
  File "create-versioned-bucket-upload-object_2sessions.py", line 26, in <module>
    version_id = response['VersionId']
KeyError: 'VersionId'
```

Noobaa log with "all" log level:
[noobaa_20240906.log.gz](https://github.com/user-attachments/files/16909695/noobaa_20240906.log.gz)

**Comment by hseipp** [comment] 2024-09-06 15:42
The issue also occurs with Ceph s3-test `test_versioning_multi_object_delete_with_marker_create()` but there the `DeleteMarker` is not returned with the DeleteObjects response.

**Comment by nadavMiz** [comment] 2024-09-09 06:50
@hseipp it looks like the logs you provided contains messages from different test:
```
Sep 06 14:09:18 m1.example.com node[42541]: Sep-6 14:09:18.504 [nsfs/42617]    [L0] core.sdk.object_sdk:: request aborted /s3tests-aouwqe3huh6xh5fgkni6u-1/dstmultipart
```
.can you send times for when you started and finished running the test, or send logs for just this failed test.

also in my environment test_bucket_list_return_data_versioning fails because the tests creates the same bucket twice: first in get_new_bucket and second in _create_objects. can you check if maybe that what happens for you as well. if not can you post the error you got from the test.

**Comment by hseipp** [comment] 2024-09-09 08:52
@nadavMiz can you please try the above provided Python script if your re-create with s3-tests is not working as expected. Please note that I maintain an s3-tests fork in a private repo that contains patches to make it work with ces-s3 - added you to it.
Anyway, here is the patch to work around the bucket creation issue:

```
diff --git a/s3tests_boto3/functional/__init__.py b/s3tests_boto3/functional/__init__.py
index aeacdc2..3bdf2ec 100644
--- a/s3tests_boto3/functional/__init__.py
+++ b/s3tests_boto3/functional/__init__.py
@@ -597,12 +597,8 @@ def get_new_bucket_resource(name=None):
                         verify=config.default_ssl_verify)
     if name is None:
         name = get_new_bucket_name()
-    client = get_client()
     bucket = s3.Bucket(name)
-    try:
-        client.head_bucket(Bucket=name)
-    except:
-        bucket_location = bucket.create()
+    bucket_location = bucket.create()
     return bucket
 
 def get_new_bucket(client=None, name=None):
```

I did not capture the time stamps for the different test - the logs cover running s3-tests as well as the above Python script.

Here is a new test cycle with minimum logs - test started at 8:31:23 UTC:
[noobaa_20240909_1.log.gz](https://github.com/user-attachments/files/16928018/noobaa_20240909_1.log.gz)

**Comment by hseipp** [comment] 2024-09-12 09:13
In a debug session today, we first re-created the issue, then tried to step through it one-by-one:
Re-create:

```
$ python ../custom-tests/create-versioned-bucket-upload-object_2sessions.py 
Traceback (most recent call last):
  File "../custom-tests/create-versioned-bucket-upload-object_2sessions.py", line 26, in <module>
    version_id = response['VersionId']
KeyError: 'VersionId'
$ s3api list-object-versions --bucket s3tests-2sessions
{
    "Versions": [
        {
            "ETag": "\"mtime-d445n9c39og0-ino-tq6\"",
            "Size": 9,
            "StorageClass": "STANDARD",
            "Key": "testobj",
            "VersionId": "null",
            "IsLatest": true,
            "LastModified": "2024-09-12T08:15:51+00:00",
            "Owner": {
                "DisplayName": "NooBaa",
                "ID": "123"
            }
        }
    ],
    "RequestCharged": null
}
$ s3api get-bucket-versioning --bucket s3tests-2sessions
{
    "Status": "Enabled"
}
```

Trying to re-create stepping through the code:

```
Python 3.8.8 (default, Aug 25 2021, 16:13:02) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> session = boto3.Session(profile_name='s3user1')
>>> endpoint = 'https://localhost:6443'
>>> bucket_name = "s3tests-2sessions"
>>> session = boto3.Session(profile_name='s3user1')
>>> cos = session.client('s3', endpoint_url=endpoint, verify='/home/vagrant/aws-cert/tls.crt')
>>> cos2 = session.client('s3', endpoint_url=endpoint, verify='/home/vagrant/aws-cert/tls.crt')
>>> bucket_name = "s3tests-2sessions-2"
>>> response = cos.create_bucket(Bucket=bucket_name)
>>> print(response)
{'ResponseMetadata': {'RequestId': 'm0z0s3kv-8oaqd1-3h1', 'HostId': 'm0z0s3kv-8oaqd1-3h1', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'm0z0s3kv-8oaqd1-3h1', 'x-amz-id-2': 'm0z0s3kv-8oaqd1-3h1', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS', 'access-control-allow-headers': 'Content-Type,Content-MD5,Authorization,X-Amz-User-Agent,X-Amz-Date,ETag,X-Amz-Content-Sha256,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'ETag,X-Amz-Version-Id', 'location': '/s3tests-2sessions-2', 'date': 'Thu, 12 Sep 2024 08:20:37 GMT', 'connection': 'keep-alive', 'keep-alive': 'timeout=5', 'content-length': '0'}, 'RetryAttempts': 0}, 'Location': '/s3tests-2sessions-2'}
>>> response = cos2.put_bucket_versioning(Bucket=bucket_name, VersioningConfiguration={'Status': 'Enabled'})
>>> print(response)
{'ResponseMetadata': {'RequestId': 'm0z0td4q-98vk5j-1b76', 'HostId': 'm0z0td4q-98vk5j-1b76', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'm0z0td4q-98vk5j-1b76', 'x-amz-id-2': 'm0z0td4q-98vk5j-1b76', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS', 'access-control-allow-headers': 'Content-Type,Content-MD5,Authorization,X-Amz-User-Agent,X-Amz-Date,ETag,X-Amz-Content-Sha256,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'ETag,X-Amz-Version-Id', 'date': 'Thu, 12 Sep 2024 08:21:36 GMT', 'connection': 'keep-alive', 'keep-alive': 'timeout=5', 'content-length': '0'}, 'RetryAttempts': 0}}
>>> response = cos2.get_bucket_versioning(Bucket=bucket_name)
>>> print(response)
{'ResponseMetadata': {'RequestId': 'm0z0up4x-cstaii-4c2', 'HostId': 'm0z0up4x-cstaii-4c2', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'm0z0up4x-cstaii-4c2', 'x-amz-id-2': 'm0z0up4x-cstaii-4c2', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS', 'access-control-allow-headers': 'Content-Type,Content-MD5,Authorization,X-Amz-User-Agent,X-Amz-Date,ETag,X-Amz-Content-Sha256,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'ETag,X-Amz-Version-Id', 'content-type': 'application/xml', 'content-length': '161', 'date': 'Thu, 12 Sep 2024 08:22:38 GMT', 'connection': 'keep-alive', 'keep-alive': 'timeout=5'}, 'RetryAttempts': 0}, 'Status': 'Enabled'}
>>> response = cos.get_bucket_versioning(Bucket=bucket_name)
>>> print(response)
{'ResponseMetadata': {'RequestId': 'm0z0vb65-5gtiyy-j7d', 'HostId': 'm0z0vb65-5gtiyy-j7d', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'm0z0vb65-5gtiyy-j7d', 'x-amz-id-2': 'm0z0vb65-5gtiyy-j7d', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS', 'access-control-allow-headers': 'Content-Type,Content-MD5,Authorization,X-Amz-User-Agent,X-Amz-Date,ETag,X-Amz-Content-Sha256,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'ETag,X-Amz-Version-Id', 'content-type': 'application/xml', 'content-length': '161', 'date': 'Thu, 12 Sep 2024 08:23:07 GMT', 'connection': 'keep-alive', 'keep-alive': 'timeout=5'}, 'RetryAttempts': 0}, 'Status': 'Enabled'}
>>> data = 'content-1'
>>> response = cos.put_object(Bucket=bucket_name, Key='testobj', Body=data)
>>> print(response)
{'ResponseMetadata': {'RequestId': 'm0z0zdk1-rq59v-15bi', 'HostId': 'm0z0zdk1-rq59v-15bi', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'm0z0zdk1-rq59v-15bi', 'x-amz-id-2': 'm0z0zdk1-rq59v-15bi', 'access-control-allow-origin': '*', 'access-control-allow-credentials': 'true', 'access-control-allow-methods': 'GET,POST,PUT,DELETE,OPTIONS', 'access-control-allow-headers': 'Content-Type,Content-MD5,Authorization,X-Amz-User-Agent,X-Amz-Date,ETag,X-Amz-Content-Sha256,amz-sdk-invocation-id,amz-sdk-request', 'access-control-expose-headers': 'ETag,X-Amz-Version-Id', 'x-amz-version-id': 'mtime-d445v8gupd6o-ino-19ts', 'etag': '"mtime-d445v8gupd6o-ino-19ts"', 'date': 'Thu, 12 Sep 2024 08:26:16 GMT', 'connection': 'keep-alive', 'keep-alive': 'timeout=5', 'content-length': '0'}, 'RetryAttempts': 0}, 'ETag': '"mtime-d445v8gupd6o-ino-19ts"', 'VersionId': 'mtime-d445v8gupd6o-ino-19ts'}
>>> quit()
```

so the issue could not be re-created that way.

We then modified the python test code and added `cos.get_bucket_versioning()` directly after `cos2.put_bucket_versioning()`. With that change, we were not able to re-produce.

After that, we reverted the Python script code changes and also weren't able to reproduce with the original script.
That provides strong evidence that the issue is highly timing-dependent, probably due to the limitations of the resource-constrained VM (8GB RAM, 2 cores, 10GB system disk) used for testing.

"all" - level logs for the issues attached
[noobaa_20240912_1.log.gz](https://github.com/user-attachments/files/16976541/noobaa_20240912_1.log.gz)

**Comment by shirady** [comment] 2024-09-12 09:25
Hi,
1. I would share that I tried to run the Ceph test with the mentioned fixes and I was not able to reproduce the issue (see additional information below).
2. I talked with @hseipp today (more details on the comment above)

#### Additional information:

`s3tests_boto3/functional/__init__.py
````python
def get_new_bucket_resource(name=None):
    """
    Get a bucket that exists and is empty.

    Always recreates a bucket from scratch. This is useful to also
    reset ACLs and such.
    """
    s3 = boto3.resource('s3',
                        aws_access_key_id=config.main_access_key,
                        aws_secret_access_key=config.main_secret_key,
                        endpoint_url=config.default_endpoint,
                        use_ssl=config.default_is_secure,
                        verify=config.default_ssl_verify)
    if name is None:
        name = get_new_bucket_name()
    bucket = s3.Bucket(name)
    # bucket_location = bucket.create()
    return bucket
```

`s3tests_boto3/functional/test_s3.py`
```
def test_bucket_list_return_data_versioning():
    bucket_name = get_new_bucket()
    check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
    key_names = ['bar', 'baz', 'foo']
    bucket_name = _create_objects(bucket_name=bucket_name,keys=key_names)

    client = get_client()
    data = {}

    for key_name in key_names:
        obj_response = client.head_object(Bucket=bucket_name, Key=key_name)
        data.update({
            key_name: {
                'ETag': obj_response['ETag'],
                'LastModified': obj_response['LastModified'],
                'ContentLength': obj_response['ContentLength'],
                'VersionId': obj_response['VersionId']
                }
            })

    response  = client.list_object_versions(Bucket=bucket_name)
    objs_list = response['Versions']

    for obj in objs_list:
        key_name = obj['Key']
        key_data = data[key_name]
        assert obj['ETag'] == key_data['ETag']
        assert obj['Size'] == key_data['ContentLength']
        assert obj['VersionId'] == key_data['VersionId']
        _compare_dates(obj['LastModified'],key_data['LastModified'])
```

logs from my running Ceph tests (remove the credential printings)
For example - put with headers prints:
> Sep-12 10:58:42.689 [nsfs/39789]   [LOG] CONSOLE:: SDSD header version id mtime-d445a4kmwyrk-ino-2flsdj
> Sep-12 10:58:42.689 [nsfs/39789]    [L1] core.util.http_utils:: HTTP REPLY EMPTY PUT /shira-isdvuwge37qqejuydgitbrb-1/foo {"host":"localhost:6443","accept-encoding":"identity","user-agent":"Boto3/1.24.96 Python/3.11.9 Darwin/23.4.0 Botocore/1.27.96 Resource","content-md5":"rL0Y20zC+Fzt72VPzMSk2A==","expect":"100-continue","x-amz-date":"20240912T075842Z","x-amz-content-sha256":"UNSIGNED-PAYLOAD","authorization":"AWS4-HMAC-SHA256 Credential=<>/20240912/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=836758837b59f4e5a342fc0b5d8149a0f4949ca261e60dd52db6b5812b2c04d1","amz-sdk-invocation-id":"611be87d-9955-448d-a6ab-43aa1c953986","amz-sdk-request":"attempt=1","content-length":"3"} 200

List object - we can the version-id for each object
Sep-12 10:58:42.722 [nsfs/39789]    [L1] core.util.http_utils:: HTTP REPLY XML GET /shira-isdvuwge37qqejuydgitbrb-1?versions&encoding-type=url {"host":"localhost:6443","accept-encoding":"identity","user-agent":"Boto3/1.24.96 Python/3.11.9 Darwin/23.4.0 Botocore/1.27.96","x-amz-date":"20240912T075842Z","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","authorization":"AWS4-HMAC-SHA256 Credential=<>/20240912/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7a9d98ae263f6daadad88a50cf5ca7b2e4fbfb3f8303c11a0de6f2d784f76875","amz-sdk-invocation-id":"b046de86-3eb7-4b99-bb3f-9eb6a15787ab","amz-sdk-request":"attempt=1"} <?xml version="1.0" encoding="UTF-8"?><ListVersionsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>shira-isdvuwge37qqejuydgitbrb-1</Name><Prefix>undefined</Prefix><Delimiter>undefined</Delimiter><MaxKeys>1000</MaxKeys><KeyMarker>undefined</KeyMarker><IsTruncated>false</IsTruncated><NextKeyMarker>undefined</NextKeyMarker><EncodingType>url</EncodingType><Version><Key>bar</Key><VersionId>mtime-d445a4k6getc-ino-2flsdc</VersionId><IsLatest>true</IsLatest><LastModified>2024-09-12T07:58:42.000Z</LastModified><ETag>&quot;mtime-d445a4k6getc-ino-2flsdc&quot;</ETag><Size>3</Size><Owner><ID>66e02998446842a899c69bef</ID><DisplayName>ceph</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Version><Version><Key>baz</Key><VersionId>mtime-d445a4kf9rls-ino-2flsdg</VersionId><IsLatest>true</IsLatest><LastModified>2024-09-12T07:58:42.000Z</LastModified><ETag>&quot;mtime-d445a4kf9rls-ino-2flsdg&quot;</ETag><Size>3</Size><Owner><ID>66e02998446842a899c69bef</ID><DisplayName>ceph</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Version><Version><Key>foo</Key><VersionId>mtime-d445a4kmwyrk-ino-2flsdj</VersionId><IsLatest>true</IsLatest><LastModified>2024-09-12T07:58:42.000Z</LastModified><ETag>&quot;mtime-d445a4kmwyrk-ino-2flsdj&quot;</ETag><Size>3</Size><Owner><ID>66e02998446842a899c69bef</ID><DisplayName>ceph</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Version></ListVersionsResult>

Cleanup step - we can see the version-id for each object
`Sep-12 10:58:42.762 [nsfs/39789]    [L1] core.util.http_utils:: HTTP REPLY XML POST /shira-isdvuwge37qqejuydgitbrb-1?delete {"host":"localhost:6443","accept-encoding":"identity","x-amz-bypass-governance-retention":"True","user-agent":"Boto3/1.24.96 Python/3.11.9 Darwin/23.4.0 Botocore/1.27.96","content-md5":"WhPchyR5tLbQureqoi5M0w==","x-amz-date":"20240912T075842Z","x-amz-content-sha256":"659a9a1b8150670cc7d046844c0c92886a4d52f6c67b3456e0dfa1e10e48c38d","authorization":"AWS4-HMAC-SHA256 Credential=<>/20240912/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-bypass-governance-retention;x-amz-content-sha256;x-amz-date, Signature=21e09f517c34d6e343815f232be8fd24f9dd0ffe23fabbaca568b2df72e7010a","amz-sdk-invocation-id":"9adbe021-f600-438b-b15e-c5e0f5a19bdb","amz-sdk-request":"attempt=1","content-length":"333"} <?xml version="1.0" encoding="UTF-8"?><DeleteResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Deleted><Key>bar</Key><VersionId>mtime-d445a4k6getc-ino-2flsdc</VersionId></Deleted><Deleted><Key>baz</Key><VersionId>mtime-d445a4kf9rls-ino-2flsdg</VersionId></Deleted><Deleted><Key>foo</Key><VersionId>mtime-d445a4kmwyrk-ino-2flsdj</VersionId></Deleted></DeleteResult`

**Comment by romayalon** [comment] 2024-09-12 10:21
@hseipp when running with get_object_acl(), are you able to reproduce the bug?

**Comment by hseipp** [comment] 2024-09-13 06:56
@romayalon  yes:

```
============================================================================ FAILURES ============================================================================
____________________________________________________________ test_bucket_list_return_data_versioning _____________________________________________________________

    @pytest.mark.fails_on_dbstore
    @pytest.mark.versioning
    def test_bucket_list_return_data_versioning():
        bucket_name = get_new_bucket()
        check_configure_versioning_retry(bucket_name, "Enabled", "Enabled")
        key_names = ['bar', 'baz', 'foo']
        bucket_name = _create_objects(bucket_name=bucket_name,keys=key_names)
    
        client = get_client()
        data = {}
    
        for key_name in key_names:
            obj_response = client.head_object(Bucket=bucket_name, Key=key_name)
            acl_response = client.get_object_acl(Bucket=bucket_name, Key=key_name)
            data.update({
                key_name: {
                    'ID': acl_response['Owner']['ID'],
                    'DisplayName': acl_response['Owner']['DisplayName'],
                    'ETag': obj_response['ETag'],
                    'LastModified': obj_response['LastModified'],
                    'ContentLength': obj_response['ContentLength'],
>                   'VersionId': obj_response['VersionId']
                    }
                })
E           KeyError: 'VersionId'
```

This error I can reproduce 100%.
If I do a manual `list-object-versions` afterwards, I see the object versions:
```
$ s3api list-object-versions --bucket s3tests-d2hykax4i5rgvhlfx8nit-1
{
    "Versions": [
        {
            "ETag": "\"mtime-d44yiragvpj4-ino-11xf\"",
            "Size": 3,
            "StorageClass": "STANDARD",
            "Key": "bar",
            "VersionId": "mtime-d44yiragvpj4-ino-11xf",
            "IsLatest": true,
            "LastModified": "2024-09-13T06:53:31+00:00",
            "Owner": {
                "DisplayName": "NooBaa",
                "ID": "123"
            }
        },
        {
            "ETag": "\"mtime-d44yirb0ehog-ino-11xg\"",
            "Size": 3,
            "StorageClass": "STANDARD",
            "Key": "baz",
            "VersionId": "mtime-d44yirb0ehog-ino-11xg",
            "IsLatest": true,
            "LastModified": "2024-09-13T06:53:31+00:00",
            "Owner": {
                "DisplayName": "NooBaa",
                "ID": "123"
            }
        },
        {
            "ETag": "\"mtime-d44yirbextkw-ino-11xh\"",
            "Size": 3,
            "StorageClass": "STANDARD",
            "Key": "foo",
            "VersionId": "mtime-d44yirbextkw-ino-11xh",
            "IsLatest": true,
            "LastModified": "2024-09-13T06:53:31+00:00",
            "Owner": {
                "DisplayName": "NooBaa",
                "ID": "123"
            }
        }
    ],
    "RequestCharged": null
}
```

**Comment by shirady** [comment] 2024-09-17 06:32
@hseipp,
Could you please attach the logs of what you could reproduce? (in the [comment above](https://github.com/noobaa/noobaa-core/issues/8332#issuecomment-2348173424))
(You can edit the comment and add the logs if you want).

**Comment by hseipp** [comment] 2024-09-17 08:14
@shirady Unfortunately I no longer have access to the logs after I have destroyed and re-deployed my test environment yesterday. I am now running Storage Scale 5.2.2.0 240913.105913 with noobaa-core-5.17.0-20240904.
With this setup I am no longer able to re-create the error running `test_bucket_list_return_data_versioning()`  even with `get_object_acl()`. The above Python script now also passes.

**Comment by shirady** [comment] 2024-09-17 08:19
@hseipp thanks for sharing.
@romayalon @hseipp, can we close the issue, or do you think there is still something to investigate?

**Comment by hseipp** [comment] 2024-09-17 09:05
I'm OK with closing.

**Comment by romayalon** [comment] 2024-09-19 06:02
Closing, if needed @hseipp feel free to re-open.

**Closed by romayalon** 2024-09-19 06:02 UTC
Labels: NS-FS
