### ISSUE TITLE
Noobaa ingests Warp data at incorrect size

### ISSUE THREAD

**Issue by delillol** [noobaa/noobaa-core#6392] opened 2021-03-01 22:24 UTC
### Environment info
- NooBaa Version:
INFO[0000] CLI version: 5.5.0-nsfs                   
INFO[0000] noobaa-image: noobaa/noobaa-core:5.5.0-nsfs
INFO[0000] operator-image: noobaa/noobaa-operator:5.5.0-nsfs
- Platform: Kubernetes 1.20.4

### Actual behavior
1. Warp is a publicly available tool in which to run to s3 protocol.  In this test, I have a single bucket called nsfs and Warp is running IO to it.  Trying to transfer all 1M files, but when they get ingested, they are at size: 1001525, as shown below.  You can also see the errors Warp throws when it tries to GET the objects that it previously PUT.  The GETs expected 1M objects, but saw larger objects.  Also, the Warp job that I ran below did not have multipart enabled.  I get the same errors whether or not multipart is enabled.

More data:  When we run this exact same job on minio, no errors occur and the objects all show up as 1M.

Here I am trying to run all 1M files.  They transfer to Noobaa nsfs bucket as 1001525:
-------------------------------------------------------------------------------------
(Fri Feb 26 07:19:35) stevefeb22-x-app1:~  **./warp mixed --access-key=fxzjlNA4ukK6r9o515ux --secret-key=wRtSyCMwXs6sucLEW6rdzRfRvL9UtO1b3N2r0eQD --obj.size=1M --host=stevefeb22-x-master.fyre.ibm.com:31168 --duration=60s --disable-multipart --objects=50 --bucket=nsfs --insecure**
warp: <ERROR> We encountered an internal error. Please try again.                                                  
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525                                                      
warp: <ERROR> unexpected stat size. want:1000000, got:1001525    

Inside of the bucket, we can see that the files got ingested at incorrect sizes:
------------------------------------------------------------------------------
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20 '11.jAM9(NyhwNj(c4Fm.rnd'
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  16.DbcqY06ofEyT064V.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  29.lVl4UZFuBtOGh41p.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  36.WSntmmYxYTsUrgA5.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  46.TYEJKGGCVOHF9QY9.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20 '52.HikhV5Ci4C(hP6JA.rnd'
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  57.lHJMri5ijC669qBP.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  59.GTyv96pNhxDMhIeE.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  62.68IEubzctC3xMFzc.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20  64.JjG3gJwtzz8NRfTA.rnd
-rw-r--r-- 1 noob root 1001525 Feb 26 15:20 '67.jFlHtJSDO9OlW)NM.rnd'  

### Expected behavior
1. We expect the files to show up as the correct size. Warp should be able to run for 60 seconds with no errors.

### Steps to reproduce
1. Rerun the Warp job shown above.

**Comment by guymguym** [comment] 2021-03-01 23:23
Hi @delillol Thanks for the info!
Can you please get one of the PUT object logs from the noobaa-endpoint pod?
It would help to understand what were the request headers and these will be shown in the log.
Thanks

**Comment by delillol** [comment] 2021-03-01 23:36
@guymguym : Hello.  Just reran a few objects today to get the logs.  Here is the endpoint logs for a PUT and GET operation:

^[[32mMar-1 23:30:45.074^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.endpoint.s3.s3_rest:: S3 REQUEST PUT /nsfs/119%28nd2Z/11.hursGhFNqmfW%28nKu.rnd op put_object request_id klr7tsjy-cxgik2-y95 { host: ^[[32m'stevefeb22-x-master.fyre.ibm.com:31168'^[[39m, ^[[32m'user-agent'^[[39m: ^[[32m'MinIO (linux; amd64) minio-go/v7.0.6 warp/0.3.40'^[[39m, ^[[32m'content-length'^[[39m: ^[[32m'1001525'^[[39m, authorization: ^[[32m'AWS4-HMAC-SHA256 Credential=fxzjlNA4ukK6r9o515ux/20210301/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=b2ba5f2f4062a91b7181ba78bdb29fd8ea08911c7d74add1663db3e9590e8fb9'^[[39m, ^[[32m'content-type'^[[39m: ^[[32m'application/octet-stream'^[[39m, ^[[32m'x-amz-content-sha256'^[[39m: ^[[32m'STREAMING-AWS4-HMAC-SHA256-PAYLOAD'^[[39m, ^[[32m'x-amz-date'^[[39m: ^[[32m'20210301T233045Z'^[[39m, ^[[32m'x-amz-decoded-content-length'^[[39m: ^[[32m'1000000'^[[39m }
^[[32mMar-1 23:30:45.076^[[35m [Endpoint/12] ^[[36m  [LOG]^[[39m CONSOLE:: /nsfs/nsfs/4LFAOm(Z/6.DXwGEijtltb017Z4.rnd Stats { dev: ^[[33m81^[[39m, mode: ^[[33m33188^[[39m, nlink: ^[[33m1^[[39m, uid: ^[[33m10001^[[39m, gid: ^[[33m0^[[39m, rdev: ^[[33m0^[[39m, blksize: ^[[33m1048576^[[39m, ino: ^[[33m2626147^[[39m, size: ^[[33m1001525^[[39m, blocks: ^[[33m0^[[39m, atimeMs: ^[[33m1614641443711.529^[[39m, mtimeMs: ^[[33m1614641443770.5718^[[39m, ctimeMs: ^[[33m1614641443770.5718^[[39m, birthtimeMs: ^[[33m0^[[39m, atime: ^[[35m2021-03-01T23:30:43.712Z^[[39m, mtime: ^[[35m2021-03-01T23:30:43.771Z^[[39m, ctime: ^[[35m2021-03-01T23:30:43.771Z^[[39m, birthtime: ^[[35m1970-01-01T00:00:00.000Z^[[39m }
^[[32mMar-1 23:30:45.076^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.util.http_utils:: HTTP REPLY EMPTY HEAD /nsfs/4LFAOm%28Z/6.DXwGEijtltb017Z4.rnd {"host":"stevefeb22-x-master.fyre.ibm.com:31168","user-agent":"MinIO (linux; amd64) minio-go/v7.0.6 warp/0.3.40","authorization":"AWS4-HMAC-SHA256 Credential=fxzjlNA4ukK6r9o515ux/20210301/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=f64c3f60448ae8ff62f4262b0721f31730125542c3a202c02636a61e53651ae7","x-amz-content-sha256":"e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855","x-amz-date":"20210301T233045Z"} ^[[33m200^[[39m
^[[32mMar-1 23:30:45.076^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.util.http_utils:: HTTP REPLY RAW GET /nsfs/BGma9Itb/5.5VvNRSQopaM3UqaT.rnd
^[[32mMar-1 23:30:45.077^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.endpoint.s3.ops.s3_put_object:: PUT OBJECT nsfs 119(nd2Z/11.hursGhFNqmfW(nKu.rnd
^[[32mMar-1 23:30:45.077^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.endpoint.s3.s3_rest:: S3 REQUEST GET /nsfs/BGma9Itb/4.oMsBClYuoZZ9cJhP.rnd op get_object request_id klr7tsju-cv2msl-v4s { host: ^[[32m'stevefeb22-x-master.fyre.ibm.com:31168'^[[39m, ^[[32m'user-agent'^[[39m: ^[[32m'MinIO (linux; amd64) minio-go/v7.0.6 warp/0.3.40'^[[39m, authorization: ^[[32m'AWS4-HMAC-SHA256 Credential=fxzjlNA4ukK6r9o515ux/20210301/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=677c1f5772944331e4e6a88f6de0fb6a3da570b0756c22d6b3cee66bc6a664fd'^[[39m, ^[[32m'x-amz-content-sha256'^[[39m: ^[[32m'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'^[[39m, ^[[32m'x-amz-date'^[[39m: ^[[32m'20210301T233045Z'^[[39m }
^[[32mMar-1 23:30:45.077^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.endpoint.s3.s3_rest:: S3 REQUEST GET /nsfs/tJJey5to/8.YmoIRIStPPWL%28A9L.rnd op get_object request_id klr7tsju-cv9mvv-8ll { host: ^[[32m'stevefeb22-x-master.fyre.ibm.com:31168'^[[39m, ^[[32m'user-agent'^[[39m: ^[[32m'MinIO (linux; amd64) minio-go/v7.0.6 warp/0.3.40'^[[39m, authorization: ^[[32m'AWS4-HMAC-SHA256 Credential=fxzjlNA4ukK6r9o515ux/20210301/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=296a8c1e74fd0982bce3aef04446dc067f6288649a2b56f00e908ce0712c7138'^[[39m, ^[[32m'x-amz-content-sha256'^[[39m: ^[[32m'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'^[[39m, ^[[32m'x-amz-date'^[[39m: ^[[32m'20210301T233045Z'^[[39m }
^[[32mMar-1 23:30:45.078^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.util.http_utils:: HTTP REPLY EMPTY PUT /nsfs/4LFAOm%28Z/8.Ww3JMXRh4S0JYvME.rnd {"host":"stevefeb22-x-master.fyre.ibm.com:31168","user-agent":"MinIO (linux; amd64) minio-go/v7.0.6 warp/0.3.40","content-length":"1001525","authorization":"AWS4-HMAC-SHA256 Credential=fxzjlNA4ukK6r9o515ux/20210301/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=1560987ab2e0b0191ea567396d5084cdb25bb31809331af8d0fd98fa74c1a45b","content-type":"application/octet-stream","x-amz-content-sha256":"STREAMING-AWS4-HMAC-SHA256-PAYLOAD","x-amz-date":"20210301T233044Z","x-amz-decoded-content-length":"1000000"} ^[[33m200^[[39m
^[[32mMar-1 23:30:45.080^[[35m [Endpoint/12] ^[[36m   [L0]^[[39m core.util.signature_utils:: _string_to_sign_v4 method PUT pathname /nsfs/tJJey5to/9.9idWfedWldpT3GiM.rnd search  headers { Host: ^[[32m'stevefeb22-x-master.fyre.ibm.com:31168'^[[39m, ^[[32m'User-Agent'^[[39m: ^[[32m'MinIO (linux; amd64) minio-go/v7.0.6 warp/0.3.40'^[[39m, ^[[32m'Content-Length'^[[39m: ^[[32m'1001525'^[[39m, Authorization: ^[[32m'AWS4-HMAC-SHA256 Credential=fxzjlNA4ukK6r9o515ux/20210301/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=bb9661b9d75d3da1e843a9dc40d30a227f8f05563ecf2fea24bb477cd23d336c'^[[39m, ^[[32m'Content-Type'^[[39m: ^[[32m'application/octet-stream'^[[39m, ^[[32m'X-Amz-Content-Sha256'^[[39m: ^[[32m'STREAMING-AWS4-HMAC-SHA256-PAYLOAD'^[[39m, ^[[32m'X-Amz-Date'^[[39m: ^[[32m'20210301T233045Z'^[[39m, ^[[32m'X-Amz-Decoded-Content-Length'^[[39m: ^[[32m'1000000'^[[39m } region us-east-1 canonical_str
PUT
/nsfs/tJJey5to/9.9idWfedWldpT3GiM.rnd

**Comment by guymguym** [comment] 2021-03-08 22:15
Hi @delillol 

Thanks for the logs! I can clearly see that this warp client uses `STREAMING-AWS4-HMAC-SHA256-PAYLOAD` which means that the content is chunked encoded. 

We support this mode of course, but previously this was not handled correctly for namespace buckets (see issue #6122) and then resolved in #6206 which was not included in version 5.5. 

So I would be happy to know if this reproduces on new master builds - which I do not expect.

Closing this issue for now so that I won't forget, but please let us know if this is indeed working or reopen if the issue is reproduced.

Thanks!

**Closed by guymguym** 2021-03-08 22:15 UTC
