### ISSUE TITLE
namespacestore status Rejected, Mode: STORAGE_NOT_EXIST 

### ISSUE THREAD

**Issue by akmithal** [noobaa/noobaa-core#6604] opened 2021-06-24 04:32 UTC
### Environment info
- NooBaa Version: master-20210622
- Platform: OCP 4.6.16

### Actual behavior
1. Namespacestore status is Rejected

### Expected behavior
1. Namespacestore status should be Ready

### Steps to reproduce
1. Installed master-20210622 
2. Created PVC gpfs-vol 
3. Created namespacestore using command:

`noobaa namespacestore create nsfs nsfs-nsr-1 --pvc-name='gpfs-vol' --fs-backend='GPFS'
`

```
[root@ocp-akshat-1-inf ~]# noobaa namespacestore list
NAME         TYPE   TARGET-BUCKET   PHASE      AGE         
nsfs-nsr-1   nsfs                   Rejected   26h17m28s   
```

```
[root@ocp-akshat-1-inf ~]# noobaa namespacestore status nsfs-nsr-1
INFO[0000] ✅ Exists: NamespaceStore "nsfs-nsr-1"        
ERRO[0000] ❌ NamespaceStore "nsfs-nsr-1" Phase is "Rejected": Namespace store mode: STORAGE_NOT_EXIST NamespaceStorePhaseRejected 

# NamespaceStore spec:
nsfs:
  fsBackend: GPFS
  pvcName: gpfs-vol
  subPath: ""
type: nsfs
```

### More information - Screenshots / Logs / Other output

```
[root@ocp-akshat-1-inf ~]# oc get pvc -A
NAMESPACE                       NAME                                               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                     AGE
ibm-spectrum-scale-csi-driver   scale-fset-pvc                                     Bound    pvc-a80a1fa0-b027-49e8-8ce7-b6d1f981eeea   50Gi       RWX            ibm-spectrum-scale-csi-fileset   55d
ibm-spectrum-scale-ns           datadir-ibm-spectrum-scale-pmcollector-0           Bound    worker2.ocp-akshat-1.cp.fyre.ibm.com-pv    25Gi       RWO            ibm-spectrum-scale-internal      55d
ibm-spectrum-scale-ns           datadir-ibm-spectrum-scale-pmcollector-1           Bound    worker0.ocp-akshat-1.cp.fyre.ibm.com-pv    25Gi       RWO            ibm-spectrum-scale-internal      55d
noobaa                          db-noobaa-db-pg-0                                  Bound    pvc-d1c22d45-5f3b-4684-8f4c-48880815f451   50Gi       RWO            ibm-spectrum-scale-csi-fileset   4h17m
noobaa                          gpfs-vol                                           Bound    pvc-0ff5b2f7-6017-43f2-a19a-4e9136657b78   2000Gi     RWX            ibm-spectrum-scale-csi-fileset   4h15m
noobaa                          noobaa-default-backing-store-noobaa-pvc-b0a5d78b   Bound    pvc-9807ce5b-863c-42ae-9bbf-14d33d2b1d1a   50Gi       RWO            ibm-spectrum-scale-csi-fileset   4h15m
openshift-image-registry        image-registry-storage                             Bound    registry-storage                           200Gi      RWX                                             56d
[root@ocp-akshat-1-inf ~]# oc get pv -A
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                                                            STORAGECLASS                     REASON   AGE
pvc-0ff5b2f7-6017-43f2-a19a-4e9136657b78   2000Gi     RWX            Delete           Bound      noobaa/gpfs-vol                                                  ibm-spectrum-scale-csi-fileset            4h14m
pvc-9807ce5b-863c-42ae-9bbf-14d33d2b1d1a   50Gi       RWO            Delete           Bound      noobaa/noobaa-default-backing-store-noobaa-pvc-b0a5d78b          ibm-spectrum-scale-csi-fileset            4h15m
pvc-a80a1fa0-b027-49e8-8ce7-b6d1f981eeea   50Gi       RWX            Delete           Bound      ibm-spectrum-scale-csi-driver/scale-fset-pvc                     ibm-spectrum-scale-csi-fileset            55d
pvc-d1c22d45-5f3b-4684-8f4c-48880815f451   50Gi       RWO            Delete           Bound      noobaa/db-noobaa-db-pg-0                                         ibm-spectrum-scale-csi-fileset            4h17m
registry-storage                           200Gi      RWX            Recycle          Bound      openshift-image-registry/image-registry-storage                                                            56d
task-pv-volume                             1000Gi     RWO            Retain           Released   noobaa/task-pv-claim                                             ibm-spectrum-scale-csi-fileset            34d
worker0.ocp-akshat-1.cp.fyre.ibm.com-pv    25Gi       RWO            Delete           Bound      ibm-spectrum-scale-ns/datadir-ibm-spectrum-scale-pmcollector-1   ibm-spectrum-scale-internal               55d
worker2.ocp-akshat-1.cp.fyre.ibm.com-pv    25Gi       RWO            Delete           Bound      ibm-spectrum-scale-ns/datadir-ibm-spectrum-scale-pmcollector-0   ibm-spectrum-scale-internal               55d

[root@ocp-akshat-1-inf ~]# podn
NAME                                               READY   STATUS        RESTARTS   AGE
noobaa-core-0                                      1/1     Running       0          4h3m
noobaa-db-pg-0                                     1/1     Running       0          4h17m
noobaa-default-backing-store-noobaa-pod-b0a5d78b   0/1     Terminating   0          20m
noobaa-endpoint-566488749f-c48tq                   1/1     Running       0          4h4m
noobaa-operator-656d4f678-lw5k6                    1/1     Running       4          4h17m

```

Mount is working fine as well and buckets are created too. IO operations are fine as well.

```
fs1                                   2.0T   83G  1.9T   5% /nsfs/nsfs-nsr-1
sh-4.4# cd /nsfs/nsfs-nsr-1/bucket-
bucket-1/           bucket-11/          bucket-12/          bucket-13/          bucket-2/           bucket-21/          bucket-3/           bucket-max-objects/ 
```

**Comment by akmithal** [comment] 2021-06-24 09:01
This is from Srikanth's environment:

```
[root@hpoocpci-inf HPO]# noobaa namespacestore list
NAME   TYPE   TARGET-BUCKET   PHASE   AGE     
fs1    nsfs                   Ready   1m40s   
[root@hpoocpci-inf HPO]# 
[root@hpoocpci-inf HPO]# 
[root@hpoocpci-inf HPO]# noobaa namespacestore delete fs1
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: pool.read_namespace_resource() Request: {Name:fs1} 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:46363/rpc/ 0xc000d9eaf0 
INFO[0001] RPC: Connecting websocket (0xc000d9eaf0) &{RPC:0xc00049aaf0 Address:wss://localhost:46363/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] RPC: Connected websocket (0xc000d9eaf0) &{RPC:0xc00049aaf0 Address:wss://localhost:46363/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0001] ✅ RPC: pool.read_namespace_resource() Response OK: took 0.4ms 
INFO[0001] 🗑️  Deleting: NamespaceStore "fs1"           
INFO[0002] 🗑️  Deleted : NamespaceStore "fs1"           
[root@hpoocpci-inf HPO]# noobaa namespacestore create nsfs "fs1" --pvc-name="gpfs-vol" --fs-backend="GPFS"
I0624 01:49:34.918744  693261 request.go:645] Throttling request took 1.017270208s, request: GET:https://api.hpoocpci.cp.fyre.ibm.com:6443/apis/rbac.authorization.k8s.io/v1beta1?timeout=32s
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Created: NamespaceStore "fs1"              
INFO[0001]                                              
INFO[0001] NOTE:                                        
INFO[0001]   - This command has finished applying changes to the cluster. 
INFO[0001]   - From now on, it only loops and reads the status, to monitor the operator work. 
INFO[0001]   - You may Ctrl-C at any time to stop the loop and watch it manually. 
INFO[0001]                                              
INFO[0001] NamespaceStore Wait Ready:                   
INFO[0001] ⏳ NamespaceStore "fs1" Phase is "": waiting... 
INFO[0004] ✅ NamespaceStore "fs1" Phase is Ready        
INFO[0004]                                              
INFO[0004]                                              
INFO[0004] ✅ Exists: NamespaceStore "fs1"               
INFO[0004] ✅ NamespaceStore "fs1" Phase is Ready        
# NamespaceStore spec:
nsfs:
  fsBackend: GPFS
  pvcName: gpfs-vol
  subPath: ""
type: nsfs
[root@hpoocpci-inf HPO]# noobaa namespacestore list
NAME   TYPE   TARGET-BUCKET   PHASE      AGE    
fs1    nsfs                   Rejected   8m5s   
```

**Comment by bssrikanth** [comment] 2021-06-24 09:18
attaching logs:
[noobaa_diagnostics_1624526198.tar.gz](https://github.com/noobaa/noobaa-core/files/6707964/noobaa_diagnostics_1624526198.tar.gz)

**Comment by jeniawhite** [comment] 2021-06-29 08:12
I can see the following logs:
```
time="2021-06-24T06:46:21Z" level=info msg="ReconcileNamespaceStores: nsr: {Name:fs1 Mode:STORAGE_NOT_EXIST Undeletable: EndpointType: Endpoint: TargetBucket: Identity: AuthMethod: CpCode:}" sys=noobaa/noobaa
time="2021-06-24T06:46:21Z" level=info msg="❌ Not Found: NamespaceStore \"fs1\"\n"
```
Seems like we are failing to reconcile the fs1, needs further investigation

**Comment by akmithal** [comment] 2021-07-20 04:24
Hi @jeniawhite , @nimrod-becker : Please see the challenge here:

During my IO test, found backend got removed ( Defect 6673). Now

-  I can't list the buckets to delete ( Get error An error occurred (NoSuchKey) when calling the ListObjectsV2 operation: The specified key does not exist.)
- Can't delete the namespacestore as get error like below
- 
Only way forward is to create a new namespacestore. 

`[root@ocp-akshat-1-inf ~]# noobaa namespacestore status nsfs-nsr-1
INFO[0001] ✅ Exists: NamespaceStore "nsfs-nsr-1"        
ERRO[0001] ❌ NamespaceStore "nsfs-nsr-1" Phase is "Rejected": Namespace store mode: STORAGE_NOT_EXIST NamespaceStorePhaseRejected 

# NamespaceStore spec:
nsfs:
  fsBackend: GPFS
  pvcName: gpfs-vol
  subPath: ""
type: nsfs

[root@ocp-akshat-1-inf ~]# noobaa namespacestore delete nsfs-nsr-1
I0719 21:19:04.416752 1021311 request.go:645] Throttling request took 1.01588118s, request: GET:https://api.ocp-akshat-1.cp.fyre.ibm.com:6443/apis/scheduling.k8s.io/v1beta1?timeout=32s
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
INFO[0001] ✅ Exists: Service "noobaa-mgmt"              
INFO[0001] ✅ Exists: Secret "noobaa-operator"           
INFO[0001] ✅ Exists: Secret "noobaa-admin"              
INFO[0001] ✈️  RPC: pool.read_namespace_resource() Request: {Name:nsfs-nsr-1} 
WARN[0001] RPC: GetConnection creating connection to wss://localhost:45991/rpc/ 0xc00053b130 
INFO[0001] RPC: Connecting websocket (0xc00053b130) &{RPC:0xc00053b180 Address:wss://localhost:45991/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0005] RPC: Connected websocket (0xc00053b130) &{RPC:0xc00053b180 Address:wss://localhost:45991/rpc/ State:init WS:<nil> PendingRequests:map[] NextRequestID:0 Lock:{state:1 sema:0} ReconnectDelay:0s} 
INFO[0005] ✅ RPC: pool.read_namespace_resource() Response OK: took 2.3ms 
FATA[0005] ❌ Could not delete NamespaceStore "nsfs-nsr-1" in namespace "noobaa" as it is being used by one or more buckets 
[root@ocp-akshat-1-inf ~]# noobaa namespacestore list
NAME         TYPE   TARGET-BUCKET   PHASE      AGE         
nsfs-nsr-1   nsfs                   Rejected   24h11m25s   
[root@ocp-akshat-1-inf ~]# noobaa namespacestore
Manage namespace stores

Available Commands:
  create      Create namespace store
  delete      Delete namespace store
  list        List namespace stores
  status      Status namespace store

Use "noobaa <command> --help" for more information about a given command.
[root@ocp-akshat-1-inf ~]# noobaa namespacestore create nsfs nsfs-nsr-1 --pvc-name='gpfs-vol' --fs-backend='GPFS'
INFO[0001] ✅ Exists: NooBaa "noobaa"                    
FATA[0001] ❌ NamespaceStore "nsfs-nsr-1" already exists in namespace "noobaa" 
`

**Comment by ketankhurana64** [comment] 2021-08-05 10:26
Please find the attached logs
[noobaa_diagnostics_1628068930.tar.gz](https://github.com/noobaa/noobaa-core/files/6937865/noobaa_diagnostics_1628068930.tar.gz)

**Comment by jeniawhite** [comment] 2021-08-16 15:48
@ketankhurana64 Sadly the logs are only 2 seconds long and have the bringup of the system.
I can also see that the debug level is not raised so in any case we won't be able to see any advanced logs.
Would be great if you could raise the debug level and reproduce.
Sorry for late response.

**Comment by ketankhurana64** [comment] 2021-10-06 08:22
This issue is not replicated anymore. We can close it now. @akmithal Since you've opened this issue, can you please close it. I don't have closing rights.

**Comment by nimrod-becker** [comment] 2021-10-06 08:52
Based on the last comment, closing

**Closed by nimrod-becker** 2021-10-06 08:52 UTC
Labels: NS-FS
