### ISSUE TITLE
Noobaa pods are not coming up by OCS

### ISSUE THREAD

**Issue by nishant16** [noobaa/noobaa-core#6721] opened 2021-08-31 10:27 UTC
### Environment info
- NooBaa Version: **VERSION**
- Platform: OpenShift 4.7

### Actual behavior
1. oc apply -f deploy-with-olm.yaml
2. namespace/openshift-storage created
operatorgroup.operators.coreos.com/openshift-storage-operatorgroup created
catalogsource.operators.coreos.com/ocs-catalogsource created
subscription.operators.coreos.com/ocs-subscription created

pods are not coming up:
[root@nishant-inf hpo-core]# oc get ns|grep openshift-storage
openshift-storage                                  Active   6m11s
[root@nishant-inf hpo-core]# oc get pods
No resources found in openshift-storage namespace.

### Expected behavior
1. Pod should come up for openshift-storage
# oc get pods -n openshift-storage
NAME                                    READY   STATUS    RESTARTS   AGE
noobaa-operator-7d69f7b694-xlktr        1/1     Running   0          17m
ocs-metrics-exporter-66b8747855-vg62p   1/1     Running   0          17m
ocs-operator-8d9ddf87c-k5z4l            1/1     Running   0          17m
rook-ceph-operator-7dd954cf46-924k6     1/1     Running   0          17m

### Steps to reproduce
# Apply olm in OCP cluster with CNSA CSI installation and check openshift-storage pods.

**Comment by nishant16** [comment] 2021-08-31 11:12
Issue is with latest image and 4.7.0 is working fine.

**Comment by nishant16** [comment] 2021-09-01 04:55
with 4.7.0 image endpoint image is not coming up:
NAME                                    READY   STATUS             RESTARTS   AGE
noobaa-core-0                           1/1     Running            0          41m
noobaa-db-pg-0                          1/1     Running            0          41m
noobaa-operator-8c4d4f845-lcd5z         1/1     Running            0          42m
ocs-metrics-exporter-675b75d957-hqlbx   1/1     Running            0          42m
ocs-operator-7f4644bdbd-72l28           0/1     CrashLoopBackOff   12         42m
rook-ceph-operator-644cddbc4c-cwmpq     1/1     Running            0          42m

**Comment by akmithal** [comment] 2021-09-02 09:36
@nishant16 , please add must-gather logs.

**Comment by nehasharma5** [comment] 2021-09-02 10:40
@jeniawhite : As discussed I reproduced it again and here are logs for same
[root@api.new.cp.fyre.ibm.com ~]# wget https://raw.githubusercontent.com/openshift/ocs-operator/master/deploy/deploy-with-olm.yaml
--2021-09-02 03:14:34--  https://raw.githubusercontent.com/openshift/ocs-operator/master/deploy/deploy-with-olm.yaml
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2240 (2.2K) [text/plain]
Saving to: ‘deploy-with-olm.yaml’
deploy-with-olm.yaml           100%[====================================================>]   2.19K  --.-KB/s    in 0s
2021-09-02 03:14:34 (31.4 MB/s) - ‘deploy-with-olm.yaml’ saved [2240/2240]
[root@api.new.cp.fyre.ibm.com ~]# oc create -f deploy-with-olm.yaml
namespace/openshift-storage created
operatorgroup.operators.coreos.com/openshift-storage-operatorgroup created
catalogsource.operators.coreos.com/ocs-catalogsource created
subscription.operators.coreos.com/ocs-subscription created
[root@api.new.cp.fyre.ibm.com ~]#
3:47
[root@api.new.cp.fyre.ibm.com ~]# oc get pod -n openshift-storage
No resources found in openshift-storage namespace.
[root@api.new.cp.fyre.ibm.com ~]# oc get pod -n openshift-storage
No resources found in openshift-storage namespace.
[root@api.new.cp.fyre.ibm.com ~]#

[root@api.new.cp.fyre.ibm.com ~]# oc get noobaa -n openshift-storage
No resources found in openshift-storage namespace.
[root@api.new.cp.fyre.ibm.com ~]#

Logs:
[ocs-logs.tar.gz](https://github.com/noobaa/noobaa-core/files/7098252/ocs-logs.tar.gz)

**Comment by bssrikanth** [comment] 2021-09-06 09:40
I have been hitting same issue. Attaching the must-gather logs here from my environment.
[must-gather.local.704311556809802228.tar.gz](https://github.com/noobaa/noobaa-core/files/7114923/must-gather.local.704311556809802228.tar.gz)

**Comment by rkomandu** [comment] 2021-09-09 08:15
This is a blocker for the complete environment. Could one of you @jackyalbo @nimrod-becker @jeniawhite @romayalon help us on this front.

**Comment by jeniawhite** [comment] 2021-09-09 16:49
@rkomandu 
Basically this got broken due to ODF changes, currently syncing with the ocs-operator team in order to understand how to continue deploying with olm script with the latest changes.

**Comment by nimrod-becker** [comment] 2021-09-30 07:39
ocs-operator bug is opened, issue is withing the ocs-op scripts, closing this one

**Closed by nimrod-becker** 2021-09-30 07:39 UTC
Labels: NS-FS
